### ISSUE TITLE
Better ways to handle SIGHASH_SINGLE bug

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1015]
Producing invalid data is surprising and may be difficult to debug.

Ideas for better handling:

* rename the function and return a different result type, renaming should trigger people to check what changed
* return something else than `Result` - weird but may be appropriate in this case
* remove the function - I guess no-go
* try to prevent the situation by construction (didn't look deeply but I guess this is hard/impossible)

Side note: this is a nice example of a bug that would've been prevented by `genio`-like generic IO traits (assuming one would use a proven non-panicking method instead of `expect`).

**Comment by dpc** [comment]
@Kixunil Any reference to the bug?

**Comment by dpc** [comment]
```rust
        if self.is_invalid_use_of_sighash_single(sighash_type, input_index) {
            // We cannot correctly handle the SIGHASH_SINGLE bug here because usage of this function
            // will result in the data written to the writer being hashed, however the correct
            // handling of the SIGHASH_SINGLE bug is to return the 'one array' - either implement
            // this behaviour manually or use `signature_hash()`.
            writer.write(b"[not a transaction] SIGHASH_SINGLE bug")?;
            return Ok(())\
        }
```
        
I don't get why we can't/shouldn't `Err("SIGHASH_SINGLE bug")` or something.

**Comment by dpc** [comment]
One could both write some garbage to `writer` and error-out.

**Comment by apoelstra** [comment]
There are transactions like this in the blockchain (at least, on testnet), but the issue here is that this function cannot possibly do the correct thing, since it is providing input to a hash engine, and nobody knows what input (if any) would result in the blockchain-enforced "numeric 1 hash".

The issue with returning `Err(SIGHASH SINGLE bug)` is that the current API will never error based on the transaction data, only on writer issues. If we were to change that it could cause panics in downstream code which `.unwrap`s these errors.

**Comment by dpc** [comment]
It is already returning `encode::Error`, so seems that people doing `.unwrap()` on it do it at their own peril.

All we want is for people not to have to write their own code here (so keep public), but also not do something stupid because they didn't handle right this case. Idiomatically if one can't use the system to protect the user from misuse, the name should raise an eyebrow. It seems to me that some combination of:

* `encode_signing_data_to` should return `Option<Result<(), encode::Error>>`,  with `None` meaning could not write the hash to `writer` and be a `#[must_use]`
* rename to `maybe_encode_signing_data_to` or something like that.

would make much harder to do the wrong thing. 


BTW. Could there ever be a SF that would make blocks with this magic hash == 1 invalid (after certain height?). Would it be worhtwhile


Also, a question. It seems like that there are two problems:

* protecting the API of this one function from being accidentally misused,
* protecting users from signing a tx that effectively generate a "anyone can spend tx"?

It seems that former is what we are worrying about here. Is the second one even an issue, or do I mis-understand the issue?

**Comment by dpc** [comment]
With the proposed changed, the `signature_hash` could change to:

```rust
    pub fn signature_hash(
        &self,
        input_index: usize,
        script_pubkey: &Script,
        sighash_u32: u32
    ) -> Sighash {
        let mut engine = Sighash::engine();
        if let Some(()) = self.maybe_encode_signing_data_to(&mut engine, input_index, script_pubkey, sighash_u32)
            .expect("engines don't error") {
           Sighash::from_engine(engine)
        } else {
            return Sighash::from_slice(&UINT256_ONE).expect("const-size array");
        }
    }
```

**Comment by dpc** [comment]
BTW `maybe_encode_signing_data_to` should probably return `Option<Result<(), io::Error>>` (not `encode:Error) too, if only IO error is ever expected.

**Comment by apoelstra** [comment]
> It is already returning `encode::Error`, so seems that people doing `.unwrap()` on it do it at their own peril.

It only returns errors if the underlying writer errors. It's perfectly reasonable to `unwrap` this currently and all of my code does so.

> BTW. Could there ever be a SF that would make blocks with this magic hash == 1 invalid (after certain height?). Would it be worhtwhile

No -- this sighash bug has been fixed in every new iteration of the signature hash, since segwit, and there's no interest in going back and further restricting old codepaths that haven't been changed. It would have technical risk, require community consensus, and theoretically could confiscate coins.

> It seems that former is what we are worrying about here. Is the second one even an issue, or do I mis-understand the issue?

I think you're misunderstanding -- if users sign the 1 hash, then yes, they are exposing themselves to potential theft (assuming they also do some other things wrong, i.e. reuse the address that they signed the 1 hash with). But this function can't output the 1 hash, so this isn't a problem here.

**Comment by dpc** [comment]
> It only returns errors if the underlying writer errors.

Then the error type should fixed, yes.

> But this function can't output the 1 hash, so this isn't a problem here.

So I do understand it now, though I didn't when wrote my first comment. And yes, that's why I want this function to return `Option`.

**Comment by apoelstra** [comment]
Yeah I like the idea of just wrapping the existing result return type in an `Option`!!
