### ISSUE TITLE
Bump version to 0.14.0

### ISSUE THREAD

**Issue by popzxc** [rust-bitcoin/rust-bitcoin#102]
Current version of `rust-bitcoin` has some new features (`Regtest` network, consensus parameters, corrected multiplication).

Would it make sense to bump the version of crate?

**Comment by apoelstra** [comment]
Yes. I will do that in a PR right before release.

We haven't really figured out a good process for this. I guess when we bump to 0.14, we should add an additional commit that bumps to "0.15-pre" or something, and then bump to 0.15 before publishing?

I agree that the current situation, where the git repo says 0.13 but we have breaking changes since the published 0.13, seems wrong.

**Comment by popzxc** [comment]
Well, in [exonum](https://github.com/exonum/exonum) we have a [`CHANGELOG.md`](https://github.com/exonum/exonum/blob/master/CHANGELOG.md) file which is updated in every PR. So, at the every point we have an actual list of changes for the current commit. Before release they are stored in `[Unreleased]` and on release it's just renamed to the appropriate version.

I guess some similar process will be enough here too.

**Comment by apoelstra** [comment]
Sure, I like that. Alongside 0.14.0 I'll create such a file and require updates in any PRs that change semantics.

**Comment by popzxc** [comment]
I'd suggest to create a `CONTRIBUTING.md` file with information for external contributors, so such a requirements won't be a surprice for them.

**Comment by popzxc** [comment]
I don't want to be intrusive, but @apoelstra could you please tell me when approximately version will be bumped? We need a release to use some of new features.

**Comment by apoelstra** [comment]
Today or tomorrow I should have time to go through everything outstanding in rust-bitcoin and rust-secp.

I want to release a new version of rust-secp soon that will overhaul the API, and to update rust-bitcoin to use this also in 0.14.

**Comment by apoelstra** [comment]
Once we have #125 (serde 1.0) and #113 (secp256k1 0.10) I'll release 0.14.

I'd prefer not to release without secp 0.10, since it would make the latest versions of rust-bitcoin and rust-secp incompatible, and merging secp 0.10 (which is ready) without serde 1.0 (which is not) would cause grief for serde users.

**Comment by ariard** [comment]
Really cool, waiting Regtest support to play with it on rust-lightning-bitcoinrpc :)
