### ISSUE TITLE
`Transaction::weight()` differs fom the actual weight of a serialized tx with 0 inputs

### ISSUE THREAD

**Issue by afilini** [rust-bitcoin/rust-bitcoin#1159]
I'm not sure whether this is expected or if it's a bug, but the implementation of `Transaction::weight()` considers transactions with zero inputs as non-segwit (it doesn't account for the marker and flag extra 2 weight units).

However, serializing a transaction using the consensus encode trait will push the extra marker and flag for transactions with zero inputs, so the actual weight of a serialized tx would be larger than what the `weight` method says.

Code here:

https://github.com/rust-bitcoin/rust-bitcoin/blob/bb4396266a6f27c73a010bd0ce9f51b052d52158/src/blockdata/transaction.rs#L866-L898

If there are no inputs, `inputs_with_witnesses` is zero, so the 2 wu are not counted

**Comment by apoelstra** [comment]
I'm of two minds here:
* we should fix `Transaction::weight` to match our own serialization code
* we should leave it as-is, since it matches the PSBT serialization code

IIRC in the non-PSBT case Bitcoin Core's serialization of 0-input transactions is not actually deserializable (this is an issue with BIP141 itself actually) so we already deviate from them in this case ... and since there is no consensus code that will accept 0-input transactions things are not really important.

In the PSBT case things **are** consistent, since PSBT always uses non-segwit serialization ... so my advice to anybody using 0-input transactions is "do this within PSBT and save yourself the grief".

**Comment by Kixunil** [comment]
Good points, I'm even thinking panicking for zero-input txes outside of PSBT could be a good idea.

**Comment by afilini** [comment]
It's fine for me even if it's left as-is, I just wanted to point out the inconsistency. Feel free to close the issue if you don't plan on changing this.

**Comment by Kixunil** [comment]
If we decide to leave it as-is I'd like to at least document it.

**Comment by apoelstra** [comment]
Agreed, my vote is to leave it as-is but document:

* For 0-input transactions this will return a value 2 less than the actual weight of the data coming from `serialize`
* But `serialize` does not handle 0-input transactions gracefully due to ambiguity between the "0 inputs" marker and the segwit marker, which are both encoded as hex `00` [link to BIP 141 or whichever is responsible for the segwit marker].
* ...therefore, if you must use 0-input transactions, we strongly recommend you do so within PSBT, and use the PSBT API, since PSBT requires non-segwit serialization and therefore avoids the ambiguity.

and we should keep this issue open to track this.
