### ISSUE TITLE
Literal out of range in src/blockdata/script.rs

### ISSUE THREAD

**Issue by jeandudey** [rust-bitcoin/rust-bitcoin#117]
It only happens on i686. Not sure how to proceed.

```
warning: literal out of range for usize
   --> src/blockdata/script.rs:525:22
    |
525 |             n if n < 0x100000000 => {
    |                      ^^^^^^^^^^^
    |
    = note: #[warn(overflowing_literals)] on by default
    = note: the literal `0x100000000` (decimal `4294967296`) does not fit into an `usize` and will become `0usize`
```

[Offending code](https://github.com/rust-bitcoin/rust-bitcoin/blob/45c699f00501263523993930a052405a7bf31364/src/blockdata/script.rs#L525)

**Comment by dpc** [comment]
@jeandudey The way to proceed is not to use `usize` for things that are not cpu-architecture dependent sizes.  I haven't seen the code, but I'm guessing that this `n` is of type `usize`, which works on x64, and not on x32 machines. `n <= 0xffffffff` won't help because it's true for every value of `n`.

**Comment by dongcarl** [comment]
If no one is taking this on right now, I'd like to run through the repo and find all `usize`s that shouldn't be.

**Comment by apoelstra** [comment]
@dongcarl go for it

**Comment by dongcarl** [comment]
Too much to do for me right now, anyone who wants to take this on please feel free.
