### ISSUE TITLE
Test with `-Z minimal-versions`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1229]
It'd be great to test the crate with minimal versions to ensure the dependencies are not under-specified. Ideally all crates, not just `bitcoin`.

**Comment by MUCCHU** [comment]
Hello @Kixunil I am interested in taking up this issue can you please guide me into it.

**Comment by apoelstra** [comment]
When we do this, I'd like to actually commit a "minimal" and "tested" version of `Cargo.lock` in `contrib/`. I actually have some infrastructure now that lets me locally test with multiple lockfiles (not in this repo yet, because workspaces add a bit of extra complexity with crate2nix, but in e.g. rust-bech32).

**Comment by Kixunil** [comment]
Yeah #1230 seems to be superior and I have a PR open there that I didn't have time to rebase and then forgot about it. Would you like to look at that instead @MUCCHU?

**Comment by tcharding** [comment]
This can be closed now because we have `minimal-Cargo.toml`.
