### ISSUE TITLE
Special purpose hash types (e.g. Txid) should impl `From<>` from their preimage type

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#1245]
(This issue has been totally re-written (by @tcharding) based on the discussion thread below.)

Our hash types can be created by various methods scattered around the place, the API would be more ergonomic if we provide `From` imps for them.

To close this issue you'll likely want to implement `From` for all the hash types created using `hash_newtype!` and `sha256t_hash_newtype!`

**Comment by nlanson** [comment]
Is this it?
https://github.com/rust-bitcoin/rust-bitcoin/blob/501821404d08e5ce6a7b6251b68f6f8ebc1f63a6/src/util/key.rs#L112-L119

**Comment by apoelstra** [comment]
Ah, there we go! This should also be a method on `PubkeyHash` itself and/or a `From` impl.

**Comment by tcharding** [comment]
> We have a PubkeyHash type that you need for Script::new_p2pkh etc but there's no way to construct it from a public key.

The issue description is incorrect as shown by the function posted above. 

> This should also be a method on PubkeyHash itself and/or a From impl.

So I'm not sure that we should be drawing this conclusion. We have discussed previously that `From` impls should only be provided in quite restricted cases. I'm not sure if "create a hash from this object" fits that or not but if it does there should probably be a bunch of other `From` impls for all the other hash types in `hash_types`. It seems like fixing this issue makes the API less good because now we have one `From` impl and no real reason why it exists.

Sorry @nlanson, I should have said this when the issue was posted but I didn't think of it until I was reviewing your PR.

**Comment by nlanson** [comment]
> So I'm not sure that we should be drawing this conclusion. We have discussed previously that From impls should only be provided in quite restricted cases. I'm not sure if "create a hash from this object" fits that or not but if it does there should probably be a bunch of other From impls for all the other hash types in hash_types. It seems like fixing this issue makes the API less good because now we have one From impl and no real reason why it exists.

Makes sense. It's no good having an inconsistent API and a close to redundant `From` impl.

I'll keep the PR open until hearing back from @apoelstra.

> Sorry @nlanson, I should have said this when the issue was posted but I didn't think of it until I was reviewing your PR.

No worries

**Comment by tcharding** [comment]
> Can you link to specific discussion? 

I don't remember where it was, I find searching github across repos for discussion threads quite difficult if its any more than a week or two ago - perhaps I'm getting old. 

> I don't remember any argument against Item -> ItemHash conversions assuming the conversion is obvious. From has no perf restrictions (e.g. it can allocate) and hashing is infallible.

I did not fully internalise the argument and in this case I tend to agree with you. My main objection was one of consistency.

> Should we have From<Item> for ItemHash for all instances?

At first blush I think we should, I don't know off the top of my head if we have hashes that require more than one input (making `From` impossible). Since all the hashes are defined in one file (`hash_types`) this is a reasonably easy investigation, might be a good fun first issue for someone.

**Comment by apoelstra** [comment]
I vaguely remember this discussion, where I argued that `From` shouldn't be super expensive (although as @Kixunil points out, this is not a rule followed by anyone else, including stdlib ... eg `String` has a `From<&str>` implementation).

In the case of hashes, which take well under a microsecond to compute on a modern CPU and involve no allocations, and where the semantics are obvious and error/edge-case free, I definitely think we should do it.

I agree that we should actually do more than just `PubkeyHash`, but actually we should do all the hashes.

**Comment by tcharding** [comment]
@apoelstra can you confirm you're ok with the issue description re-write please.

**Comment by apoelstra** [comment]
Confirmed, looks good.

It's an interesting thought to provide impls for *all* the hashtypes... eg `From<Transaction> for Txid`. But I think it makes sense. The goal is that when people see in the docs that they need one of these hash types, they can check the docs for that hashtype to find an obvious way how to construct them.

**Comment by tcharding** [comment]
This looks like its done, I started going through types created with `hash_newtype!` and it seems to be done - did not check all of them. I rekon we can close this.
