### ISSUE TITLE
`Sequence` and `PackedLockTime` should implement `From<u32>`

### ISSUE THREAD

**Issue by afilini** [rust-bitcoin/rust-bitcoin#1302]
I personally would find this useful in our `descriptor!()` macro, because it would allow me to accept a wide variety of types for the `older()` and `after()` fragments just by calling `Sequence::from(x)` or `PackedLockTime::from(x)`.

I'm sure there are other potential use-cases, this is just mine :)

cc'ing #1298 which is similar to this issue

**Comment by tcharding** [comment]
Thanks for raising the issue @afilini, there has been much discussion on this topic. FTR `Sequence` has a few constructors available, specifically `from_consensus`. Also the inner `u32` is public so `Sequence(seq)` works too. We explicitly did not add a `from<u32>` implementation (and the debate is raging still) because we wanted to make user code explicit and easily readable that it was a `u32` as represented by consensus code. Do you think we are wrong in being so conservative? Would a `From<u32>` be perfectly readable in your code? I appreciate your thoughts no this because we've had good arguments on both sides. Cheers.

Similarly there is `LockTime::from_consensus()` and a `From<LockTime> for PackedLockTime` impl, hoping that the following pattern is useful and clear `PackedLockTime::from(LockTime::from_consensus(x))`. Open to API suggestions for these types also.

Thanks again.

**Comment by afilini** [comment]
Yeah I know there are constructors available (and I've been using them in other parts of the code), my issue in this particular case is that there isn't a single "generic" constructor that works with all the types at once. Which is what the `From` trait is meant to be.

For example, the `PackedLockTime` can be constructed from a `u32`, from a `LockTime` or potentially even from another instance of `PackedLockTime`. At the moment there isn't a constructor to which I can pass either of these types and it will just accept them.

Having `From` implemented would allow writing functions like `is_timelock_expired<T: Into<LockTime>>(timelock: T)` which would work with all these types seamlessly.

Without it you are forced to pick one and then force the user to do the conversion, which can be a bit annoying I think.

If you think it's ambiguous to implement `From<u32>` on types like `LockTime` (because the user may think it means a timestamp for example) I guess you could also deprecate the `from` method in the impl, so that a warning is emitted. "Advanced" users who know what they are doing can disable the warning, but "newcomers" would see it and fix their code accordingly.

**Comment by apoelstra** [comment]
I don't think we can deprecate impls of trait methods, but even if we could, I'd concept NACK doing so ... it's an abuse of deprecation and anyway there's only one remotely obvious way to turn a locktime into a `u32`.

**Comment by tcharding** [comment]
I think we should provide these, we now have one "external" user of the library that has requested them. I think we should provide what users want, as well as keeping our conservative `from_consensus` constructors for those who want to use them.

**Comment by Kixunil** [comment]
@afilini I wonder if removal of `PackedLockTime` makes things easier. Are you sure you want to accept `u32` without the caller being explicit about it being a lock time?

**Comment by tcharding** [comment]
We have elected to not implement `From<u32> for Sequnce`, please see #2421 for discussion.

**Comment by tcharding** [comment]
Oh and `PackedLockTime` no longer exits.
