### ISSUE TITLE
Should Instruction implement Copy?

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#1368]
I noticed that `Instruction` doesn't implement `Copy`, but it looks like a cheap value type. I would generally derive `Copy` for such a struct. Is there a reason that it doesn't implement `Copy`?

**Comment by Kixunil** [comment]
Apart from obscure hypothetical of having owned push data in it I see no reason. Because adding such owned variant would be already breaking change I think it makes sense to implement `Copy`.

(We could also make the type more opaque so that it's possible but I don't really see it as very useful - it's mainly used in iterator and concatenating instructions allocates anyway.)

**Comment by casey** [comment]
I opened #1376 to derive Copy for Instruction.
