### ISSUE TITLE
Method for getting `TweakedPublicKey` from `TweakedKeyPair`

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#1452]
It looks like there's currently no way to get a `TweakedPublicKey` from a `TweakedKeyPair` except getting the `XOnlyPubkey` and calling `TweakedPublicKey::dangerous_assume_tweaked`. It seems like it should be possible to get a `TweakedPublicKey` directly from a `TweakedKeyPair`.

**Comment by Kixunil** [comment]
OMG, what were we thinking?

Suggested conversions:

* `From<TweakedKeyPair> for TweakedPublicKey`
* `From<&TweakedKeyPair> for TweakedPublicKey`
* `TweakedKeyPair::public_key(&self) -> TweakedPublicKey`

**Comment by casey** [comment]
> OMG, what were we thinking?

Seems like an easy thing to forget! I only need it because of some crazy nonsense I'm doing.

> * `From<TweakedKeyPair> for TweakedPublicKey`
> * `From<&TweakedKeyPair> for TweakedPublicKey`

These seem a little too magical to me, unless if it's in keeping with the rest of the API.

> * `TweakedKeyPair::public_key(&self) -> TweakedPublicKey`

This is kind of what I was expecting to find.

**Comment by Kixunil** [comment]
> keeping with the rest of the API.

We usually try to implement all reasonable conversion traits between the types for maximum idiomatic Rust experience. :)

**Comment by casey** [comment]
> We usually try to implement all reasonable conversion traits between the types for maximum idiomatic Rust experience. :)

I don't actually see any key pair -> pubkey `From` implementations. I think pubkey -> pubkey `From`s are probably unsurprising, but keypair to pubkey `From`s are a little wierd. That might just be me though.

**Comment by Kixunil** [comment]
OK, that's another hole.

**Comment by tcharding** [comment]
> I don't actually see any key pair -> pubkey From implementations.

What pubkey are you meaning? `KeyPair` is the secp256k1 type and we have `bitcoin::PublicKey` and `secp256k1::PublicKey`. Conversion between the secp types is implemented.

**Comment by casey** [comment]
> What pubkey are you meaning?

I mean any `impl From<KeyPair> for Pubkey` for any key pair or pub key type. Maybe I missed them, but I haven't seen any in rust-bitcoin. I don't mean conversion methods, like `key_pair.pub_key()`, only `From` implementations.

**Comment by Kixunil** [comment]
@tcharding we definitely can't do that one. But that reminded me we have same-named types in `bitcoin` so @casey obviously meant those, not `secp256k1` ones. I'm sorry for confusion.

**Comment by tcharding** [comment]
Cool, no worries. Cheers.

**Comment by tcharding** [comment]
> > OMG, what were we thinking?
> 
> Seems like an easy thing to forget! I only need it because of some crazy nonsense I'm doing.
> 
> > * `From<TweakedKeyPair> for TweakedPublicKey`
> > * `From<&TweakedKeyPair> for TweakedPublicKey`

These two are not possible because the conversion returns the parity as well.

**Comment by apoelstra** [comment]
We could implement a conversion for `(TweakedPublicKey, bool)`, and also do a conversion to `TweakedPublicKey` which simply drops the parity (which is not, in general, needed for an x-only public key -- though it is needed at spend time because bitcoin's consensus logic requires that bit be provided) (without it we couldn't do batch validation).

I could go either way on whether implementing `From` in a way that drops potentially-useful infiormation is a good idea.

**Comment by Kixunil** [comment]
> whether implementing `From` in a way that drops potentially-useful infiormation is a good idea.

I can see the concern if you contrast this with integers. In case of integers e.g. `From<u18> for u8` is not implemented because it'd drop the significant bits. But also when converting people usually think about integers semantics. Going from "I have 256 steaks" to "I have 0 steaks" is quite unexpected for humans.

OTOH, in case of tweked keys, we don't *silently* lose information. Any code that requires `Parity` requires it in API so if you lose it using `from` then you get type error. The conversion is also very obvious.

So I believe it's OK.
