### ISSUE TITLE
Add `fn minima_non_dust(script_pubkey: Script)` constructor to `TxOut`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1459]
This is useful for creating fee-bump (anchor) outputs. Computed as `serialized_size * DUST_FEE_RATE`.

**Comment by Kixunil** [comment]
Oh, do I remember it incorrectly? I though dust amount depends on script size but it seems to be constant? @apoelstra do you know?

**Comment by apoelstra** [comment]
It's both, sorta. The dust size for an output is determined by the minimum fee rate (1 sat/byte for the majority of nodes) times the *cost of spending a script*. For a "normal" p2pkh output this is a fixed size since all such scripts have the same size and same spending cost. I believe that Bitcoin Core has/had a constant corresponding to this, and that we copied it (it was around 640 sats?).

So regarding this method, I don't think it's possible to do for a general scriptpubkey (though we could do it in miniscirpt). Though we **could** do it for a few kinds of common addresses.

Also I guess the intention here is to make an output which has the minimal non-dust value (rather than the maximal dust value), so maybe we want `minimal_non_dust(Address) -> Option<TxOut>`?

**Comment by Kixunil** [comment]
The one I'm concerned about is the one that decides whether the transaction gets relayed. In case of hashed versions Core can not know but it has to choose something and I want to do the same thing.

`minimal_non_dust` seems like the name I intend, but I don't think we should limit it to address because policy checking code doesn't have that. But having a similar method on `Address` also makes sense but it has different semantics and should be documented appropriately.

**Comment by apoelstra** [comment]
Ah, I gotcha. So it does make sense to copy Core's behaviour even if this isn't (and can't be) very principled.

So, concept ACK this method (though I'd like it to be called `minimal_non_dust` or similar rather than `dust`), although I would need to check the Core source code to know exactly what its semantics should be.

**Comment by Kixunil** [comment]
Oh, finally found it: https://github.com/bitcoin/bitcoin/blob/7d515600034b84ebf23346a3642cf0a714880e25/src/policy/policy.cpp#L26
