### ISSUE TITLE
DISPLAY_BACKWARDS for `sha256d`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1534]
Is our usage of `DISPLAY_BACKWARDS = true` in the `sha256d` type correct?

In [bip143](https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#Backward_compatibility) there is a test that includes
```
  hashPrevouts:
    dSHA256(fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f00000000ef51e1b804cc89d182d279655c3aa89e815b1b309fe287d9b2b55d57b90ec68a01000000)
  = 96b827c8483d4e9b96712b6713a7b68d6e8003a781feba36c31143470b4efd37
```
This is displaying/parsing opposite to what our codebase does. Who is wrong, us or the BIP.

```rust
    let mut engine = sha256d::Hash::engine();
    let data = Vec::from_hex("fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f00000000ef51e1b804cc89d182d279655c3aa89e815b1b309fe287d9b2b55d57b90ec68a01000000").expect("failed to parse hex");
    engine.input(&data);

    let got = sha256d::Hash::from_engine(engine);
    let want = sha256d::Hash::from_hex("96b827c8483d4e9b96712b6713a7b68d6e8003a781feba36c31143470b4efd37").expect("failed to parse prevouts hex");
    assert_eq!(got, want);
```
Fails with
```
  left: `0x37fd4e0b474311c336bafe81a703806e8db6a713672b71969b4e3d48c827b896`,
 right: `0x96b827c8483d4e9b96712b6713a7b68d6e8003a781feba36c31143470b4efd37`'
```

**Comment by Kixunil** [comment]
Firstly, `hashPrevouts` is not very interesting to display so it shouldn't matter much. I don't think we even expose it.

If we do expose it it should be a newtype, probably with `DISPLAY_BACKWARDS = false`.

I'm wondering if the raw hash types should even impl formatting traits (apart from `Debug`), maybe everything should be a newtype.

**Comment by apoelstra** [comment]
@tcharding it is the BIP that's "wrong", but this is because (as @Kixunil is hinting at) there isn't really any standardized way to write "a double sha256" without knowing more about what it is.

>I'm wondering if the raw hash types should even impl formatting traits (apart from Debug), maybe everything should be a newtype.

This seems a bit extreme. If I could go back I think I'd make all the raw hash types implement `Display` in the natural way (lowercase hex, no reversing) and then make the reversedness a property of newtypes only. This would probably also simplify our reversing code and maybe avoid the `DISPLAY_BACKWARD` constant entirely.

But given that we **have** implemented sha256d `Display` to output hashes backward, and this is always the correct thing for Bitcoin types, and is probably behavior that people depend on for non-Bitcoin types, I think we should just leave it be.

**Comment by Kixunil** [comment]
Yeah, that makes sense. It might be interesting to provide `cfg` to turn it *off* (so not a cargo feature) so that people could inspect if they are accidentally relying on it but I'm not really sure how many people would want to.

**Comment by sanket1729** [comment]
FTR, in rust-miniscript we added a `hash256` module that has display forward. https://github.com/rust-bitcoin/rust-miniscript/blob/master/src/miniscript/hash256.rs
