### ISSUE TITLE
`Sighash` should be `ecdsa::Sighash` and `schnorr::Sighash`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1542]
These hashes are returned from `SighashCache` methods which can distinguish between them. Once we have them split we can have a `sign(&self, secp: &Secp256k1<impl Signing>, private_key: &secp256k1::SecretKey)` method on each to make signing more convenient and safe. (IMO it's an API hole that we don't have this yet.)

**Comment by apoelstra** [comment]
It may be that we want to put a marker type on `Sighash` instead. It's not really that sighashes are distinct if they're schnorr vs ECDSA, but that they're distinct if they're legacy, segwit, taproot, or $future_thing.

Using a marker type would also make it easy to be generic over these, so that you could write signing code that could handle any of them, e.g..

**Comment by Kixunil** [comment]
Is it interesting for anything to track legacy vs segwit? If yes, I might be on board but note that `hash_newtype!` doesn't support these marker types (yet?) and once we have another one for `KnownPreimage`/`UnknownPreimage` it could get annoying.

**Comment by sanket1729** [comment]
Are they already not separated as `TapSighashHash` and `SigHash`(both segwitv0 and legacy)?

**Comment by Kixunil** [comment]
Oh, crap, that's what we get by having the modules disorganized, I totally missed the other when checking. So I propose just adding helper methods and moving around, possibly renaming the types. I think they should be consistent - either reaname `Sighash` to `EcdsaSighash` or removed the prefix and have them in separate modules.

**Comment by tcharding** [comment]
#1597 uses `taproo::Sighash` but still closes this issue.
