### ISSUE TITLE
`script::read_uint` should read i32

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1547]
To close this issue you will likely need to dig quite deeply, into both Rust code and Bitcoin Core code. This issue  should not be taken lightly, will also need a whole bunch of reviewer time. Probably needs buyin from maintainers before starting.

Issue edited after comments below - terse on purpose.

Integers in Bitcoin are signed 32 bits but we provide `script::read_uint`

EDIT: Please see discussion in https://github.com/rust-bitcoin/rust-bitcoin/pull/2535#discussion_r1618309936

**Comment by Kixunil** [comment]
Firstly, I have no idea why reading unsigned int makes sense since ints in Bitcoin are *signed* 32 bits.

I think it should be `read_int(bytes: &[u8]) -> i32` and we should also have `read_{absolute,relative}_lock_time`. See also #1530 

And it should be a method on `PushBytes` after #1190

**Comment by apoelstra** [comment]
+1 to all of @Kixunil's suggestions.

`usize` is definitely wrong, but the correct type is probably `i32` since this reflects the numeric range accepted by all of the numeric opcodes, with the exception of the timelock ones.

TBH I'm not sure what this method is even there for ... we use it in our assembly output but nowhere else. rust-miniscript doesn't use it (we use `read_scriptint` instead, which seems a little suspicious).

**Comment by apoelstra** [comment]
On further reading I don't understand the purpose of this method next to `read_scriptint`. It seems like it does the same thing except wrongly and in a system-dependent way.

**Comment by apoelstra** [comment]
It looks like this all dates back to the 2015-era hand-rolled script interpreter (long since removed from this library due to the many inconsistencies with Core's consensus logic). `read_uint` was used to read things like the number of bytes to push given `PUSHDATA1/2/4`. It probably should have been removed when we removed the script interpreter.

**Comment by Kixunil** [comment]
ACK removing it but it looks like `read_scriptint` should also be renamed to `read_int`.

**Comment by apoelstra** [comment]
@Kixunil I'm unsure about that. `read_scriptint` is not symmetric with `push_int` -- the latter will push numeric opcodes, but the former won't parse them out.

And I don't think we want this to parse numeric opcodes, because the point of `read_scriptint` is that it parses *bytes*, not *script slices*.

I think we should hold off on renaming until we can move this into `PushBytes`. If it were a method on `PushBytes` I wouldn't mind calling it `read_int`.

**Comment by Kixunil** [comment]
A, crap, I see. Then I think it should be a method on `Instruction` to take into account opcodes.

**Comment by apoelstra** [comment]
If possible I'd still like a method on `PushBytes`, because [the rust-miniscript lexer calls this method once we already have a `PushBytes`](https://github.com/rust-bitcoin/rust-miniscript/blob/d524c6d9431906e2bbc12f076c7ac75e9216e53c/src/miniscript/lex.rs#L240).

If `read_int` was taking into account opcodes, then the giant match in that file would need to be split into an `if let Ok(n) = read_int` branch alongside a `match` that had a bunch of `unreachable!()` branches corresponding to numbers.

**Comment by Kixunil** [comment]
Yeah, I'm not opposed to `read_int` on `PushBytes` but needs good doc and perhaps a bit discouraging name. (`read_raw_int`?)

**Comment by Kixunil** [comment]
Hmm, I noticed it uses a funny way to check if the int is minimal. We should have a proper method for that. Perhaps return tuple with `bool` or something.

**Comment by apoelstra** [comment]
> Yeah, I'm not opposed to read_int on PushBytes but needs good doc and perhaps a bit discouraging name. (read_raw_int?)

How about `read_script_int` ;)

**Comment by Kixunil** [comment]
I never liked `script` in those names, it's already in the `script` module.

**Comment by apoelstra** [comment]
But the point is that it's a "scriptint" which is a particular encoding of integers used by the Bitcoin Script interpreter.

**Comment by Kixunil** [comment]
Ah, yet another term that only Core developers know about. Although this one is much better than the horrible name "script code".

I was thinking about conveying that it doesn't cover all ints. `read_non_minimal_int` or something.

**Comment by Kixunil** [comment]
That's part of it. The other part is having `read_int` on `Instruction`.

**Comment by apoelstra** [comment]
I don't think `read_scriptint` should be renamed. But yes, it should be moved to `PushBytes`.

**Comment by 15IITian** [comment]
>  The other part is having `read_int` on `Instruction`


@Kixunil 
Sorry I am not getting this -> as per the conversation, It seems that there were discussion about whether `read_scriptint` to put on `PushBytes` or `Instruction` ( where I think more preference for `PushBytes`),
and  regarding whether `read_scriptint` should be renamed to `read_int` or not -> so now  if  there is no need of renaming it -> then what the `read_int` actually is??

**Comment by Kixunil** [comment]
`read_scriptint` is a primitive that `Instruction::read_int` should call.

**Comment by apoelstra** [comment]
I think, to close this issue:

* We should have a sane `read_scriptint` function that can read 4-byte functions (done in #2535 but we have not decided whether we want to give it a parameter to control the maximum width)
* We should have a way to read and write 5-byte scriptints for locktime purposes. (We have gotten away without one for a while because Miniscript can't deal with 5-byte numbers, though we will need to address that at some point by changing the Miniscript spec. But BitVM wants 5-byte scriptints).
* We should have a way to read non-minimal scriptints and maybe a convenience method to check minimality?
* Maybe we should also have an equivalent of `CastToBool` in the Core script interpreter, which since Taproot is only used by `IFDUP` but pre-Taproot was used by all the `IF` opcodes? This is basically "read a scriptint" except that it can handle arbitrary-width integers, and it turns +/- into false and everything else into true.
* Any methods that can read/write only 4-byte scriptints should work with `i32` parameters. Those that handle bigger values should use `i64`.
* **However** writing an i32 may still require returning a `Result` because you can't represent `i32::MIN` in 32-bit signed magnitude.
