### ISSUE TITLE
`src.blockdata/script/types/owned.rs` is annoying to type

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1640]
I suggest removing (flattening) the types submodule.

**Comment by Kixunil** [comment]
Yes, filename (as suggested by slashes and `.rs`).

> FWIW Script is one of those things that should go a long time betwieen changes.

If you mean API, this change is entirely internal.

**Comment by apoelstra** [comment]
No, I just mean that once we're done the current refactoring, you won't have to type the filename anymore because we won't be touching it anymore :P.

**Comment by Kixunil** [comment]
I'm afraid that'll take a longer time than you think. We still have opcodes refactoring to do.

**Comment by tcharding** [comment]
Ah yeah, the extra `types` directory was probably over zealous of me :)

**Comment by tcharding** [comment]
I went to do it and remembered why I added `types/`, its so that we get a `types/mod.rs` to put all the imlps together instead of spread across `owned` and `borrowed` - this makes seeing which traits are implemented for which type easier, and since often the impl on `ScriptBuf` uses `as_script` to then call into the impl on `Script` it feels good to see the other code right away. Open to suggestions though, I too take such things as "typing such-and-such is annoying" as meaningfully worth fixing when they bother me all day.

**Comment by Kixunil** [comment]
How about having them in `script/mod.rs` in a section marked by comments or even inline `mod`?

**Comment by tcharding** [comment]
Yeah in `script/mod.rs` looks ok - I'll do it.
