### ISSUE TITLE
Get rid of all unsafety, add `deny(unsafe)`

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#170]
I think all the use of `unsafe` in this library is pre-1.0 stuff that can be made safe now. We should do that.

**Comment by apoelstra** [comment]
Two comments

1. On #rust people pointed out that you can override `deny(unsafe_code)` by putting `allow(unsafe_code)` on individual blocks. I'd probably ban anyone from the repo if they tried this ;) but better safe than sorry. We should use `#[forbid(unsafe_code)]` instead, that can't be overridden.
2. Unfortunately [this `transmute`](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/blockdata/opcodes.rs#L602) appears to have no safe equivalent. We have a `#[repr(u8)]` enum with 256 variants and need a way to convert a `u8` to the enum. Does anyone know another way?

**Comment by ema-fox** [comment]
Googleing around a bit there seems to be no satisfying standard way to convert integers to enums in rust. https://internals.rust-lang.org/t/pre-rfc-enum-from-integer/6348. There is https://crates.io/crates/enum-primitive-derive but reading the release notes keeping the number of dependencies small seems to be a goal of the project. In https://github.com/nikomatsakis/rust-memory-model/issues/41 the idea to use newtype + constants for all the values instead of enums was discussed.

**Comment by apoelstra** [comment]
Yeah, I really don't want to add dependencies for the sake of "hiding" unsafety. The one exception I make in many of my projects (though not rust-bitcoin) is to use `lazy_static` for things like log mutexes...and if `lazy_static` weren't in the rust nursery, I probably wouldn't even do that.

Unfortunately with regards to "are invalid enum values UB?" the answer is resoundly yes. The discussion you link seems to peter out in 2017 but more recently there is stuff like [this discussion about uninhabited types](http://smallcultfollowing.com/babysteps/blog/2018/08/13/never-patterns-exhaustive-matching-and-uninhabited-types-oh-my/) where it's clear that rustc can get a *lot* of mileage out of assuming invalid enum values never exist, and the language is not going to change to allow this.

Unfortunately-er, this case where we have a #[repr(u8)] enum with 256 variants so that there really are no invalid values, is very niche. I don't expect any language-level support for that case. The best we can hope for is a `TryFrom` impl, but `TryFrom` is blocked on the never type, which is blocked on very complicated-seeming design work.

**Comment by sgeisler** [comment]
> Unfortunately this transmute appears to have no safe equivalent. We have a #[repr(u8)] enum with 256 variants and need a way to convert a u8 to the enum. Does anyone know another way?

I see you inlined the function, but how performance critical is it actually? If we can afford one additional pointer add, deref and copy we could just build a big lookup table. The code duplication doesn't seem too bad since no variants will be ever added or removed and if one forgets to rename an existing variant consistently the compiler will complain about it. If there are nonetheless worries about code duplication I could try to build a macro for that.
