### ISSUE TITLE
Add BlockHeader method for returning difficulty as an f64

### ISSUE THREAD

**Issue by junderw** [rust-bitcoin/rust-bitcoin#1703]
https://github.com/rust-bitcoin/rust-bitcoin/blob/0.29.2/src/blockdata/block.rs#L132-L135

Currently the only method for returning difficulty is a u64.

https://github.com/mempool/electrs/issues/3

In some of the earlier blocks where the difficulty was less than 2, this shows the difficulty as `1` which is less helpful in the earlier blocks.

I am creating this issue for two purposes:

1. Ask for a method that returns difficulty as a f64.
2. If adding this method is not desirable, I would like help brainstorming ways to get the custom Uint256 type in this library to divide into an f64 nicely.

**Comment by junderw** [comment]
Related: https://blog.m-ou.se/floats/

**Comment by apoelstra** [comment]
Agreed, we should change the type, though it may be nontrivial to do the division. Thanks for the blog post!

**Comment by junderw** [comment]
I'll take a crack at it, it seems as though the blog post's method is fairly performant, so I'll start with a to_f64 (and also From<x> for f64) for the uint types.

f32 is not that useful, but if f64 is easy I might just add it anyways.

Then using that, we can change the difficulty to return f64.

2 PRs sounds reasonable.

**Comment by Kixunil** [comment]
> I'll start with a to_f64 (and also From for f64) for the uint types.

I guess start with `U256` and then call its impl from the others.

We normally use unit names for conversion (it's not always clear what it is), e.g. `Weight::to_wu()`. However IIUC `Work` and `Target` are unitless so I guess `to_f64` is fine.

Regarding `From` I don't believe it's OK to have it for lossy conversions. For instance `From<u64> for f64` doesn't exist because it'd be lossy. (OT: I just found `From<bool> for f64` is implemented - WTF?!)
