### ISSUE TITLE
Add `as_core_arg` module to implemenet `serde` using `Network::to_core_arg` and `Netwrok::from_core_arg`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1799]
This is useful in json RPC but others might find it useful too.

**Comment by Kixunil** [comment]
We put these along  the types, so that'd be `network::constants`.

**Comment by stevenroose** [comment]
Tbh I'm kinda meh when it comes to having core-specific implementations in general. If they make sense generally (like for values or feerates in denominations) or are widely used across the ecosystem (reversed hex hashes), it's ok, but for really specific things like this.. I mean sure it's the same naming as BIP70, so that would be OK I guess.. (Not to say that everyone hates BIP70 :sweat_smile: )

**Comment by apoelstra** [comment]
Lol! Yeah, let's forget that BIP70 exists.

But I agree with Kix that this is a small amount of code that will support standing up Core nodes compatible with rust-bitcoin software, and while sure, it's kinda Core-specific, this is also a super common and useful thing to do.

**Comment by stevenroose** [comment]
Nah, I don't hate you, no objection to this MR :) Arguments that it's really minimal code is ok for me.
