### ISSUE TITLE
"written in" date

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1816]
We have a bunch of files that include a date along with the license, these are at times wrong, and in my opinion not that useful because what does "written in" mean when the code is patched constantly?

For example, taken from `bitcoin/src/policy.rs` which was introduced 2 years ago in commit 2b777485f

```
// Written in 2014 by Andrew Poelstra <apoelstra@wpsoftware.net>
// SPDX-License-Identifier: CC0-1.0
```

@apoelstra do these "written in" bits serve some purpose still that you intended back in 2014 and you'd like to fill?

**Comment by apoelstra** [comment]
No, just legal cargo-culting.

**Comment by tcharding** [comment]
Cool, will remove the dates (at some stage). Thanks

**Comment by Kixunil** [comment]
I'm not sure if we should remove them. People might then find it harder to use the crate since it may cease to be legally valid (even though it's totally stupid). IDK anything about this though. I've seen projects having stuff like 2014-2023 but bumping some number every year is annoying.

**Comment by stevenroose** [comment]
Yeah these headers are kinda silly because they often include a single name and lots of people usually have added things to the file. IMO remove them all and if we really want something there for legal reasons, just add a generic one refering to "the rust-bitcoin org" or something generic and refer to the README, LICENSE and/or AUTHORS files.
