### ISSUE TITLE
`PrivateKey` is annoying to generate

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1823]
The required code to generate a private key:

```rust
bitcoin::PrivateKey::new(bitcoin::secp256k1::SecretKey::new(&mut rand::thread_rng()), bitcoin::Network::Regtest);
```

Which also requires to add `rand` dependency and keep the versions in sync (well, duplicates would work but that's not nice)/

I propose to add this in `rand-std` feature:

```rust
/// Generate a new private key using entropy from `rand::thread_rng()`
pub fn generate(network: Network) -> Self { ... }
```

Although renaming `new` to `from_parts` and changing `new` to generate instead would be nicer.

Tangentially, IIRC WIF does merge some networks similarly to what `Address` does so it's kinda related to #1819 and probably should have a dedicated enum instead of `Network`.

**Comment by apoelstra** [comment]
It would be really nice if WIF could use the same enum. I'm not sure.

So regarding `generate`, concept ACK. The rest of my comment here is about rust-secp rather than rust-bitcoin.

I also feel like we should rename `SecretKey::new` in rust-secp. `new` makes it seem like this is the standard way to produce secret keys, but it's really not. The common cases are deriving from BIP32 or parsing from a string. So the upstream method should be called `generate` or something as well to take its privilege away.

Also holy shit lol, you should not be able to make a secret key from a `thread_rng`. The `rand` crate has a `CryptoRng` trait bound for exactly this purpose, but somehow we are not using it here. We use it for schnorr signing...where it's not even really needed...and nowhere else.

**Comment by Kixunil** [comment]
[`thread_rng` is cryptographically secure](https://docs.rs/rand/latest/rand/rngs/struct.ThreadRng.html#impl-CryptoRng)

`SecretKey::generate` is indeed clearer and consistent with usage here, so that sounds great.

**Comment by kshitjj** [comment]
Hey @Kixunil @apoelstra,

To resolve the issue, should I add rand dependency to `Cargo.toml` in the way below? I have a PR ready but adding dependency in the way below doesn't feel right. 


`
[dependencies]
rand = { version = "0.8.4", features = ["std"] }
`
