### ISSUE TITLE
`ExtendedPrivKey::ckd_priv` is unreadable

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1866]
Apart from random-looking name it's not immediately obvious how does it differ from `derive_priv`. We should just make it private and possibly inline it into the for loop.

If a special method for single-child derivation is still desired (despite `&[child_numer]` being viable) we could just `impl AsRef<[ChildNumber]> for ChildNumber` so that `derive_priv` would work.

**Comment by apoelstra** [comment]
I think we should update the docs for `derive_priv` to say that you can now pass a lone `ChildNumber` as the path, and we should add a unit test for this as well.

**Comment by stevenroose** [comment]
I do remember in the origin of the bip32 module that there was some trait or so that both `&[ChildNumber]` and `ChildNumber` and some other types implemented. Found it, `IntoDerivationPath`, can that not be used always instead of `AsRef<[ChildNumber]>`? That latter one IMO would confuse a user as it might be more obvious that `ChildNumber` is `IntoDerivationPath`?

**Comment by Kixunil** [comment]
I guess I would just explicitly point it out in the docs. But it raises a question why the trait is no longer present. The good thing about `AsRef` is that practically all useful collections already implement it.

**Comment by tcharding** [comment]
>  But it raises a question why the trait is no longer present.

hmmm, this is a bit of a process fail, removing this trait is an API breaking change, should show up in changelog, but it doesn't. I tried looking for the patch/PR that removed it and couldn't. The best I can do is see that it was removed in the last release.
