### ISSUE TITLE
The docs claim this library is pure rust but it depends on `libsecp256k1` (and optionally `libbitcoinconsensus`)

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1867]
I know it's not clear if this is strictly lying but it could be misleading so maybe we should improve the wording.

**Comment by apoelstra** [comment]
We also depend on stdlib which uses compiler intrinsics...I don't think this is even close to lying to claim that it's "pure Rust".

**Comment by junderw** [comment]
*libc enters the chat*

**Comment by Kixunil** [comment]
> "pure Rust" for practical reasons

Yeah, that's what I had in mind.

Maybe saying "except for dependency on `libsecp256k1` and optional `libbitcoinconsensus`, this library is pure Rust" would suffice.

**Comment by junderw** [comment]
Feature flag all the secp related things, and have it on default.

That way at least we could also say "pure Rust with a simple feature flag toggle."

**Comment by apoelstra** [comment]
Feature-gating (basically) the entire library so that we can make technically-true claims *would* feel dishonest, plus it would inconvenience users.

**Comment by junderw** [comment]
The purpose wouldn't be for making the claim, but it would be for making things easier for those that don't want to deal with libsecp.

> In particular people who want "pure Rust" for practical reasons (WASM support) should be able to see in the README what problems they'll have, **what features they may need to disable**, etc.

The suggestion was to make your observation easier on them by consolidating it into one feature.

**Comment by apoelstra** [comment]
Without rust-secp you will have no keys, no addresses, no sighashes, no PSBT (without some difficult surgery), etc. rust-miniscript will not be usable, and by extension bdk or any other wallet software.

You will have blockchain primitives (blocks and transactions), hashes, and that's it.

IIRC there was a PR to add such a feature a year or two ago and we decided it was too invasive.

But I'm not opposed in principle, as long as the feature were on by default.

**Comment by stevenroose** [comment]
It would be nice to have a way to cut out the C stuff. And in principle we could have Address, i.e. pubkeys, because I think even in rust-secp, pubkeys are just byte arrays, not wrappers for C types (right? not 100% sure of this claim). So we could have just sk and pk types without the C stuff.

I have personally struggled with the C stuff in the past, but since we have that script that prevents naming collisions, it's been quite good. I mean not a single real Rust project will build when you don't have a C building toolchain present because libc etc.
