### ISSUE TITLE
Check for API breaking changes in CI

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1875]
As we move towards a 1.0 release it would be nice to check CI that we don't make breaking changes. Consider using 
- https://github.com/Enselic/cargo-public-api 
- https://github.com/obi1kenobi/cargo-semver-checks

**Comment by apoelstra** [comment]
We should definitely be using cargo-semver-checks -- though bearing in mind that it's still very incomplete and we can't blindly trust an "ok" from it.

`cargo-public-api` looks pretty interesting. I like the idea of committing the public API in `contrib/` or somethig and then diffing against that in CI, so that any API changes become visible (and easy to check for after-the-fact). And maybe there are lints we could run against the text file to check if e.g. all errors impl `Debug` and `std::Error` and so on. We'd have to experiment a bit to see how well it handles our feature-gating etc.

**Comment by tcharding** [comment]
Whats the status of this one crew, do we want it in before next release? The one on `bech32` has stalled. 

ref: https://github.com/rust-bitcoin/rust-bech32/pull/141

**Comment by Kixunil** [comment]
I'm not sure there should be rush but I want it eventually, definitely before 1.0 of any crate. Doing it sooner has the advantage of being able to auto-label PRs.

**Comment by apoelstra** [comment]
Let's just rebase #1880 and do it here, since Kix is onboard.

The history here is that we tried opening #1880 and got no reply from Kix after several weeks and were unable to move forward. So we switched to doing it in leaf crates where we didn't need Kix's approval (e.g. in rust-secp https://github.com/rust-bitcoin/rust-secp256k1/pull/656 and in rust-bech32). Then in rust-bech32 we have gotten no reply from Clark for several weeks :).

For what it's worth, it's worked great in rust-secp ... but that's not worth much since the API for rust-secp never changes :).

But since Kix is online and in favor of this, I think we should just pull the trigger instead of waiting on rust-bech32.

**Comment by tcharding** [comment]
> Then in rust-bech32 we have gotten no reply from Clark for several weeks

Just to clear the respond Clark did respond, it was back waiting on @Kixunil (because of merge strategy proposed by me). No one is really at fault here.

Anyways, I'll rebase and YOLO - if there are too many teething problems we can always revert.

**Comment by Kixunil** [comment]
I don't think this is really closed, the title suggests checking **breaking** changes, #2713 just "displays" **all** changes and we have no tool to highlight the breaking ones..

**Comment by apoelstra** [comment]
Yeah, we should add cargo-semver-checks, but we should **try to avoid a false sense of security** because it's really incomplete.

Though thankfully, the stuff it misses is often obvious to a human, and the stuff it catches is often really non-obvious.

The other issue is: what happens if there *are* breaking changes? Maybe CI should require an `[API-BREAK]` prefix or something in every PR that breaks the API? Because we don't want to forbid changes entirely (yet).

**Comment by Kixunil** [comment]
> because it's really incomplete.

There are so many weird semver footguns that it's probably already better than humans. And even if it isn't, just catching a few non-obvious ones makes it useful anyway.

> Maybe CI should require an `[API-BREAK]` prefix or something

Yeah, I like that. We have the API break label but we need to set it before CI runs. That's probably doable for maintainers but not others. Maybe we could allow saying `[API-BREAK]` in commit message which sets the label before the check runs.
Also the label should *invert* the check so that if someone claims to do API-break but it doesn't we detect it (though maybe it'll end up as a bug report at cargo-semver-checks).

**Comment by obi1kenobi** [comment]
Hi all! I'm the `cargo-semver-checks` maintainer 👋 Please ping me if you run into any issues.

> There are so many weird semver footguns that it's probably already better than humans.

It's already way better than humans. We have the data to prove it: https://predr.ag/blog/semver-violations-are-common-better-tooling-is-the-answer/

That study found that more than 1 in 6 of the top 1000 most-downloaded Rust crates has violated semver in a way `cargo-semver-checks` could have caught and prevented. We went to extreme lengths to validate those numbers: as just one example, for each semver violation we claimed, we produced [a "witness" program that relied on the broken functionality](https://predr.ag/blog/semver-violations-are-common-better-tooling-is-the-answer/#automated-validation-via-witnesses) and then validated that it indeed suffers a compile error as a result of upgrading to the broken release.

That study is a year and a half old. `cargo-semver-checks` today has almost twice as many lints as it did at that time, so it's gotten much better at catching breakage since then. If we re-ran that study, we probably would find even more semver violations that we missed the first time around.

> Maybe we could allow saying `[API-BREAK]` in commit message which sets the label before the check runs. Also the label should _invert_ the check so that if someone claims to do API-break but it doesn't we detect it (though maybe it'll end up as a bug report at cargo-semver-checks).

Small nit: we consider undetected (false-negative) semver violations as a missing feature (we have [a list](https://github.com/obi1kenobi/cargo-semver-checks/issues/5)), not a bug. We do not and cannot promise to catch everything — the pesky Halting Problem is in the way.

There are several categories of issues where `cargo-semver-checks` is known to miss things: https://predr.ag/blog/four-challenges-cargo-semver-checks-has-yet-to-tackle/

None of those are fundamental problems, and all of them are solvable with more funding and judicious application of engineering. If you do end up finding `cargo-semver-checks` useful and would like to see it improve further, I'd appreciate your support! I have a GitHub Sponsors page, or if it's easier for you, I'd be happy to post a bitcoin wallet address :)

**Comment by Kixunil** [comment]
Thanks for detailed version!

> the pesky Halting Problem is in the way.

How is it the Halting Problem? :open_mouth: I though it's just very large set of rules that are not straightforward. Is compatibility determined by computation?

**Comment by Kixunil** [comment]
Oh, OK, we have different definitions of what is breaking change. I mean I don't disagree with yours it's just not practical in the context - I wouldn't have expected any tool like `cargo-semver-checks` to check behavior, just check if the code is buildable.

**Comment by obi1kenobi** [comment]
Of course, that makes sense. Not everyone sees things the same way, though, and given the large number of people using `cargo-semver-checks`, I like to be explicit about what it can and cannot promise :)

**Comment by apoelstra** [comment]
obi1:
> That study is a year and a half old. `cargo-semver-checks` today has almost twice as many lints as it did at that time, so it's gotten much better at catching breakage since then. If we re-ran that study, we probably would find even more semver violations that we missed the first time around.
> 

I'm pretty sure I haven't look at it in more than a couple years. So I think it's probably way more complete than I remember :).

Kix:
>Yeah, I like that. We have the API break label but we need to set it before CI runs. That's probably doable for maintainers but not others. Maybe we could allow saying [API-BREAK] in commit message which sets the label before the check runs.
Also the label should invert the check so that if someone claims to do API-break but it doesn't we detect it (though maybe it'll end up as a bug report at cargo-semver-checks).

Sounds good to me. I'm not totally sure what value the label provides if the PR description or title already has `[API-BREAK]` in it, which we can programmatically detect just as easily as a label (I think). And we can certainly try negating the check and complaining if a claimed API break is undetected. Though my *guess* would be that we'll have enough false negatives that this would just need to be a warning (the bot can post a comment) rather than something that causes CI failures.

**Comment by Kixunil** [comment]
Filtering by label is super easy for instance. Warning is fine.
