### ISSUE TITLE
`TapTweakHash::into_scalar` returns different result on big/little endian machines

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1896]
This is going to return a different `Scalar` value depending on the endianness of the host machine:
```rust
    /// Converts a `TapTweakHash` into a `Scalar` ready for use with key tweaking API.
    pub fn to_scalar(self) -> Scalar {
        // This is statistically extremely unlikely to panic.
        Scalar::from_be_bytes(self.to_byte_array()).expect("hash value greater than curve order")
    }
```

Is this a bug?

**Comment by apoelstra** [comment]
Definitely a bug if true, but is it `from_be_bytes` or `to_byte_array` that is responsible?

**Comment by Kixunil** [comment]
Disclaimer: I only write this from memory and it's late here so I might be wrong.

Since Tobin didn't write why it returns different value, my guess is he assumes `to_byte_array` uses native endianess. It doesn't. It uses the same for all hashes (don't remember which one, I guess big since it's passed into `from_be_bytes`).

**Comment by tcharding** [comment]
Unless I'm missing something
`Hash::from_byte_array` calls `internal_new` which just copies the bytes in what ever representation they are passed in as then `to_byte_array` gives back the array, again in what ever endianness the machine is in, then `from_be_bytes` is called - seems like a bug to me.

**Comment by Kixunil** [comment]
That sounds like I guessed correctly. `from_byte_array` has a fixed endianess - independent of architecture, so does `to_byte_array`. We should probably document it.

**Comment by tcharding** [comment]
Oh so I think I know where I went wrong, writing it to make sure. 

1. The endian-ness of `Scalar::from_be_bytes` is in how the 32 byte scalar is mapped to an array of bytes _not_ the endian-ness of the underlying machine. 
2. And  I had a further brain fart yesterday by thinking that a contiguous block of memory (32 bytes) is effected by endian-ness. I definitely owe someone a beer for that.

Assuming (1) is correct, why do we even have both? Why not just `to_bytes`/`from_bytes`?

**Comment by Kixunil** [comment]
Correct. Endianess is only related to integer types, we just used fixed because there's no benefit from changing it (as opposed to native integer types which may have faster native operations).

It's not just `from_bytes` to make it more obvious which one we use. An argument could be made that hashes should have `be`/`le` as well but I think that since hashes are actually generally standardized (and the only odd ones are reversed and that is also only when displaying), it shouldn't be needed.

**Comment by apoelstra** [comment]
Scalars have an endianness because they're numbers. Endianness does not make sense for hashes, which are not numbers and do not have any parts that are more significant than others.

**Comment by tcharding** [comment]
Cool thanks lads.
