### ISSUE TITLE
Address's payload shouldn't be used by users

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-bitcoin#1908]
I was trying to read into Address's internals and I noticed it's kinda weird we have constructors in Payload instead of doing that logic in the corresponding constructors on Address.

I think we should remove all API on payload and just make it an internal data type and have all the code that is in there just be in the corresponding Address methods.

If people agree, I can MR this.

**Comment by tcharding** [comment]
I'm going to hack the shit out of the Address internals soon as the bech32 re-write is done. Making this stuff on Address instead of Payload will make that work easier so concept ack from me.

**Comment by Kixunil** [comment]
IIRC this was previously the case but it was changed to expose payload a few versions before. I never really liked the change TBH. I think it was motivated by making it possible to create shitcoin addresses or something, which this lib no longer supports.

**Comment by apoelstra** [comment]
I also agree that exposing `Payload` is a bad API.

I don't recall this being a deliberate thing, for shitcoin support or otherwise. I think it just sorta fell out of the separation between the base58 module, bech32 crate, and the various Bitcoin address types. And rather than writing a clean API, we just exposed a bunch of internals and moved on.

**Comment by Kixunil** [comment]
Oh, I actually misremembered what #643 did.
