### ISSUE TITLE
Hash newtypes that only hash one type of data should have a From impl

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-bitcoin#1909]
For example, all these:
```rust
        /// A hash of a public key.
        pub struct PubkeyHash(hash160::Hash);
        /// A hash of Bitcoin Script bytecode.
        pub struct ScriptHash(hash160::Hash);
        /// SegWit version of a public key hash.
        pub struct WPubkeyHash(hash160::Hash);
        /// SegWit version of a Bitcoin Script bytecode hash.
        pub struct WScriptHash(sha256::Hash);
```

should have implementations using `From` for the types they are supposed to has. So you can use `pk.into()` to provide a `WPubkeyHash`, f.e..

**Comment by Kixunil** [comment]
Should also work for references and, in case of script support `&Script`, `ScriptBuf` and `&ScriptBuf`.

**Comment by tcharding** [comment]
Ah yes, nice. Thanks.

**Comment by tcharding** [comment]
Turns out this issue was totally bogus, not the fault of the original author at all but in fact an epic win for those of use who are anal about code layout, if the From impls had have been near the type definitions it would have been immediately clear what was implemented. #1914 now moves the hash type defitintions around, this is in line with the recent pushes to remove "container" modules (`util`, `hash_types`).

**Comment by Kixunil** [comment]
Well, I hope this shows that opening issues based on reading the code instead of generated documentation is not great...

**Comment by apoelstra** [comment]
I think it's an argument for #1880.
