### ISSUE TITLE
Should we provide a pubkey to script code API?

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1920]
In #1776 @panicfarm introduces example code for generating sighashes. Part of that code looks like this (edited by me):
 ```rust
    let tx: Transaction = consensus::deserialize(raw_tx).unwrap();
    let inp = &tx.input[inp_idx];
    let witness = &inp.witness;
    println!("Witness: {:?}", witness);

    // BIP-141: The witness must consist of exactly 2 items (≤ 520 bytes each). The first one a
    // signature, and the second one a public key.
    assert_eq!(witness.len(), 2);
    let sig_bytes = witness.nth(0).unwrap();
    let pk_bytes = witness.nth(1).unwrap();

    let sig = ecdsa::Signature::from_slice(sig_bytes).expect("failed to parse sig");
    let pk = PublicKey::from_slice(pk_bytes).expect("failed to parse pubkey");

    //BIP-143: "The item 5 : For P2WPKH witness program, the scriptCode is 0x1976a914{20-byte-pubkey-hash}88ac"
    //this is nothing but a standard P2PKH script OP_DUP OP_HASH160 <pubKeyHash> OP_EQUALVERIFY OP_CHECKSIG:
    let wpkh = pk.wpubkey_hash().expect("compressed key");
    let spk = ScriptBuf::new_v0_p2wpkh(&wpkh);
    let script_code = spk.p2wpkh_script_code().expect("spk is known to be p2wpkh");
```

This logic that goes from the pubkey to the script code is the most difficult to discover IMO, should we have an API function for it? It would be quite hard to discover such a function if it was on `Script` but perhaps after we have script tagging and if "script code" is a thing then this would be more discoverable?

**Comment by Kixunil** [comment]
I think the API is also useful because it removes the `except` and since IIUC `script_code` does some hashing it could avoid intermediate allocation. So concept ACK.

**Comment by stevenroose** [comment]
Is it hard to discover? This is what you get when you search for "script_code" in the rust-bitcoin docs...

![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/853468/0f293d72-17bb-4035-bbb3-4958a391bead)

What might help is if the docs for these methods contain both the keywords "scriptcode" and "script code".

**Comment by apoelstra** [comment]
Agreed on using the keyword "scriptcode". And we should also think about how we word this stuff -- there are 5 different functions that all say "Obtains the pre bip-340 signature script code for this..." and the meaningful stuff is after the cutoff.

As a broader project maybe we should try to word our doccumments to pack the most information possible into the first 5-10 words. (And for these `script_code` functions in particular we should fix them. I'm hesitant to suggest a broader audit of the library because this is such a tricky thing to do and it'd be basically impossible to keep track of what had been done and what hadn't.)

But glad to see that this actually is fairly discoverable... from Steven's screetshot it looks like all the available plausible functions are already distinguished by type.
