### ISSUE TITLE
`hex_bytes` is slow

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/rust-bitcoin#207]
I am doing blockchain indexing  and when analyzing `perf` output of my indexer (which is quite CPU-bound at this point), I can see 10% of CPU time sitting in `hex_bytes`. I query blocks from the node, which get decoded from hex response to `Vec<u8>` and then to `Block` via `consensus_decode`. All of this happens in `rust-bitcoincore-rpc` https://github.com/rust-bitcoin/rust-bitcoincore-rpc/blob/master/client/src/queryable.rs#L23

Looking at:

https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/misc.rs#L24

I see the following room for improvement:

* output vector's capacity could be preallocated (should be typically 1/2 of the string length)
* `chars` is for handling Unicode chars, so I suspect there's quite a bit of overhead there. We can assume that the hex string is ASCII, and just convert it to `&[u8]` directly via `as_bytes()` and work on that; unicode characters are `> 128` so it all should be fine;
* the whole iterator-based approach seems suspicious, performance-wise; `pair`, `fold`; who knows how it gets optimized; a simpler, imperative code would be both more readable, and maybe faster

**Comment by sgeisler** [comment]
I did some benchmarking using @TheBlueMatt's implementations, the current one and two I wrote myself. You can find [the code](https://github.com/sgeisler/rust-bitcoin/blob/hex_bytes/benches/from_hex.rs) here and the [results on my T480s/i7-8650U CPU @ 1.90GHz here](https://gist.github.com/sgeisler/5a462edd7c5c9cdede84a97e8664ceb8).

On my machine my completely [non-functional-style implementation](https://github.com/sgeisler/rust-bitcoin/blob/hex_bytes/benches/from_hex.rs#L246-L279) is currently the fastest one. I even think it's quite readable, but I might be a bit biased :smile: 

The reason why we can't use the `Chars` iterator is quite sad: to me it seems that handling unicode codepoints isn't much more complicated than ascii characters, but what makes it inefficient in the end id that the `size_hint` is way off (lower bound is `len()/4` because of the max. UTF8 character size). That means we get many more allocations than necessary. At first I had an implementation using characters but this turned out to be a complete show stopper. I could have built a wrapper iterator struct that lets me add size hints after the fact, but imo it would still be slower then the currently fastest solutions or completely unreadable if written in a functional style.

You can benchmark it using `cargo bench`. If it's well received I'll PR my solution.

**Comment by dpc** [comment]
@sgeisler I don't think it's going to add anything, but just for double-checking: can you bench with a 4MB worth of hex-encoded data? That corresponds to a biggest hex string that could potentially be hex-decoded in Bitcoin, if I'm not mistaken.

**Comment by sgeisler** [comment]
I did the benchmark with 4M again and the [result](https://gist.github.com/sgeisler/09c263717de86d1460eb53a4e1c2bf42) shows a much smaller difference between the current and the better implementations (which can be expected due to memory latency/cache misses).

In terms of throughput the best implementation achieves 260MByte/s input or 130MByte/s output. That somehow doesn't sound really good to me, but also not horrible. One could try out a lookup table approach, but I won't right now.

**Comment by dpc** [comment]
https://github.com/nervosnetwork/faster-hex/ could be used as a datapoint too

**Comment by sgeisler** [comment]
That's a really nice crate :smiley: but avoiding unsafe is probably the bigger concern than speed in this case imo (except someone wants to do a really thorough review on it, but I doubt it), it also seems to require the 2018 edition of rust, which we won't be able to use for some time (#206).

The stats for 256bytes:
- current: `1773 ns`
- optimized: `464 ns`
- faster-hex: `98 ns`

The effect is even noticeable for 64 bytes but not that strongly.

Fun fact: switching to the current stable (because of `faster-hex`) made the current code 45% faster :laughing:

**Comment by dpc** [comment]
Now we know what are the ballparks here for original, and possibly optimal solution. I agree that lack of `unsafe` is more important and I'm personally satisfied with current speed. Thank you for working on it! I'll patiently await when this lands and gets released.

**Comment by TheBlueMatt** [comment]
Nice work, PRs welcome :p
