### ISSUE TITLE
rust-lightning is using << and >> on pow target values

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2161]
`rust-lightning`'s `lightning-block-sync` crate currently does right and left shift on a target. But with the 0.30 release we intentionally did not implement `Shl` or `Shr`.

ref: https://github.com/lightningdevkit/rust-lightning/blob/415cbf088ea238ff6c8d36c932d335b28fa0053f/lightning-block-sync/src/poll.rs#L141

This might be related to https://github.com/rust-bitcoin/rust-bitcoin/issues/1997, either way its goning to make it hard for them to use v0.30.0

**Comment by Kixunil** [comment]
If this is different from #1997 then we still should use the same approach: provide a higher-level method for whatever they are computing.

**Comment by apoelstra** [comment]
Yep -- they are computing the minimum and maximum difficulty of the next block by dividing/multiplying by 4. (And they are doing it (technically) incorrectly because they are not accounting for the absolute minimum difficulty.)

We do this computation internal to our new target adjustment logic. We should pull that out into its own methods.

**Comment by apoelstra** [comment]
And I think we can release a .1 with the new methods.

**Comment by tcharding** [comment]
>  (And they are doing it (technically) incorrectly because they are not accounting for the absolute minimum difficulty.)

ooof, we are doing it wrong too because the new min/max_difficulty_transition_threshold functions do not check the limits.

**Comment by tcharding** [comment]
We backported the transition functions so this can be closed.
