### ISSUE TITLE
Should `Network` be stored in `Params`?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2173]
It looks like the point of `Params` is that people could define their own (test) networks. However if one were to do that (presumably by calling `Params::new` and then modifying the returned value) the value would still contain `Network` which would falsely say it's one of the pre-defined networks. I think we should just remove it?

The field isn't accessed anywhere in this library.

**Comment by apoelstra** [comment]
We should arguably collapse `Network` into some sort of unique pointer to a `Params` struct. Maybe instead of being an enum, `Network` should store sha2 hashes of parameters and all the existing variants should be associated constants.

Or maybe we should just drop `Network` entirely and use references to `Params`.

~See #2169~ I see that you suggest pretty-much the same thing in #2169 :).

**Comment by apoelstra** [comment]
Looks like #2169 has taken over as "the issue to discuss this".

**Comment by Kixunil** [comment]
I'm not sure, do you realize it's about storing `Network` in `Params` not the other way around?

**Comment by apoelstra** [comment]
Yes -- we should probably rename the issue. But it is, in fact, where general discussion about "how should `Params` and `Network` relate to each other" is happening.
