### ISSUE TITLE
Displaying secrets

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2210]
Currently for `PrivateKey` we implement `Display` (using WIF) [0]. We derive `Debug` (bizarrely, only for "std" builds).

In secp256k1 we obfuscate secrets by hashing them, should we do the same here in `rust-bitcoin`?

[0] We also implement serder traits using WIF if `human_readable`

**Comment by apoelstra** [comment]
The entire purpose of the `PrivateKey` type in this library is to be WIF-displayed. So I think it does make sense to have a `Display` impl. `Debug` probably should not be std-gated :).

**Comment by tcharding** [comment]
> The entire purpose of the PrivateKey type in this library is to be WIF-displayed.

Oh? So its not a `PrivateKey` at all, its a `WifKey` (or some such name)?

> Debug probably should not be std-gated :).

I'm guessing this is just kruft from before we did obfuscation in secp.

**Comment by apoelstra** [comment]
> Oh? So its not a `PrivateKey` at all, its a `WifKey` (or some such name)?
> 

I guess so. I don't really understand this distinction.

**Comment by tcharding** [comment]
Just did #2214, closing this

**Comment by Kixunil** [comment]
> I guess so. I don't really understand this distinction.

`PrivateKey` should not have network to be consistent with `PubicKey` and if `WifKey` is desired it should be a separate type (or really just a method that takes network).

**Comment by tcharding** [comment]
I agree :)

> `PrivateKey` should not have network to be consistent with `PubicKey`

I always keep my pubic keys private.

**Comment by apoelstra** [comment]
> `PrivateKey` should not have network to be consistent with `PubicKey`

Ok, but that's not how bitcoin is used, or has ever been used. Public keys have always been network-independent and private keys (and addresses) have always been tagged with a network.

If we remove the network from `PrivateKey` then the type will be impossible to serialize and basically useless. If we require the user carry around a network flag independently, in order to pass to weird special-case encoding methods (since `Display`, `serde`, etc., do not let you pass in extra context like this) then the result will be undiscoverable and error-prone.

I'm happy to rename `PrivateKey` to `WifKey` if that makes people happy, but I also think that's less discoverable than the current situation.
