### ISSUE TITLE
`CompactTarget` is missing `LowerHex` and `UpperHex` impls

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2219]
These are useful and [used in the wild](https://github.com/lightningdevkit/rust-lightning/pull/2740/files#diff-f682e21555e68461ae57aa4d4c3b5048c94b1a3b4b76ce537bf9b62bfe7b4f69R311).

**Comment by crywolf** [comment]
Hi @Kixunil ,
I have implemented these traits for CompactTarget, but `pre-commit` githook does not allow me to commit the file I changed, because `cargo +nightly fmt --check` yells at me about some formatting issues in completely unrelated file I have not touched: `rust-bitcoin/io/src/lib.rs`. 

I've changed only `rust-bitcoin/bitcoin/src/pow.rs` which has no formatting issues. 

How to solve it? Should I just skip the hook?

**Comment by apoelstra** [comment]
@crywolf yeah, just skip the hook.

@tcharding I guess we should remove that from the githooks? Are they installed automatically somehow or do people need to manually remove the hooks now that we're not forcing the library to be formatted every day?

**Comment by crywolf** [comment]
I've skipped the hook. 
They are not installed automatically, I just followed README and installed it manually before. Deleting the last line in that hook should be enough.

**Comment by crywolf** [comment]
I deleted that rustfmt check from githook here #2222 so it should work for everybody now
