### ISSUE TITLE
Use `ArrayVec` in `key::SortKey`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2276]
This would simplify the code and allow us to not initialize data past the key length improving performance of generating the compressed sort keys.

**Comment by Harshit933** [comment]
Hello!,
I am new to this project and I want to contribute. Can you please explain this issue a bit more so I try to fix it or are there any beginner friendly issue that you can suggest.
Thanks.

**Comment by Kixunil** [comment]
I think this is quite beginner friendly.

In `bitcoin/src/crypto/key.rs` find `struct SortKey` and change it to `struct SortKey(ArrayVec<65>)` (use the `arrayvec` crate), then change the code to simply convert the bytes into `ArrayVec` - I think simple `if self.compressed { self.inner.serialize().into() } else { self.0.serialize_uncompressed().into() } should work. (Check the `ArrayVec` API if not.)

And that's probably it, don't forget to add the dep to Cargo.toml. :)

**Comment by Harshit933** [comment]
I read about the ECDSA curve and got to know about two types of keys, uncompressed and the compressed one. Thus, while converting the compressed key bytes which are of length 32 into `ArrayVec<u8, 65>`. It showed me the error that ``the trait `From<[u8; 33]>` is not implemented for `ArrayVec<u8, 65>``.

While the `ArrayVec<u8, 65>` would work for uncompressed keys. How should I manage it for the compressed ones?

One more question, We need to copy both the x and y coordinates for the key into a same `ArrayVec<u8, 65>` and then run the unit test for both of them combined rather than comparing the left and right quantities which is implemented in the code for now. Right?

**Comment by Kixunil** [comment]
Oh, I think you need something like:

```rust
let mut buf = ArrayVec::new();
buf.extend_from_slice(self.inner.serialize());
SortKey(buf)
```

for the compressed case.

You don't need to worry about curves and coordinates, the `serialize()`/`serialize_uncompressed()` methods already deal with all that. Just pass around the bytes. Note that comparing bytes is the correct thing because that's what Core/BIP implements. (Lexicographical sorting).

**Comment by Harshit933** [comment]
Got it
