### ISSUE TITLE
auxpow support

### ISSUE THREAD

**Issue by sidhujag** [rust-bitcoin/rust-bitcoin#232]
Is there any support coming for auxpow? If not then any hints on best practices to integrate into your codebase?

**Comment by sidhujag** [comment]
Just need to parse and possibly validate POW. Its pretty easy to parse, I have it working with tests passing in my fork but I think an abstraction so that blocks are processed according to the test on if auxpow is present (version bits would tell us). That would be ideal so it becomes chain agnostic.

**Comment by sgeisler** [comment]
What exactly is the use case of this and how big would the change be? It sounds like it's something to support other crypto currencies? If that's the case we'd really want to limit the scope of the changes.

**Comment by DR-BoneZ** [comment]
the rust bitcoin crate has enough functionality to parse out auxpow headers, you just can't use the block parsing function directly. you have to parse it piece by piece. I've already written code to parse out auxpow headers in dogecoin for one of my own projects, and I'd be happy to pr it in if it's wanted.

**Comment by sgeisler** [comment]
It sounds like it would be reasonable to create a separate crate for these altcoins that reexports some of `rust-bitcoin`'s types and adapts it where necessary (e.g. adding auxpow support). The burden on the `rust-bitcoin` maintainers seems too big otherwise since someone had to read up on the respective standards.

If there are certain design choices that make adapting it hard/impossible I'd be much more open to revisiting these. If extending the library is hard that's probably something we want to fix.

**Comment by dongcarl** [comment]
Closing, please let us know if library ergonomics are non-optimal.
