### ISSUE TITLE
`coveralls` notification is a bit spammy

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2394]
Every time one raises a PR `coveralls` posts and this causes a notification - feels a bit like spam.

**Comment by Kixunil** [comment]
Yeah, but it's usually pretty easy to filter-out if you don't care. But maybe we can set it up to post only when coverage decreases by more than 1%?

**Comment by apoelstra** [comment]
I agree that it's not too big a deal since it's only one comment with a distinctive shape. But if there's an easy way to reduce it, yeah, we might as well.

At this point we only really care about it for PRs that are explicitly improving test coverage ... when we get our test coverage up to near 100% then we will start caring about new PRs causing reductions.

**Comment by tcharding** [comment]
Oh I meant when viewing the `github.com/notifications` page. But the comments are good ideas too.

**Comment by Kixunil** [comment]
@tcharding you can look at the icon to the right - the topmost is the latest comment so if you only see your and coveralls you can safely skip the notification

**Comment by tcharding** [comment]
Yeah that is what I was doing when I created this issue, seems like a machine should do that for me. Anyways, closing.
