### ISSUE TITLE
Status of Taproot support in `psbt` module?

### ISSUE THREAD

**Issue by soralit** [rust-bitcoin/rust-bitcoin#2418]
Hi team, I'm from Keystone Wallet, my team used `rust-bitcoin` library to build bitcoin features on our product Keystone 3 Pro for a long time and really thanks for your great work 😄 
We intent to introduce Taproot based on PSBT into our product recently, we have done some researches on it and have made a POC version which is working well. 
It's good to know that there is an example about how to use taproot with PSBT. However I noticed the `psbt` crate didn't include taproot support yet, while our codes are based on `psbt`.
So I wondering what's the status on the taproot support in `psbt` crate? Is there an ETA?
We're happy to contribute code if needed.

**Comment by Kixunil** [comment]
You might be confused because the `psbt` **crate** is not maintained by us while the `bitcoin::psbt` **module** is. (We plan to turn it into a crate.)

The code currently doesn't support **signing** but IIUC it does support other things. I think it shouldn't be too hard to add signing and we'd be happy to get a PR for that.

We're mostly focusing on getting the most important parts of the library stable lately but I think getting taproot signing in PSBT would be fine especially given someone actually needs it.

**Comment by soralit** [comment]
Thanks for reply, sorry for the misleading, actually I mean the `bitcoin::psbt` module :) 
That's good to know you're happy for the PR, we'll do a self code review first and then raise a PR to this repo.

**Comment by soralit** [comment]
Hi @Kixunil , it seems that you're doing a API refactor on the `master`, and it is different with the latest release `bitcoin-v0.31.1`, do you have an ETA about the next stable release?

**Comment by Kixunil** [comment]
There's a proposal to release around end of March, see https://github.com/rust-bitcoin/rust-bitcoin/discussions/2375

However "stable" is years away. There's a ton of work to do and even if we magically had the work finished today we'd still have to wait because we want to stabilize with MSRV at least 1.65 which has important API-related features and we have policy of supporting two year old compilers that have to be in the latest Debian stable, so it's currently at 1.56.

**Comment by apoelstra** [comment]
>However "stable" is years away.

To be clear, we expect "years" to mean "at most two". But yes, there is a ton of work and the next several releases will continue to have big API breaks (though progressively smaller ones).

**Comment by yancyribbens** [comment]
rust is gonna be great when it's finished :)

**Comment by soralit** [comment]
Hi @Kixunil , my colleague has already raised a PR #2458, would you please take a look when you have time? :)

**Comment by tcharding** [comment]
This can be closed once the 0.32.0 release comes out I believe since it includes #2458.
