### ISSUE TITLE
CI build release testing

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#2479]
Should CI perform building and testing in release mode with `--release`?: 

Propose adding `cargo test --release` to `contrib/test.sh` someplace.

**Comment by tcharding** [comment]
Personally I have a feeling this will introduce a lot of churn, require a bunch of feature gating, and not add much value. The behaviour (ie., ops, checked/unchecked etc) of all the integer types has not been fully thought through. Doing so requires quite a lot of thought for the dev and the reviewer, I have been putting the task off for this reason. Feels like something that would be better done in `units` when its released and closer to stable then work slowly up the tree of crates. Is there some other code other than integers that this will help test?

**Comment by apoelstra** [comment]
I used to run the tests locally with `--release` but had to stop because some tests were broken (did not panic when we expected them to). When testing #2463 I confirmed that I could re-enable `--release` but then I turned it off again.

So I wouldn't mind turning this on **except** it would double our CI test matrix and compiling in release mode is really slow. Maybe we should do it for `units` (when it is out) but not for other crates.

**Comment by yancyribbens** [comment]
Alright, I don't mind about adding/not adding it to CI if others don't.  Just noticed that `--release` was broken and I thought adding it to CI would help maintain it.

**Comment by Kixunil** [comment]
I don't think this is valuable, it just slows down testing which is already huge. But I guess @apoelstra has a point with `units` since we might want to test the overflow behavior. Still, I'd suggest building in debug with `debug_assertions` off.

**Comment by yancyribbens** [comment]
Closing for now, no clear consensus.
