### ISSUE TITLE
`master` still has version set to `0.32.0-rc1`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2724]
I've done something wrong during the release process; `master` should be on version `0.32.0` now too.

**Comment by tcharding** [comment]
Found with: https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools/pull/2

That tool is "so hot right now" :)

**Comment by apoelstra** [comment]
> I've done something wrong during the release process; `master` should be on version `0.32.0` now too.

So, in many projects we would set it to "0.32.99" or something goofy like that to emphasize to any users that this is a pre-release. In Rust it might make sense to put it as `0.33.0.pre`.

Alternaely we could set it to 0.32.0 as you suggest. But I don't think it's wrong for it to deviate from any release branches.

**Comment by tcharding** [comment]
No worries, if it doesn't matter lets just leave it as is.

**Comment by apoelstra** [comment]
Well, I think leaving it at an rc number is still misleading and we ought to change it. It's true that it "doesn't matter" in the sense that anybody using master will be pinning by git rev rather than by semver version, but I still think we should choose something that won't be confused with a real revision.
