### ISSUE TITLE
Support for testnet4

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2749]
This is a good exercise of our `Network` changes. testnet4 is not yet entirely nailed down, though there is a Core PR that defines some parameters https://github.com/bitcoin/bitcoin/pull/29775. Notably this is a new network which introduces new difficulty-changing logic.

We should sort out our `Network` stuff and then afterward see how minimally-breaking a change we can make to add `Testnet4`.

cc https://github.com/bitcoindevkit/bdk/issues/1429

**Comment by yancyribbens** [comment]
This seems to be an argument for Network being non-exhaustive since this suggests adding another network, Testnet 4?

**Comment by apoelstra** [comment]
No, it is an argument for our functions taking `impl<Params>`, and maybe for `Params` being non-exhaustive to cover new consensus logic flags.

If it were `#[non_exhaustive]` how would any existing code have prepared for a new network that had a new difficulty adjustment algorithm that nobody had conceived of until a month ago? They couldn't have, so the best they could've done is add a `_ => panic!()` branch to all of their matches, meaning that they have untestable panic paths (that suddenly become active due in rust-bitcoin "minor releases" no less).

This has all been litigated to death in the "make `Network` `#[non_exhaustive]`" issue. We decided to replace `Network` with `impl Params` everywhere that we accept it as a parameter, so that the type is then never directly used. Then users can just recreate it themselves so it doesn't matter how useless we make our version.

**Comment by yancyribbens** [comment]
@apoelstra thanks, I didn't see #2541 which I guess makes sense.  So it sounds like downstream consumers may implement networks however they want roughly speaking.  Maybe I'm missing it, but some type of doc update to describe the use of Param and the reasoning would be helpful for implementers imo.  Anyway, it seems that testnet4 would deprecate testnet3 and so some of the fields in ` pub const TESTNET: Params = Params` may need to be changed (which could be a breaking change if testnet4 is radically different).

**Comment by Kixunil** [comment]
Disclaimer: I'm still low on time but I saw some people are seriously doing tetnet4 and I felt compelled to join the discussion.

It's a big question what should the `Testnet` variant mean. Since testnet4 has a different genesis block it already cannot mean "all testnets".

I see these possibilities:

1. `Testnet` means testnet3, we add a variant for each subsequent testnet. This may mean we end up with a bunch of useless variants.
2. `Testnet` means whichever testnet the latest released Core supports at the time of rust-bitcoin release. If you used testnet3 some future version of our library will rug you and change it to testnet4
3. Resetting testnet is a breaking change, so if shitcoinists trigger a testnet reset they'll also trigger the whole rust-bitcoin ecosystem breakage.
4. Stop supporting testnet in the enum entirely because it's too messy and testnet is impractical anyway.
5. Have a numeric version inside the variant or `#[non_exhaustive] enum TestnetVersion { ... }` though this is basically a form of a useless variants, just swept under the rug (the practical difference is that matching on "any testnet" is easier")
6. Remove the whole `Network` enum, everyone should define their own.

Honestly I think all options are quite terrible. I kinda want option 4 but I guess 5 is more realistic. If testnet4 had infinite inflation (doubling instead of halving) then it would be unusable for scams and I'd be more confident it won't reset again in a very long time and perhaps argue that 2 is fine.

**Comment by apoelstra** [comment]
Of all of those I prefer option 1 and I think that's what we'll wind up having by default. I agree that it may result in "useless" variants. And it could be that we have a new testnet every few years, as some people are suggesting on-list as a way to pre-empt testnet coins having a market value.

So option 5 is very interesting, where we sweep all the test networks under a single variant with extra fields to disambiguate.. at some point if we have too much detail we have just recreated `Params`. But having a numeric version (probably for type safety we want a newtype that can only represent known testnets ... but it should support comparison opcodes etc so people can do ranged comparisons, because I expect most networks will differ in their genesis blockhash and nothing else).

The cost for us to support this isn't too bad so I don't think it's worth throwing stuff away (your options 4 and 6). Nor do I think there's any need to say "ecosystem-wide breakage!" and push major revs for every testnet (option 3). And I definitely don't think we should say "`Testnet` means latest testnet" and rug people (option 2).

So in my view it comes down to a choice between 1 and 5. Which is more of an aesthetic decision than a technical one.

**Comment by yancyribbens** [comment]
Funny, I was thinking more along the lines of option 2.  And instead of "rug" I had more imagined deprecation period so implementers would have a chance to update.  I mean, why support old version of testnet once testnet4 is in place other then to give implementations a time to shift.

**Comment by tcharding** [comment]
Option 1 seems like it would make for easier pattern matching (and having to care less about testnet specifics).

**Comment by Kixunil** [comment]
@tcharding depends on which code does the matching. If you care about which testnet it is then yes, it is shorter but I don't think it's a huge difference:

```rust
match network {
    Network::Testnet3 => ...,
    Network::Testnet4 => ...,
    Network::Bitcoin => ...,
    _ => ...,
}
```

Vs


```rust
use bitcoin::network::Testnet;

match network {
    Network::Testnet(Testnet::V3) => ...,
    Network::Testnet(Testnet::V4) => ...,
    Network::Bitcoin => ...,
    _ => ...,
}
```

OTOH, if you don't care about version you need to write `Network::Testnet3 | Network::Testnet4` and update the code whenever a new version is added.

**Comment by apoelstra** [comment]
It also lets you say "any testnet, even yet-unknown future ones" by matching on `Network::Testnet(...)`, which is impossible to do if all the testnets have separate variants.

Doing so will make your code more fragile since it means any future testnet that invalidates your assumptions will break you ... but ok, breaking testnet-only code is not the end of the world. And you'll have plenty of warning in any realistic scenario.

I am warming up to option 5.

**Comment by junderw** [comment]
```
- Have a numeric version inside the variant or #[non_exhaustive] enum TestnetVersion { ... } though this is basically a form of a useless variants, just swept under the rug (the practical difference is that matching on "any testnet" is easier")
```

Option 5 :+1:
