### ISSUE TITLE
Are we enforcing the 520 stack element limit for segwit transactions?

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2793]
[BIP-141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki) includes:

> The witnessScript is deserialized, and executed after normal script evaluation with the remaining witness stack (≤ 520 bytes for each stack item).

I can't see anywhere we are enforcing this (we are enforcing the P2SH script size limit when creating an address which is also 520 bytes and uses the badly named `MAX_SCRIPT_ELEMENT_SIZE` which sounds like it should be used for the witness stack elements.

**Comment by apoelstra** [comment]
Ah, I see why you are bringing up this issue though -- the one place where it does apply and where users might conceivably hit it is when constructing P2SH spends, since there their entire script needs to appear on the stack. (And actually, here is a place where Miniscript needs to care about it, and rust-miniscript does enforce it.) (The Core wallet I think just doesn't bother supporting Miniscript in p2sh.)

So, we definitely should enforce it when constructing scripthashes from scripts. As far as Bitcoin is concerned, if the preimage to a scripthash is 521+ bytes, it simply has no preimage.

**Comment by tcharding** [comment]
Ok, thanks man. This issue is closed by #2794.

**Comment by Kixunil** [comment]
Then close it. :)
