### ISSUE TITLE
`SegwitV0Sighash` is missing an `into_secp256k1_message`

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bitcoin#2821]
The common operation to do on a `SegwitV0Sighash` is to convert it to a secp256k1 `Message` for signing, it seems like we'd benefit from having that be available directly.

**Comment by tcharding** [comment]
We have that by way of the `impl_message_from_sighash` macro.

```rust
macro_rules! impl_message_from_hash {
    ($ty:ident) => {
        impl From<$ty> for secp256k1::Message {
            fn from(hash: $ty) -> secp256k1::Message {
                secp256k1::Message::from_digest(hash.to_byte_array())
            }
        }
    };
}
```

**Comment by apoelstra** [comment]
Oops, we were supposed to change our sign methods to take an `Into<Message>` so that users wouldn't have to do the conversion themselves (or even think about the `Message` type) but [we decided to "leave that for later" without opening a followup issue](https://github.com/rust-bitcoin/rust-secp256k1/pull/686).

**Comment by tcharding** [comment]
Can we close this @apoelstra or is it tracking something that I'm missing still?

**Comment by apoelstra** [comment]
Yep, can be closed.
