### ISSUE TITLE
New hash data types (Txid etc)

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#284]
Currently sha256d::Hash type is used for all txids. However, this type is also used by many other projects using rust-bitcoin for other purposes as well, like working with generic hashes, not related to the transactions. Thus as a safety reason I propose to define a custom type alias for txid as `TransactionID`. If there are no objections, I'll do the corresponding PR

**Comment by dpc** [comment]
In the project I'm using `rust-bitcoin` for, I do use type-alias `BlockHash` and `TxHash` to readabilty. I wanted to go to newtypes, but haven't got to yet.

I think it does makes sense to have these types wrapping the underlying hash, to allow people expressing which hash exactly they expect, and do it in interoperable way between different project using `rust-bitcoin`. 

The type itself can probably `Deref` to the underlying hash type, and have `From` implemented too.

**Comment by dr-orlovsky** [comment]
I will work on the change and PR it then

**Comment by apoelstra** [comment]
Sounds good to me. We've gotten a lot of mileage out of the `OutPoint` type which is similar.

**Comment by stevenroose** [comment]
It's actually quite annoying to do a newtype on those types because of all the impls we want on them. I recently did this for `AssetId`: https://github.com/stevenroose/rust-elements/blob/elementshash/src/issuance.rs#L37 and I skipped lots of the index traits.

For rust-slip21 I did a new `([u8; 64])` newtype with all the traits (index borrow asref serde ...) and you can see most of the create is trait impls: https://github.com/stevenroose/rust-slip21/blob/master/src/lib.rs#L17

**Comment by apoelstra** [comment]
Yeah, I think it makes sense to define a `hash_newtype` macro of some sort in `bitcoin_hashes`. We have similar requirements for Simplicity where we have different types of Merkle roots that we want to keep separate.

**Comment by stevenroose** [comment]
I created a newtype macro: https://github.com/rust-bitcoin/bitcoin_hashes/pull/59

With that macro, we could easily define types like
```rust
hash_newtype!(TxHash, sha256d::Hash, doc="A Bitcoin transaction hash/transaction ID.");
hash_newtype!(BlockHash, sha256d::Hash, doc="A Bitcoin block hash.");
```

**Comment by dr-orlovsky** [comment]
I'm finally planning to implement it. What would you suggest as a best place to put these definitions?

**Comment by apoelstra** [comment]
Probably in `src/lib.rs`. But to be clear, a txid is not a transaction hash or vice-versa.

**Comment by dr-orlovsky** [comment]
Anyway it looks like it will be easier to introduce all new hash types in one PR. Can we enumerate all that we need, like https://github.com/rust-bitcoin/rust-bitcoin/issues/320?

**Comment by apoelstra** [comment]
* `Txid` (sha256d)
* `TxHash` (sha256d) (or should we call this `Wtxid`?)
* `BlockHash` (sha256d)
* `PubkeyHash` (hash160)
* `ScriptHash` (hash160)
* `P2wshProgram` (sha256) (not sha256d)
* `P2wpkhProgram` (hash160)
* `XpubIdentifier` (hash160) (is there a better name for this?)

Any others?

**Comment by dr-orlovsky** [comment]
I think Wtxid will be more readable; easier to understand the difference with Txid

Btw do we need to write Txid or TxId?

**Comment by dpc** [comment]
`XpubIdentifier`. `Identifier` == `Id`, so it should be consistently `Id`.

@dr-orlovsky Camel case so, `TxId`.

**Comment by dr-orlovsky** [comment]
So probably it has to be WTxId as well?

**Comment by apoelstra** [comment]
NAK on `TxId` that would snake-case as `tx_id` which I have never seen anywhere ever. "txid" is one word. "tx hash" is two words.

**Comment by dpc** [comment]
Seems like [some Rust project do use `tx_id`](https://github.com/search?utf8=%E2%9C%93&q=tx_id+language%3ARust&type=Code&ref=advsearch&l=Rust&l=). [I use it myself in rust-bitcoin-indexer](https://github.com/dpc/rust-bitcoin-indexer/search?q=tx_id&unscoped_q=tx_id) for what it's worth.

`txid` seems like a reasonable exception from the rules to save on typing `_` in an otherwise 4 letter word. And it's a judgment call if `txid` is an abbreviation/acronym  of "Transaction Identifier" or did it became a word on its own.

My main comment would be that "txhash" and "txid" are (at least casually) used interchangeably, (because there was no difference?). Also it seems to be [`ntxid`](https://docs.rs/bitcoin/0.20.0/bitcoin/blockdata/transaction/struct.Transaction.html#method.ntxid), so shouldn't type be named the same?

**Comment by apoelstra** [comment]
Oh, sure, we could also have an `Ntxid` type, but ntxids are unrelated to txids or wtxids.

"tx_id" is not used in any Bitcoin projects that I am aware of, and I have been involved with the project for nearly ten years now.

**Comment by dr-orlovsky** [comment]
Ok, so:

* `Txid` (`sha256d`) - agreed
* `Wtxid` (`sha256d`) - agreed
* `BlockHash` (`sha256d`) - why not `BlockId` by the same logic? (not proposing, just checking are we happy with naming consistency here)
* `PubkeyHash` (`hash160`) - seems fine (it is a hash, not an identifier definetelly), but why not `PubKey` (since pub_key is also used)
* `ScriptHash` (`hash160`) - nice name :)
* `P2wshProgram` (`sha256`) (not `sha256d`) - why not `WScriptHash` (as more consistent with `ScriptHash`)?
* `P2wpkhProgram` (`hash160`) - why not `P2WPHProg` or `WPubkeyHash` (as more consistent with PubkeyHash)?
* `XpubIdentifier` (`hash160`) - where is it used?

And can you pls clarify what `Ntxid` is?

**Comment by apoelstra** [comment]
"block id" isn't used in the Bitcoin community. (Though you are right that it's weird/inconsistent to use the term "block hash" for something which is actually the hash of the block header.)

Regarding `PubKey` vs `Pubkey`, I can never decide which one is more natural and probably the existing library is inconsistent in places. Maybe it's better to use `PublicKey` which at least has an obvious capitalization?

Sure, `WScriptHash` and `WPubkeyHash` sound fine to me.

`XpubIdentifier` is part of BIP32: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Key_identifiers

`Ntxid` refers to any of a pile of nonstantand transaction hashing conventions that were used pre-segwit to identify a transaction before it has been signed. I'd be fine with dropping this type and leaving the `ntxid` function alone, since it is only ever needed for legacy usecases.

**Comment by dr-orlovsky** [comment]
Thanks for the detailed clarifications. Actually it seems that there is some naming consistency in the resulting naming schema:
* if the name is composed from an abbreviated words (not full names), they are not camel-cased: so we have `Txid`, `Wtxid`, `XpubIdentifier` and `PubkeyHash` - but `BlockHash`, `ScriptHash`, `PublicKeyHash` etc

I am pro `PubleyHash` because of its brevity, which does not decrease readability.

**Comment by stevenroose** [comment]
> NAK on `TxId` that would snake-case as `tx_id` which I have never seen anywhere ever. "txid" is one word. "tx hash" is two words.

I'm pretty sure I've seen `txhash` been used as such in Core as well. 

I personally have doubts about the usefulness of some of the types, namely:

* `P2wshProgram` (`sha256`) (not `sha256d`) - why not `WScriptHash` (as more consistent with `ScriptHash`)?
* `P2wpkhProgram` (`hash160`) - why not `P2WPHProg` or `WPubkeyHash` (as more consistent with PubkeyHash)?
* `XpubIdentifier` (`hash160`) - where is it used?

Would we even be able to use them in rust-bitcoin?

**Comment by apoelstra** [comment]
Yes, I'm sure that you can find examples in Core RPC of all the two-word things being encoded as one word :). But that's an argument in favor of `Txhash`, not one against `Txid`.

I don't understand the rest of your post. It looks like it is supposed to be a quote of @dr-orlovsky ?

**Comment by apoelstra** [comment]
Offline conversation with @sipa suggests that we should do the reverse serialization for `Txid` Wtxid` and `BlockHash`, but no other types (not even the upstream `sha256d::Hash`). This matches current Core behaviour where only txids and blockhashes are reversed, not "all sha256d hashes that appear in RPC".

(This is something of a philosophical difference for most Bitcoin applications because there are no other sha256d hashes anywhere - but in Miniscript we do have non-txid non-blockhash sha256ds, and we care about having a non-reversed serialization.)

**Comment by dpc** [comment]
@apoelstra: Maybe just have separate types to express the difference? That guarantees clarity and avoids mistakes. And since there's already a macro to generate these it's not a big deal.

One could do `struct TxId<Serialization=Human>`, so `txid: TxId`defaults to work like you want. APIs can even take `Into<TxId>` etc. to seamlessly handle both variants (and an other hash-types).

**Comment by apoelstra** [comment]
The current API (reverse serialization in `Display` and serde, normal in `consensus_encode`) has worked perfectly fine for many years with no problems.

**Comment by dpc** [comment]
I don't remember the details, but I was definitely confused about some things with regards to serialization endianness in `rust-bitcoin`, and shenanigans that `Debug` was doing something else then `Display`, which was doing something else then `serde`, which wasn't well documented. :confused: 

It is never really a big deal, since it's easy to spot, but I don't think "perfectly" stands strong here. It works, sure. And I don't have a strong opinion if parametrizing is that useful, or adds just additional confusion.

**Comment by stevenroose** [comment]
@dpc you're right. But that's all fixed. Currently all displaying things do the same. FromStr, Display, Debug, serde.

The confusion is that Core uses reverse endiannes than the rest of the world. So we followed Core on all hashes that exist in Core but not with the hashes Core doesn't have.

**Comment by dr-orlovsky** [comment]
Have started the work on the topic, however found that `hash_newtype!` from bitcoin_hashes can't be used from outside of the lib – see more here: https://github.com/rust-bitcoin/bitcoin_hashes/pull/63

**Comment by dr-orlovsky** [comment]
WIP  can be tracked from here: https://github.com/pandoracore/rust-bitcoin/tree/hashtypes

**Comment by dr-orlovsky** [comment]
The work is done: https://github.com/rust-bitcoin/rust-bitcoin/pull/349

I am also thinking about adding these hash types:
* SigHash
* MerkleRoot
* MerkleBranch
* WitnessHash
* FilterHash

**Comment by elichai** [comment]
Done and Merged :)
