### ISSUE TITLE
Displaying hex

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2869]
We have a policy that types that are naturally displayed in hex should just implement `Display` by calling through to `fmt::LowerHex`. For discoverability, and also because of the potential for performance gains, all types that do so should also include an `to_hex` function.

Originally discussed in this thread: https://github.com/rust-bitcoin/rust-bitcoin/pull/2318#discussion_r1452731633

**Comment by shinghim** [comment]
From [#2318 (comment)](https://github.com/rust-bitcoin/rust-bitcoin/pull/2318#discussion_r1452825773):
> Alright, we are making progress! This is easy to put into policy - every type that prints hex in its `Display` implementation also gets an inherent method `to_hex` that calls through to `to_string`.

Does it make sense to add a trait for these types so users will know which types these are? Something like:

```rust
pub trait Hex {
    /// Converts the given value to its hex representation as a String  
    fn to_hex(&self) -> String; //Perhaps a default implementation that does the call through to to_string()?
}
```

**Comment by apoelstra** [comment]
No. Adding a trait would just reduce discoverability. I don't think anybody will be thinking "I need a hex-encodable object, let's see what they are". Instead they'll think "I have a specific object, I wonder if I can hex-encode it". And in the latter case, an inherent method is more discoverable because it'll be more prominent in the docs and won't require they import a trait.

Having said that, there is already such a trait -- `LowerHex` from stdlib -- which does this :).

**Comment by shinghim** [comment]
Makes sense, I'll start looking through the code to find where `to_hex()` can be added

**Comment by shinghim** [comment]
I have a bit of a Rust newbie question: we've implemented `core::fmt::Display`, but in order to get at `to_string()`, it requires the implementation of `std::fmt::Display`. I haven't had much luck finding a concise alternative for a no_std way to do this. Any suggestions on how we should do this, or some resources that I could take a look at that might help me with this?

**Comment by tcharding** [comment]
Its the same trait, I believe `std` re-exports the `core` stuff (I've not read the code though).

**Comment by Kixunil** [comment]
> I believe `std` re-exports the `core`

Yes, it does.

**Comment by shinghim** [comment]
Does the [Display function for Key](https://github.com/rust-bitcoin/rust-bitcoin/blob/db72ea8b3204966e68dfcc0784ed595ace68f9ed/bitcoin/src/psbt/raw.rs#L69-L73) need to be updated to display the format described in the [struct definition](https://github.com/rust-bitcoin/rust-bitcoin/blob/db72ea8b3204966e68dfcc0784ed595ace68f9ed/bitcoin/src/psbt/raw.rs#L27):
`<key> := <keylen> <keytype> <keydata>`? I think the current implementation makes sense for `to_string()`, but not sure if it makes sense to return it for `to_hex()` since we are calling through to `to_string()`

**Comment by Kixunil** [comment]
@shinghim  It should be pure hex returned from `to_hex` but not with the justification provided for but with the one provided for `Script`.
