### ISSUE TITLE
Remove/refactor `Weight::scale_by_witness_factor`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2963]
Why the hell do we have this function here? Weight already accounts for witness, so this is wrong. It should've taken `usize` and be called `from_non_discounted_size` (and also have `from_discounted_size`).

_Originally posted by @Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/pull/2957#discussion_r1664462205_

**Comment by apoelstra** [comment]
Was added in https://github.com/rust-bitcoin/rust-bitcoin/pull/2010. It wasn't commented on or noticed because the initial version of the PR implemented `Mul<Weight>` for `Weight` and several other things that shouldn't have existed. Since then @tcharding and I have discussed privately that we just shouldn't accept PRs that start out as such a cluster.

Agreed we should just drop this method.

The `from_non_discounted_size` method you want exists and is called `from_vb`.

**Comment by Kixunil** [comment]
Yeah, I had a vague idea of proposing "let's not add a bunch of random shit to our crates" but wasn't sure how a process to decide what is and what isn't "random shit" would work or how to express my idea reasonably politely. :)

But now I realized we should just have a hard rule to feature gate everything new behind `cfg(unstable)` unless there's some really good reason not to.

**Comment by apoelstra** [comment]
> But now I realized we should just have a hard rule to feature gate everything new behind `cfg(unstable)` unless there's some really good reason not to.

Innnteresting. Should be promoted to its own issue. Since many things are added specifically to help with miniscript, bdk, elements, esplora, etc., I suspect that all of those crates will just turn on this feature all the time, and then all their downstream users will have it on all the time, and then we won't accomplish a ton as far as breakage-reducing goes.

**Comment by Kixunil** [comment]
Providing a motivating example of how the feature wants to be used in an actual downstream crate (especially a popular like those you mentioned) sounds like a really good reason. But I want to see an example being the downstream crate depending on the patch (in a separate branch) so we can see it used in practice and I want a justification why alternative solutions don't work. This could help avoid things like what happened with the Taproot API which we though was good until people actually started using it.

**Comment by apoelstra** [comment]
Yeah, agreed, things like the Taproot API should definitely have been feature-gated initially because we knew it was too big to get right on the first shot, and it's kinda a PITA to test things downstream with unreleased `rust-bitcoin` feature branches. (Though @tcharding manages it fairly often.)

**Comment by yancyribbens** [comment]
Sorry this is my bad.  I was confused about the difference between Weight and usize.

**Comment by yancyribbens** [comment]
talk about learning the hard way on this one
