### ISSUE TITLE
Implement borsh feature to ser/de with borsh

### ISSUE THREAD

**Issue by kpp** [rust-bitcoin/rust-bitcoin#2983]
I have done some [benchmarks](https://github.com/chainwayxyz/citrea/issues/705) and it shows that borsh is the most optimal ser/de protocol for RISC0 interaction. Unfortunately no structs in this crate support borsh serialization scheme, because they require their own traits BorshSerialize/BorshDeserialize. 

Right now I have to convert `bitcoin::*` structs into internal representation which supports BorshSerialize/BorshDeserialize. Which is not optimal given your project is open source and open to modifications.

Not only this feature will help our product but all ZK-rollups on Bitcoin (assuming they will use RISC0 or other ZKVM will face same ser/de issues).

Would you please allow this feature in your project?

**Comment by Kixunil** [comment]
How is it different from consensus encoding? Why can't use use that? Could you submit a small example serializing e.g. `OutPoint`? The borsh crate isn't really documented that well.

**Comment by kpp** [comment]
> Why can't use use that?

Because in our situation where there are a lot of nested structs with bitcoin::* structs we want to pass to RISC0. Something like this:

```
#[derive(BorshDeserialize, BorshSerialize)]
struct A {
    b: B,
}

#[derive(BorshDeserialize, BorshSerialize)]
struct B {
    tx: bitcoin::Transaction
}
```

> Could you submit a small example serializing e.g. OutPoint?

```rust
use borsh::{BorshDeserialize, BorshSerialize};

/// A reference to a transaction output.
#[derive(BorshDeserialize, BorshSerialize)]
pub struct OutPoint {
    /// The referenced transaction's txid.
    pub txid: Txid,
    /// The index of the referenced output in its transaction's vout.
    pub vout: u32,
}

/// A bitcoin transaction hash/transaction ID.
#[derive(BorshDeserialize, BorshSerialize)]
pub struct Txid([u8; 32]);

fn main() {
    let point = OutPoint {
        txid: Txid([42; 32]),
        vout: 3,
    };
    let bytes = borsh::to_vec(&point).unwrap();
    dbg!(hex::encode(&bytes));
}

```

Output: `2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a03000000`.

**Comment by Kixunil** [comment]
Sounds like what you really want is a derive for consensus serialization?

Note that there's a big refactoring planned here and we will have some macros. I can't promise proc maros yet but I wouldn't be opposed to anyone contributing them.

**Comment by kpp** [comment]
Would you please elaborate? You don't mind if I add `#[derive(Borsh...)]`?

**Comment by Kixunil** [comment]
Basically your serialization is the same as our consensus serialization so maybe you could `#[derive(bitcoin::ConsensusSerialize)] Though if you're already working with borsh it's a weird thing to do. Doesn't Borsh derive macro have the equivalent of `serde`'s `with` attribute?

**Comment by apoelstra** [comment]
We already have consensus encoding implemented for all of our types, so just providing a proc-macro for it wouldn't change anything.

I think the actual issue here is that the OP wants some borsh-specific trait on rust-bitcoin types, and rust's coherence rules require that he petition one (or both) projects to support this, since he can't implement 3rd party traits on 3rd party types.

@kpp we definitely are not going to add a new dep, even an optional one, for a 3rd-party serialization trait. We definitely won't add one that uses proc-macros. serde has caused us enough pain. In the past we tried adding `schemars` traits to our hashes, with similar reasoning, and that was also a nightmare. A few of us have petitioned for the `Arbitrary` trait and that one maybe we'll accept...but the problem, in general, is with rust's coherency rules.

I *think* what you need to do is create a wrapper type that holds an arbitrary `T: bitcoin::consensus::Encodable` and then implement `BorchSerialize` on that, passing through to our encodable trait.

Then your data structures unfortunately will need to hold the wrapper type (or do some borsch equivalent to `#[serde(with = "...")]`) rather than the bare rust-bitcoin type.

**Comment by kpp** [comment]
> Doesn't Borsh derive macro have the equivalent of

They have their own https://docs.rs/borsh/latest/borsh/derive.BorshSerialize.html proc macro that is not compatible with serde unfortunately. They support only a limited number of attributes like `bound` and `skip`.



> Also, isn't RISC0 `no_std`?

They are no_std with an experimental support of std.

**Comment by Kixunil** [comment]
> is not compatible with serde

That's not what I meant. I was asking if it has an attribute that does effectively the same thing. And yes, it does - it's in the docs you linked: https://docs.rs/borsh/latest/borsh/derive.BorshSerialize.html#5-borshserialize_with---field-level-attribute

So you clearly need to use that. You may release it as a separate crate for others too (`bitcoin-consensus-encoding-as-borsh`? :D).
