### ISSUE TITLE
`Address::from_str`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3044]
An obviously incorrect bech32 address string causes our parsing code to return a `base58` error, it would be nicer if it indicated so sort of bech32 error type.

Found while playing with #3034 

(Note to implementor, do not expose `bech32` in the public API, see #2381 for context.)

**Comment by tcharding** [comment]
## Example

This code

```rust
fn main() {
    let _ = Address::from_str("bc1qzvkjn4q3nszqxrv3nraga2r822xjty3ykvkuw")
        .unwrap()
        .assume_checked();
}
```

gives this build error

```bash
called `Result::unwrap()` on an `Err` value: Base58(IncorrectChecksum(IncorrectChecksumError { incorrect: 2182836954, expected: 2347289762 }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Compilation exited abnormally with code 101 at Mon Jul 15 06:46:36
```

**Comment by apoelstra** [comment]
How can we distinguish an "obviously incorrect bech32 string" from an "obviously incorrect base58 string"?

**Comment by tcharding** [comment]
One option would be to just default to saying bech32 since segwit addresses are more "typical". Another is to not say what the error is in the variant but use a non-specific term "parse" "checksum". Another option would be to check if it starts with 'bc1' and use segwit.

Basically it looks to me like the code is written with the happy path in mind not with the error paths in mind (and the user).

Its not urgent but parsing an address is a pretty user focused thing, rigt?

**Comment by apoelstra** [comment]
Sure, we can change to defaulting to bech32. But that wouldn't make the code "have the error paths in mind". It would just have the same logic updated for a different era.

Switching on prefixes is not too bad an idea, though it would lead to bad error messages if a user provided a bech32 address with the wrong HRP. On the other hand, prefixes are the only way we can reliable distinguish the encodings. (If any prefix were allowed it would be easy to construct a string which was both valid base58 and valid bech32(m)).

I would suggest:

* In all cases we should try to parse as both kinds of address; but we should be smarter about which one we try first and which one we return an error for.
* To decide first-parse and error-return, we should first check if it matches a known prefix; if not, then check how many characters are in each charset and take the majority; and if this is somehow a tie, default to `bech32`.

**Comment by Kixunil** [comment]
I think it makes more sense to match on prefixes:

* `1`, or `3` - parse as `base58`
* `bc1`, `bcrt1`... - parse as `bech32`
* anything else: unrecognized address format

**Comment by apoelstra** [comment]
This will make it impossible to decode addresses from any custom networks.

This is currently the case for legacy addresses, which is fine (we more-or-less required this in #2232 which codifies that there are only two kinds of legacy addresses).

But it seems like an unnecessary restriction to reject valid bech32 addresses because we don't recognize the HRP. Especially because we then turn around and claim to the user that it's "unchecked" and that they need to call `require_network` (which currently takes a `Network` but should maybe take an `AsRef<Params>` or something ... or we should just add a separate `require_hrp` method).

**Comment by storopoli** [comment]
Additionally, for bech32/bech32m address, we could also indicate, if possible, where in the string the error might be found.

Ref: https://github.com/bitcoin/bips/blob/af8f9e470bc5e1b908c988f344d0bbaef9eef39d/bip-0173.mediawiki?plain=1#L179C33-L182C9

> funds to be lost irrecoverably. Because of this, implementations SHOULD
> NOT implement correction beyond potentially suggesting to the user where
> in the string an error might be found, without suggesting the correction
> to make.

**Comment by apoelstra** [comment]
How is it worse? Currently we accept addresses with any HRP and the only problem is that if they're invalid then you'll get a base58 error rather than a bech32 one. At the very least we should invert this because in 2024 bech32(m) is the default.

This isn't about shitcoins. It's about allowing people to define test networks with domain-separated addresses, something the HRP was expressly designed to do, and something which we can easily support with our existing data structures. I have seen you complain elsewhere that people keep reusing the testnet prefixes for signet, regtest, etc., but now you are suggesting that they *must* do so or else they will lose rust-bitcoin support ... and I really don't know for what benefit.

**Comment by Kixunil** [comment]
> How is it worse?

It complicates our API and address handling significantly.

> It's about allowing people to define test networks with domain-separated addresses

Why is it even useful? Losing test coins is not a big deal (if it is, by definition, it's not a test network but a shitcoin).

> HRP was expressly designed to do

I believe it was a mistake.

> have seen you complain elsewhere that people keep reusing the testnet prefixes for signet, regtest, etc

It's more about horrible inconsistency. "main" and "test" should've been the address kinds from the beginning. But now that we already have other networks, then reusing makes APIs confusing. This gets even worse with things like LN reusing the address scheme and inheriting this design. So today we have the worst of both worlds: neither can you uniquely determine the network from the address nor can you avoid the complexity of dealing with having multiple networks.

> now you are suggesting that they _must_ do so or else they will lose rust-bitcoin support

It's more like I don't like to make the API super-complicated (or inefficient) for a niche use case that wouldn't even exist if we didn't make the original mistake in the first place.

Side note: I think that regtest is the only test network that should exist. It's better at everything except "ease of configuration" which could've been solved by just having some kind of connection string URI (kinda like `lndconnect`).

**Comment by apoelstra** [comment]
>It complicates our API and address handling significantly.

There is zero change to the API. At worst it necessitates adding a `require_hrp` method, but even this we can avoid because it's easy for people to do it manually.

I appreciate the philosophical commentary, both about past and future design decisions of specs that rust-bitcoin has no influence on, but I'm really struggling to understand what your complaint here is. It seems you want to reject parsing addresses that we currently accept and which our API currently has no problem distinguishing from "real" main/test addresses. I don't see what simplifications this gets us, except maybe to the internal logic of `Address::from_str`.

Do you have a problem with other uses of `Params` or `Into<Network>`? Should we lock those down as well?

**Comment by Kixunil** [comment]
> There is zero change to the API.

Oh, yes you're right. It does affect our error handling though. With whitelisted HRPs the handling would be dead simple - check the prefix, error if unknown. But without it we just have to do guessing about how to handle the mistakes in addresses. And since this is a UI thing, we need to do it damn well.

So here's an alternative suggestion: do it as I suggested above but for non-standard HRPs provide `from_str_with_hrp` method which will know upfront what to expect. The niche use cases can still call into it. Sadly this will interact badly with `serde` but it's hard to solve anyway.

Or dig up my proposal to have a `bitcoin-common-network` crate which sets the network as a global, so `serde` can work and people can get rid of all this weirdness.

**Comment by apoelstra** [comment]
If somebody typoes in the HRP then in your solution they will get a "unknown address format" error. With mine they will correctly get a checksum error, and we could even identify where the error was.

There is no solution other than "guessing" because it is possible for an address with a low number of typos (even 0) to parse with the correct format.

Adding `from_str_with_hrp` would increase the API surface while providing the bare minimum of extra functionality -- allowing people to support a single extra test network and needing to re-parse if they want to support multiples.

**Comment by Kixunil** [comment]
> a "unknown address format" error. With mine they will correctly get a checksum error, and we could even identify where the error was.

Maybe "unknown prefix" is a better name. Then we have 100% reliability in identifying where the error is. (at the beginning!)

> because it is possible for an address with a low number of typos (even 0) to parse with the correct format.

I've read this phrase maybe 10 times and still don't understand it. 0 typos obviously means the address will parse, what's your point?

> if they want to support multiples.

That's highly unusual but maybe we should instead have `from_str_lax` that does the funny guessing and allows any HRP.

**Comment by apoelstra** [comment]
I meant to say "parse with the incorrect format". That is, a bech32 address will parse as base 58 and vice-versa.

>Maybe "unknown prefix" is a better name. Then we have 100% reliability in identifying where the error is. (at the beginning!)

Oh, nice, I like this.

> That's highly unusual but maybe we should instead have `from_str_lax` that does the funny guessing and allows any HRP.

Ok, sure, I can live with this. We don't even need to implement it with any urgency. But I don't want to preclude it.

**Comment by Kixunil** [comment]
> That is, a bech32 address will parse as base 58 and vice-versa.

:open_mouth: Didn't they ban zero-length HRPs or HRPs beginning with 1 or 3? If not that's quite messed up and if someone actually uses it it's even more messed up. I would definitely assume nobody is that stupid and just assume leading 1 or 3 is base58.

> We don't even need to implement it with any urgency. But I don't want to preclude it.

Great, I can get behind this. My thinking is to make non-niche use cases first-class but I don't mind supporting niche use cases if it doesn't negatively affect the main ones.

**Comment by apoelstra** [comment]
Empty HRPs are banned but you can still start them with 1s or 3s if you want. I guess it sorta would have made sense to ban 1 and 3 since those are so widely used, but in practice this doesn't matter except for people writing parsers because it's statistically impossible for an organically-produced base58 address to be misparsed as bech32.

Instead BIP-173 just defines a "valid segwit address" as one which starts with `bc` or `tb` and this guarantees collision freeness. (Which yes, supports your position since `Address` should be parsing valid segwit addresses, not arbitrary segwit-address-shaped strings.)

**Comment by jamillambert** [comment]
I have not been involved in the discussion until now so apologies if I have misunderstood any of it.

I have changed `Address::from_str`  to have the following logic:

1. Try to decode as bech32
2. If it fails keep the error saved and then try to decode as base58
3. If it also fails keep the error saved and check if the string has a prefix that fits the bech32 prefix requirements
4. If the string has a bech32 prefix return the bech32 error from above
5. Else return the base58 error from above

**Comment by apoelstra** [comment]
@jamillambert no, I think we have a simpler strategy:

* If something starts with a prefix from a known address variant, parse as that variant.
* Otherwise return some sort of "unknown address format" error.

**Comment by jamillambert** [comment]
Ok, but that would then change the current behaviour to only allow the decoding of an address with a one of hard coded address variants we have chosen.  The method in the PR I did keeps the current behaviour of allowing any HRP as long as it is a valid address.  The only change is it chooses which error to return based on the encoding type.

**Comment by apoelstra** [comment]
Yes, it will change the behavior. See the long conversation between me and @Kixunil about this above.

**Comment by jamillambert** [comment]
I have changed the PR so that the prefix is checked first and then the string is either attempted to be decoded as bech32 or base58.  If the prefix is not known an `UnknownHrpError` is returned with the first 2 characters of the string.
