### ISSUE TITLE
Consider adding `hash_reader` functions

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3050]
As suggested here: https://github.com/rust-bitcoin/rust-bitcoin/issues/2881#issuecomment-2216294407

Consider adding 

```rust
#[cfg(feature = "std")]
pub fn hash_reader(reader: &mut impl std::io::Read) -> Self;
```

functions to the various hash types. 

Hint: Use `git grep 'fn hash_bytes\('` to find which files to patch.

**Comment by apoelstra** [comment]
We probably just want to take the reader by value.

**Comment by Kixunil** [comment]
It's a weird case. Rust guidelines recommend by value but someone here (I think it was @RCasatta ?) found out that taking by reference causes less code bloat because in practice people don't distinguish between `R` and `&mut R` so they just pass whatever they have doubling the codegen. By taking `&mut R` people are forced to take a reference instead of passing `R` and there's a clippy lint for `&mut &mut R` (though it's for something else, not sure if it applies here too).

**Comment by apoelstra** [comment]
I think this applies only for recursive calls. If `hash_reader` were in turn calling other things then I think you'd be correct. But it'll be directly calling read functions on the `reader`. So I don't see how taking `&mut R` could result in less codegen. But it could certainly result in the user having to type extra `&mut`s.

**Comment by Kixunil** [comment]
Well, strictly speaking, I think that post-monomorphization optimizations should deal with it and recognize it a s the same code and merge it. But the thing in Rust is multiple expansions of generics slow down compile time considerably so it would be still nice to avoid it.

**Comment by apoelstra** [comment]
Agreed. But here I think there is literally no difference in compile time, so we ought to go with the "recommended" one, which is also more general and easier to use.

**Comment by Kixunil** [comment]
The compile time accumulates. We do a tiny inefficiency here, then another there and before you know it we've added seconds of compile time to the code.

Of course, ideally Rust would have some special pre-mono optimization to avoid all this. So maybe it does make sense to just have nicer API and complain at rustc to improve their stuff.

**Comment by Kixunil** [comment]
Oh, actually, it has a simple solution: if they add `fn as_deref(&mut self) -> &mut impl Read { self }` to the `Read` trait and override it for `&mut T` to return `(*self).as_deref()` we could just call `as_deref` and pass it to the real implementation (like we do with `as_ref` etc).

**Comment by apoelstra** [comment]
"Literally no difference" does not accumulate to a finite difference even if we do a countable infinity of them.

**Comment by Kixunil** [comment]
OK, I though it was a hyperbole. I believe there is actual difference. From what I've read a lot of the issues with compile times are due to Rust generating a lot of LLVM IR which LLVM has to process and even if it throws a lot of it away at the end resulting in small enough binary, it still has to process all that. There's an effort to reduce produced LLVM IR for this reason.

The way generic works is they are just fancy macros - at the end their generics are expanded and thus for each type you instantiate them with you get a separate version of code. This code has to be processed and even tiny difference like taking a reference will prevent it from being trivially merged. Thus the change in compile time is non-zero.

**Comment by apoelstra** [comment]
I understand all this. But there is still no difference between taking a `&mut R` and taking an `R`. There is still exactly one copy of the code produced for every type of reader passed to the function.

**Comment by Kixunil** [comment]
The difference is if you have two parts of the code using the same base reader type (e.g. `BufReader<File>`) then you are more likely to pass in different types (`BufReader<File>` vs `&mut BufReader<File>`) triggering two expansions. If the API forces `&mut T` then you don't accidentally pass non-reference `T` leading to only one expansion (`&mut &mut T` should be caught by clippy).

**Comment by apoelstra** [comment]
> `&mut &mut T` should be caught by clippy).

Ah, yeah, this is a good point.

I still think that because this is totally in the user's control (even though the language is pretty unhelpful) that we should do the more general and idiomatic thing. But I wouldn't be too put out by having a `&mut` if you feel strongly about it.

**Comment by Kixunil** [comment]
It was the reason why we changed a bunch of things like this already. I'm not sure if it's important but if we did it already it likely is to someone.

**Comment by apoelstra** [comment]
We definitely did this in rust-miniscript, but there the situation was further complicated by all the calls being recursive. I'm not aware of non-recursive functions that take generic readers where we did this.

**Comment by Kixunil** [comment]
OK, that makes sense.
