### ISSUE TITLE
`siphash::HashEngine::new` and `siphash::HashEngine::default` look very wrong

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3084]
I tried to find reference for when using zero keys is reasonable and couldn't find any. I believe using zeroes strongly indicates wrong usage and these methods should've never been implemented. I suspect they are a result of the macro and `HashEngine` trait not supporting non-default hashers and instead of dropping the requirement the constructors got hard-coded keys.

**Comment by apoelstra** [comment]
I believe you're correct. We should just drop both methods (though we may need to mess with the `HashEngine` trait to do so). None of the standard test vectors use zeros. These functions date to https://github.com/rust-bitcoin/bitcoin_hashes/pull/46 written by Steven who "didn't know anything about the internals" and reviewed by me who blindly asked for some test vectors then "didn't verify them". The zero-key thing was not mentioned. I suspect I noticed it and assumed that it could be useful as a fast hasher in non-secure contexts. But obviously "fast and insecure" should not be a default mode for anything in this library (and it's not even faster than siphash with real keys; it's just faster than the other unkeyed hashes in this library).

**Comment by nyonson** [comment]
I'd be happy to take a crack at this since I think it would help me with the ChaCha20Poly1305 PR, but also aware there is a lot of work going on in hashes right now and don't want to cause unnecessary churn.

**Comment by Kixunil** [comment]
@nyonson I think you can, unless @tcharding has a PR ready or something. I think we need to split out everything but those impls from internal macro to another one, call that from the original and then just call the new one from siphash and poly.

**Comment by tcharding** [comment]
Go for it @nyonson, happy to have the help.

**Comment by nyonson** [comment]
@tcharding I have been poking around on how to shift things and believe I see @Kixunil's point now. Would like to run a few things past you guys to make sure I have a good understanding of the problem.

* The hashes interface assumes an *unkeyed* hash function is being used as the engine. This allows for the nice `bytes in => hash out` function APIs for callers where the engine is fired up with default values under the hood.
* This assumption is codified with the `HashEngine` type requiring the `Default` trait. It is leveraged in the new `GeneralHash` type as well as the `hash_type` and `hash_trait_impls` macros.
* SipHash, and Poly1305, are *keyed* hash functions, requiring secret data to create an instance of an engine. This is at odds with the nice `bytes in => hash out` functions which I believe are a high priority for the hashes re-write.

Feels like this new requirement justifies splitting off a whole knew "keyed" version of the existing `HashEngine` and hash macros. The `Hash` type itself appears to be agnostic to keyed or unkeyed engines. Since the hash macros are internal, it might get a little ugly, but probably pretty easy to create "keyed" versions which drop any `Default`-y things. And while it is easy enough to copy/paste a `KeyedHashEngine` type which drops the `Default` req of `HashEngine`, there might be a little naming exercise with another shared trait there since it is public.

I'm hacking on this, but figured out throw out what I am thinking since I would like to avoid any major conflicts in the public API if possible.

**Comment by apoelstra** [comment]
Concept ACK from me. As for avoiding conflicts .. maybe you are aware of #2881 and related issues? We are doing a lot of changes to the hashes API.

My suggestion would be that you create a whole new `KeyedHashEngine` trait, and a new set of macros (if you think you even need them) and avoid touching the existing traits and macros. Then depending what you come up with we can have a discussion ... possibly we don't even need the trait, and it's fine for the two keyed hash engines to just have inherent methods.

**Comment by Kixunil** [comment]
I don't think we have to have `KeyedHashEngine`. Just drop the `Default` bound from `HashEngine` and then write `HashEngine + Default` where needed. (Probably only `GeneralHash::engine`, `GeneralHash::hash` and `GeneralHash::hash_byte_chunks`.)

The trait could be beneficial for implementing the `hash` method though:

```rust
pub trait KeyedHashEngine: HashEngine {
    type Key;

    fn new(key: Self::Key) -> Self;
}

pub trait GeneralHash {
    type Engine: HashEngine;

    fn hash(input: &[u8]) -> Self where Self::Engine: Default { /* ... */ }

    fn hash_with_key(input: &[u8], key: <Self::Engine as KeyedHashEngine>::Key) -> Self where Self::HashEngine: KeyedHashEngine { /* ... */ }
}
```

Also for consideration: `impl<T: HashEngine + Default> KeyedHashEngine for T { type Key = (); /* ... */ }`

**Comment by nyonson** [comment]
Ah, pushing Default up like that makes a lot of sense, especially if cool with messing with the public API now. I'll explore that.

**Comment by tcharding** [comment]
This is done, might have been in #3222
