### ISSUE TITLE
Add Zeroize to Secret Types

### ISSUE THREAD

**Issue by palladionIT** [rust-bitcoin/rust-bitcoin#3091]
I am working on a downstream project where we would like to have `Zeroize` on all secret material types. I noticed that Rust Bitcoin does not use `Zeroize` at all and was wondering if there is a specific reason for that? I don't mind creating a PR but some things might break a few things. For example, upstream `secp256k1` does not support zeroization for all types, but provides [non_secure_erase](https://docs.rs/secp256k1/latest/secp256k1/struct.SecretKey.html#method.non_secure_erase) that could be called on a `Zeroize` implementation.
If I understand correctly some changes that are necessary would conflict with `Copy` and thus would change the public API. This could be solved with a feature flag but before digging deeper I wanted to know if this feature is even wanted. I have checked the issues and documenation but could not find any reference on why `Zeroize` has not been added so far. Any pointers or comments on the idea are greatly appreciated.

**Comment by Kixunil** [comment]
Honestly, `Zeroize` is a placebo and that's why we don't really support it. You have no guarantee it actually works because the compiler will happily `memcpy` your data anyway regardless of `Copy` (the trait has dumb name, it should've been `!Drop`). The problem is fundamentally unsolvable, at least today. 

> If I understand correctly some changes that are necessary would conflict with `Copy`

Possibly but that's not even main issue. There's no point providing false sense of security. Also note that zeroizing itself is kinda dubious and pretty much only a harm reduction in single-threaded programs written in memory-unsafe languages. Since Rust is memory-safe the benefits are marginal and there is a real cost.

> This could be solved with a feature flag

It cannot because it'd have to be exclusive and such is not supported by `cargo` (and even if it was it'd create a problem that some crates would work with it and some not).

> I have checked the issues and documenation but could not find any reference on why `Zeroize` has not been added so far. Any pointers or comments on the idea are greatly appreciated.

You've been searching the wrong repository. https://github.com/rust-bitcoin/rust-secp256k1/issues/553

I'm closing this issue **without transferring** to help future searches and we can move discussion over there if you're still convinced that you can solve the problem and it's worth solving.

**Comment by benma** [comment]
>  You have no guarantee it actually works because the compiler will happily memcpy your data anyway 

As far as I understand, if zeroize is implemented/derived on Box/Vec, it should be safe - moving the object copies the heap pointer not the value. In the BitBox02 firmware we try to abide by this - heap-allocate, write sensitive data directly there (no stack).

It would be great if rust-bitcoin would do this too. I am currently trying to use `bip32::Xpriv`, and its `new_master()` function already leaves copy of the master seed, and the result is an unboxed `Xpriv` type, so it's not clear how to move it to a Box without leaving copies.

Could this be reconsidered? Even if it's not 100% failsafe, it seems better solve most of the cases than none.

**Comment by apoelstra** [comment]
rust-secp currently does not require or expect any allocator to be present.

**Comment by benma** [comment]
Would it need to? Thinking of Xpriv, there could be a function `Xpriv::set_master(&mut self, seed: &[u8])` instead, and the library user could init a `let xprv: Box<zeroize::Zeroizing<Xpriv>> = Box::new(zeroiize::Zeroizing::new(Default::default()))` and call `set_master()` on it, and so on.

**Comment by benma** [comment]
I just revisited https://github.com/rust-bitcoin/rust-secp256k1/issues/553#issuecomment-2246844927, whose details I had forgotten about, and which makes more sense than my above proposal. Apologies for the noise.

**Comment by apoelstra** [comment]
>Default::default()

`Xpriv` does not implement `Default` and it's hard for me to think of what a "default" key should be. So at the very least, you would need to use a dummy key here and the ergonomics would be even worse.

**Comment by Kixunil** [comment]
@apoelstra maybe we should lock this issue with a comment to redirect it into secp repo? Nothing personal against anyone, just managerial. :)

**Comment by apoelstra** [comment]
No, it's not clear to me that help from upstream would be necessary (or sufficient even) to implement `Zeroize`. I think the crux of this issue is about Rust, not C.

**Comment by Kixunil** [comment]
Yeah, I agree. But C has the same problem, they just pretend they don't. ;)
