### ISSUE TITLE
Newtype for PubkeyHash?

### ISSUE THREAD

**Issue by thomaseizinger** [rust-bitcoin/rust-bitcoin#320]
Given a [recent addition](https://github.com/rust-bitcoin/bitcoin_hashes/pull/59) to `bitcoin_hashes`, it is now fairly easy to create newtypes around the existing hash-types.

What are everyone's thoughts about adding a newtype `PubkeyHash` that can be created from a `PublicKey`?

**Comment by apoelstra** [comment]
I like it.

**Comment by stevenroose** [comment]
Me too. Should we go all the way? `TxHash`, `BlockHash`, `ScriptHash`? And use them wherever relevant. F.e. in `address::Payload`.
If we also implement `From<bitcoin_hashes::sha256d::Hash>` for those types, it wouldn't be that invasive either. And perhaps change method arguments to take `H: Into<PubkeyHash>` so that one can put in a `PublicKey` and a `sha256d::Hash` as well.

**Comment by apoelstra** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/issues/284 has a big list of hashes we can newtype

**Comment by dr-orlovsky** [comment]
Do we need to close this issue as a duplicate?

**Comment by thomaseizinger** [comment]
> Do we need to close this issue as a duplicate?

When I created it, the old issue was only about TxId :)
Happy to close this one though! Thanks for working on this @dr-orlovsky !
