### ISSUE TITLE
The monorepo is hostile towards backports

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3212]
During recent `io` backports I've realized we have a problem with our monorepo: it's really hard to backport things if we have different branches for individual crates. So unless we want to make a single branch for every major version of `bitcoin` (I think doing it for a bottom crate makes most sense) we might want to look into git submodules.

**Comment by tcharding** [comment]
Yeah I've thought this before too, I have no opinion/idea on the suggested solution though.

**Comment by apoelstra** [comment]
I really really hate submodules. If we want to do this we can use git subtrees, which at least use normal git structures instead of a weird flat-file based thing that requires magic invocations to manipulate (and leaves your repo in a totally broken state if you don't).

Having said that, I can live with the current messy situation where we have a gazillion branches that fork off of master at weird points and are labeled with specific subcrates.

**Comment by apoelstra** [comment]
In either case though, the implication is that the other crates live in their own repos and then this one is just an "aggregator". So we would want to split up issue tracking etc. Possibly we would even want to disable the issue tracker here? And do we want to PR directly to this repo or just have a system of scripts which updates the subtrees and runs CI?

If we are doing that do we even need the monorepo, or can we just have some synthetic repo off to the side whose job it is to integration-test rust-bitcoin with `master` of all the other repos.

**Comment by Kixunil** [comment]
> I can live with the current messy situation where we have a gazillion branches that fork off of master at weird points and are labeled with specific subcrates.

That is what actually doesn't work here. If you need to backport things to `io` and `hashes` and both have their separate branches then there's no way to depend on both from `bitcoin`.

**Comment by Kixunil** [comment]
> So we would want to split up issue tracking etc.

No idea, I was just pointing out the problem. I'm too tired to figure it out rn.

**Comment by apoelstra** [comment]
> That is what actually doesn't work here. If you need to backport things to `io` and `hashes` and both have their separate branches then there's no way to depend on both from `bitcoin`.

I don't think we ever need `bitcoin` to depend *on the backported fixes*. If we did, then presumably we'd have noticed the bugs when they were current and fixed them in master, rather than noticing much later and needing to backport. And when we backport, we have copies of the fixed code on `master`, so `bitcoin` can depend on that.

> No idea, I was just pointing out the problem. I'm too tired to figure it out rn.

Fair.

**Comment by Kixunil** [comment]
> presumably we'd have noticed the bugs

We don't in case of API holes.

> And when we backport, we have copies of the fixed code on `master`, so `bitcoin` can depend on that.

If we remove patches then it's harder to demonstrate that a filled API hole is fixed - one needs to make two PRs. That may be acceptable.

**Comment by tcharding** [comment]
I'm going to close this. Yes its suboptimal but its currently workable and no obviously better solution exists (to my knowledge). Also @apoelstra does most of the releases and I do most of the backports.
