### ISSUE TITLE
All extension traits need to be sealed

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3231]
They are currently unsealed which allows users to implement them even though it's pretty obviously misguided. If we keep them unsealed then formally adding any function to them is a breaking change which is silly.

**Comment by apoelstra** [comment]
I **think** if they are blanket-impled then users can't implement them? e.g. if we have `ReadExt` impled for all `T: Read` then nobody except stdlib will be able to implement `ReadExt` since theoretically stdlib could add their own blanket impl that'd cover the user's type?

If it's possible to do, I wouldn't say it's "obviously misguided". But it's not what the extension traits are meant for, and I agree we should seal them to give ourselves more API freedom at the expense of preventing it.

**Comment by Kixunil** [comment]
LOL, I mean all type extension traits that we're adding lately. Trait extensions are indeed fine.

**Comment by apoelstra** [comment]
Oh, yes, definitely agreed! And ok, yes, in that case it'd be "obviously misguided" for users to implement them :).

**Comment by tcharding** [comment]
> If we keep them unsealed then formally adding any function to them is a breaking change which is silly.

This doesn't matter because `bitcoin 1.0.0` is years away.

I rekon this issue is going too far, if someone is stupid enough to implement these traits then perhaps they are beyond help. I think we should close this.
