### ISSUE TITLE
Bike shed and find uniform format for `deprecated` `note` field

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3306]
Can we have a uniform format for 

`#[deprecated(since = "TBD", note = "format of this field is under discussion")]`

Currently we have:

- Capitalized with full stop
- Capitalized without full stop
- Lowercase with full stop
- Lowercase without full stop
- Lowercase without full stop and multiple "sentences"

I don't personally care what it is but just that its uniform so I don't have to think every time I write one.

**Comment by Kixunil** [comment]
We should check if there's any Rust-wide standard first.

**Comment by jirijakes** [comment]
> We should check if there's any Rust-wide standard first.

In Rust's standard library:

- everything starts with lowercase
- no period at the end
- two most common patterns:
  - “replaced by `abc`”
  - “use `abc` instead”

So perhaps “use `abc` instead“ would be suitable, given that this is the wording mostly used in rust-bitcoin. The fix would be only to make it lowercase and remove periods.

<details>
<summary><code>rg -trust -I --trim "deprecated.*note"</code></summary>
<pre><code>
#[deprecated(since = "1.3.0", note = "renamed to join", suggestion = "join")]
#[deprecated(since = "1.6.0", note = "replaced by `std::thread::sleep`")]
#[deprecated(since = "1.6.0", note = "replaced by `std::thread::park_timeout`")]
#[deprecated(since = "1.16.0", note = "this option can only be set before the socket is bound")]
#[deprecated(since = "1.16.0", note = "this option can only be set before the socket is bound")]
#[deprecated(since = "1.8.0", note = "other methods of this trait are now preferred")]
#[deprecated(since = "1.6.0", note = "replaced by `std::sync::Condvar::wait_timeout`")]
#[deprecated(note = "moved to `std::ops::Bound`", since = "1.26.0")]
#[deprecated(since = "1.26.0", note = "use inherent methods instead")]
#[deprecated(since = "1.8.0", note = "other methods of this trait are now preferred")]
#[deprecated(since = "1.37.0", note = "should be unsafe, use `pre_exec` instead")]
#[deprecated(note = "use `align_of` instead", since = "1.2.0", suggestion = "align_of")]
#[deprecated(note = "use `align_of_val` instead", since = "1.2.0", suggestion = "align_of_val")]
#[deprecated(since = "1.39.0", note = "use `mem::MaybeUninit` instead")]
#[deprecated(note = "no longer an intrinsic - use `ptr::drop_in_place` directly", since = "1.52.0")]
#[deprecated(since = "1.42.0", note = "use the Display impl or to_string()")]
#[deprecated(since = "1.81.0", note = "this never returns anything useful")]
#[deprecated(since = "1.59.0", note = "use `IntoIterator::into_iter` instead")]
#[deprecated(since = "TBD", note = "replaced by the `MIN` associated constant on this type")]
#[deprecated(since = "TBD", note = "replaced by the `MAX` associated constant on this type")]
#[deprecated(since = "TBD", note = "replaced by the `RADIX` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `DIGITS` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `EPSILON` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `MIN` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `MIN_POSITIVE` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `MAX` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `MIN_EXP` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `MAX_EXP` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `MIN_10_EXP` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `MAX_10_EXP` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `NAN` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `INFINITY` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `NEG_INFINITY` associated constant on `f32`")]
#[deprecated(since = "TBD", note = "replaced by the `RADIX` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `DIGITS` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `EPSILON` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `MIN` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `MIN_POSITIVE` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `MAX` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `MIN_EXP` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `MAX_EXP` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `MIN_10_EXP` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `MAX_10_EXP` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `NAN` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `INFINITY` associated constant on `f64`")]
#[deprecated(since = "TBD", note = "replaced by the `NEG_INFINITY` associated constant on `f64`")]
#[deprecated(since = "1.0.0", note = "renamed to is_sign_positive")]
#[deprecated(since = "1.0.0", note = "renamed to is_sign_negative")]
#[deprecated(since = "TBD", note = "replaced by the `MIN` associated constant on this type")]
#[deprecated(since = "TBD", note = "replaced by the `MAX` associated constant on this type")]
#[deprecated(since = "1.39.0", note = "use the `?` operator instead")]
#[deprecated(since = "1.52.0", note = "rustc-serialize is deprecated and no longer supported")]
#[deprecated(since = "1.52.0", note = "rustc-serialize is deprecated and no longer supported")]
#[deprecated(since = "TBD", note = "replaced by the `MIN` associated constant on this type")]
#[deprecated(since = "TBD", note = "replaced by the `MAX` associated constant on this type")]
#[deprecated(since = "1.51.0", note = "use hint::spin_loop instead")]
#[deprecated(since = "1.4.0", note = "use lines()/Lines instead now")]
#[deprecated(since = "1.29.0", note = "use `get_unchecked(begin..end)` instead")]
#[deprecated(since = "1.29.0", note = "use `get_unchecked_mut(begin..end)` instead")]
#[deprecated(since = "1.4.0", note = "use lines() instead now", suggestion = "lines")]
#[deprecated(since = "1.33.0", note = "superseded by `trim_start`", suggestion = "trim_start")]
#[deprecated(since = "1.33.0", note = "superseded by `trim_end`", suggestion = "trim_end")]
#[deprecated(since = "1.13.0", note = "use `std::hash::DefaultHasher` instead")]
#[deprecated(since = "1.13.0", note = "use `std::hash::DefaultHasher` instead")]
#[deprecated(since = "1.13.0", note = "use `std::hash::DefaultHasher` instead")]
#[deprecated(since = "1.13.0", note = "use `std::hash::DefaultHasher` instead")]
#[deprecated(since = "1.13.0", note = "use `std::hash::DefaultHasher` instead")]
#[deprecated(since = "1.13.0", note = "use `std::hash::DefaultHasher` instead")]
#[deprecated(since = "1.13.0", note = "use `std::hash::DefaultHasher` instead")]
</code></pre>
</details>

**Comment by storopoli** [comment]
I like @jirijakes suggestions and I prefer the imperative "use `abc` instead" in place of the passive "replaced by `abc`".

**Comment by apoelstra** [comment]
Can we also make a habit of sticking a PR # or issue # in there somewhere?

(For people making new PRs -- it's mildly annoying to do, but you can just look at the existing PRs/issues list to find the most recent number, and add +1 to it to guess your PR number before pushing. This will almost always work because it's rare to have two new PRs within minutes of each other, and easy to fix after the fact.)

**Comment by Kixunil** [comment]
@apoelstra we could also replace it during release when `TBD` is being replace. I think it should be scriptable.

Anyway, ACK using `std`'s imperative style.

**Comment by apoelstra** [comment]
@Kixunil oo, interesting.

In principle it is scriptable but I think it'd require having an index of commit IDs to PRs. (If we had such a thing, I suppose we could also sanity-check our changelog to insist that every change that added a deprecation showed up there somewhere..).

I've got such an index in my [label-pr](https://github.com/apoelstra/rsgit) tool which has served me well but it's not currently designed to be used within scripts, and also it's extremely slow on massive repos.

**Comment by Kixunil** [comment]
Github GUI can tell you in which PR a commit was, I'd be surprised if it's not accessible from API. I think we could also get away with scanning which merge contains adding of deprecation - we only need to scan since last release and there shouldn't be so many merges for it to take too long during release.

**Comment by tcharding** [comment]
Nice work @jirijakes!

**Comment by tcharding** [comment]
Push #2137 forwards as part of this.

**Comment by jamillambert** [comment]
#3475 changes all the existing deprecated note fields to the “use `abc` instead” format.  

I was going to add the PR number to the note too using git blame, until I came across one which is "automated rustfmt nightly".  If there are only a few like that I can find the original PR with git log.

Is the following format ok? 

"use `abc` instead (see PR #xxxx)"

**Comment by tcharding** [comment]
I don't think we should add PR numbers to the code base.

**Comment by jamillambert** [comment]
#3475 made all of the exiting deprecated notes uniform and #3476 adds a section to `CONTRIBUTING.md` stating the agreed format of 
```#[deprecated(since = "TBD", note = "use `alternative_method()` instead")]```

Suggest to close this Issue.
