### ISSUE TITLE
Should we provide constructors for types with public fields

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3340]
As an example, the `OutPoint::new` constructor is pointless because both fields are public.

`OutPoint{ txid, vout }` is arguably better than `OutPoint::new(txid, vout)` because in the first one the order does not matter, it is also more terse.

Should we provide constructors for types with all public fields?

**Comment by Kixunil** [comment]
You're not asking: "Should we also hide public fields of POD types like `OutPoint`?", which makes this non 1.0 issue because adding constructors later is non-breaking.

And to answer your question, I don't see a point besides making them usable in combinators like `map` but there one likely wants something like `From<(Txid, u32)> + From<(u32, Txid)>` and perhaps currying. I'd prefer sticking to idiomatic Rust and leave this for extension traits which functional fans can easily write.

**Comment by apoelstra** [comment]
Agreed with @Kixunil. I think we should deprecate our existing constructors for such types (at least where they have generic names like `new`) in favor of using the structuring notation.

This does break theoretic uses of `map` but `map` is already only usable in pretty narrow circumstances as Kix says because of Rust's lack of currying support, inability to turn `(x,y)` into `x,y`, inability to turn `x` into `&x` or vice-versa, etc etc. And we certainly do not want to pollute our  API with a massive number of explicit constructors to patch over this language deficiency.

**Comment by Kixunil** [comment]
There's one exception to this: if at least one field has an obvious default, so that the number of inputs gets reduced. But I don't remember where in the library we have anything like this except for uses of `PhantomData` which we don't expose anyway. Just pointing it out in case someone finds it.

Also for single-field types Rust already generates a suitable constructor for `map`.

**Comment by tcharding** [comment]
Closing as resolved, `OutPoint::new`  to be left behind as deprecated during move of `OutPoint` to `primitives`, same for any other types we come across.
