### ISSUE TITLE
Broken feature handling in `internals::impl_to_hex_from_lower_hex` macro

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3348]
I've just realized the macro is broken.

If crate `a` depends on `internals` and has `alloc` off and then crate `b` depends on `internals` turning on the `alloc` feature crate `a` has suddenly injected code referencing a non-existing `alloc` crate and thus `a` breaks.

There's another small but ugly issue that the `alloc` requirement is not properly documented in the calling crate.

Because of the second issue, out of two possible fixes - using `$crate::alloc` and just putting the `cfg` on the `to_hex` method and declaring the assumption of the macro that the calling crate has an `alloc` feature that also activates the `alloc` crate, I prefer the latter.

_Originally posted by @Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/pull/3295#discussion_r1753843584_

**Comment by apoelstra** [comment]
As always, putting my vote in for just replacing these macros with script-generated code that lives in the crate they're instantiated in. Would be far easier to reason about.

A partial step toward that would be to stop putting feature-gates on macros themselves, only *inside* the macros. And yes, documenting which feature-gates are assumed to exist and what they do.

**Comment by Kixunil** [comment]
> just replacing these macros with script-generated code that lives in the crate they're instantiated in

We need to share that code (hence `internals`) and once we do, script is not going to help (and having build script is annoying anyway because it makes audits raise eyebrows).

**Comment by apoelstra** [comment]
It wouldn't be a build script. It would be a CI script that verified that checked-in code matched the output of the codegen script. And this would help with reasoning about feature gates because there would be no "containing crate" that owned the macros and whose own features would interact confusingly with the features of the crate that actually used the generated code.

But I think, if we had a soft rule that we won't put cfg gates on macros, that would solve this issue without the downsides of extra tooling.

**Comment by Kixunil** [comment]
ACK the soft rule. I suspect we'll find an exception to it soon enough that will help us clarify it better.

**Comment by tcharding** [comment]
+1 the soft rule but amusingly it being soft probably means it doesn't need another +1 :)
