### ISSUE TITLE
`TxIn` should impl `Default`

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#339]
and probably so should a bunch of other types

**Comment by dpc** [comment]
What is a default `TxIn`? Doesn't seem to me like it has a good default value. Is there any practical reason to have it?

**Comment by apoelstra** [comment]
Every field of `TxIn` has a default value. Presumably the default `TxIn` would be the one that's populated by the default values of every one of its fields.

And the reason is so you can initialize a `TxIn` piece by piece.

**Comment by dpc** [comment]
I'm unsure if this is a good idea. I have an intuitive feeling that `Default` should be to generate meaningful, useful, default values. Just because parts have default, doesn't necessarily mean the the sum of default parts should be a default whole. 

Initializing piece by piece can be achieved by something like `fn new_empty() -> Self` or even simply `new`. In contrast, the `Default` trait has a meaning - it comes into play when people write higher-level abstractions generic over having a meaningful, neutral and useful default value. Typically when skipping initializing a certain data is totally fine and useful. So my worry is that giving a meaningless default value to a any type is exposing user to a risk of not noticing, that they should probably have to handle that explicitly.

**Comment by apoelstra** [comment]
I specifically need an empty `TxIn` to give to [miniscript::Descriptor::satisfy](https://docs.rs/miniscript/0.11.0/miniscript/descriptor/enum.Descriptor.html#method.satisfy) so that I can extract the witness from it.

**Comment by elichai** [comment]
@dpc I think you're over thinking it.
A default value is a nice thing as long as it's possible(i.e. with Box and references it's not).
step by step initialization, might not be the most idiomatic thing in rust (i.e in rust people generally prefer to initialize the fields and then construct a struct from all the fields) but sometimes it's still very useful.

Anyway, there are some RFCs to allow safe step by step initialization, until then I think using `Default` is what most of the ecosystem does.

**Comment by dpc** [comment]
Just to make sure it was noticed: `fn new_empty() -> Self` can return a new `struct` with empty fields, so `impl Default` is not necessary for "step by step initialization". `Default` is purely for generalizing over stuff that has a meaningful, neutral default value.

I agree that this is not a big deal one way or another, and I might be overthinking it here, though. :)

> Anyway, there are some RFCs to allow safe step by step initialization, until then I think using Default is what most of the ecosystem does.

I am confused. I don't really see a point here. In this case, there's nothing preventing step by step initialization, be that `let mut txin = Default::default()` or `let mut txin =  TxIn::new_empty()`. And normally builders like https://docs.rs/crate/derive_builder  are doing a great job at providing flexible and convenient step by step initialization, and it is trivial for the compiler to get rid of any overhead.
