### ISSUE TITLE
`PushBytes::read_scriptint` is a bit unwieldy

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3479]
While upgrading `mininscript` to track master branch I found that the `PushBytes::read_scriptint` function is unwieldy.

Should we add this back in:

```rust
/// Decodes an integer in script(minimal CScriptNum) format.
///
/// See [`PushBytes::read_scriptint`] for documentation.
pub fn read_scriptint(v: &[u8]) -> Result<i64, Error> {
    let push = <&PushBytes>::try_from(v).map_err(|_| Error::NumericOverflow)?;
    push.read_scriptint()
}
```

**Comment by tcharding** [comment]
ref: https://github.com/rust-bitcoin/rust-miniscript/pull/755

**Comment by tcharding** [comment]
And the PRs that touched `read_scriptint`:

- https://github.com/rust-bitcoin/rust-bitcoin/issues/1547
- https://github.com/rust-bitcoin/rust-bitcoin/pull/2535

**Comment by apoelstra** [comment]
It looks like there are two places where we call this method in `miniscript`. One is to convert a slice from `script::Instruction::PushBytes` which for some reason holds a `&[u8]` instead of a `PushBytes`. Shouldn't it hold a `PushBytes` instead?

The other is in `witness_to_scriptsig` in `src/util.rs` which is, frankly, a bizarre method and I think it's fine if the code there is a bit unwieldy.

**Comment by tcharding** [comment]
> It looks like there are two places where we call this method in `miniscript`. One is to convert a slice from `script::Instruction::PushBytes` which for some reason holds a `&[u8]` instead of a `PushBytes`. Shouldn't it hold a `PushBytes` instead?

This is a `bitcoin::script::Instruction::PushBytes(PushBytes)` so this call site is ok.

> The other is in `witness_to_scriptsig` in `src/util.rs` which is, frankly, a bizarre method and I think it's fine if the code there is a bit unwieldy.

This is the call site that caused me to raise the issue, so you've cleared it up nicely. Thanks
