### ISSUE TITLE
Is `primitives::opcodes` ok to stabalize

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3538]
Since we move `opcodes` to `primitives` we have gotten _much_ more conservative on what we move over. Is the current `primitives::opcodes` code ok to stabalize or do we want to use extension traits and move logic back to `bitcoin`?

**Comment by tcharding** [comment]
Note #2989 is impossible with the current code arrangement.

**Comment by apoelstra** [comment]
Similarly the `OP_PUSHBYTES_<N>` display output is pretty weird, but again, people have been using it forever (I routinely see this format in slides about stuff far removed from rust-bitcoin, so that's a lesson there about making decisions in the early days of a project..) and they'd be annoyed if we changed it out from under them.

And again, it's super easy for somebody to just make their own `Opcode` type with better formatting and classification for whatever they're doing, and convert to our type when needed.
