### ISSUE TITLE
FromStr for hex? or making a FromHex type?

### ISSUE THREAD

**Issue by elichai** [rust-bitcoin/rust-bitcoin#355]
Currently we use the `FromStr` https://doc.rust-lang.org/std/str/trait.FromStr.html to convert from hex to a type.
I argue that this should be a `FromHex` trait. as `FromStr` usually is a bit more literal and doesn't concern itself with the radix. (i.e. for integers it uses "regular" decimals)

**Comment by stevenroose** [comment]
Depends. Which types are you talking about? In many cases the hex strings are the "standardized" string representations of the types. So `FromStr` makes sense in that case for me.
If something expects a `sha256d::Hash`, I should be able to just pass in `"000000000000000000039805d44e1d9f42442e592eb361c4741716543aac1a7c".parse()?` because that's a SHA-256d hash like you'd see them all over the place.

`FromStr` is the reverse of `Display`, right? Or at least it's supposed to be (because `ToString` is auto-implemented using `Display`). So I'm in favor of probably 99% of the cases where `FromStr::from_str(x.to_string())? == x`.

**Comment by stevenroose** [comment]
Also, we have `FromHex` in `bitcoin_hashes::hex` and it's implemented for all `bitcoin_hashes` type.

For one, I'm unhappy with `hex` being part of `bitcoin_hashes`. I'd much rather just use the `hex` crate or something that is broader than our repos.

**Comment by apoelstra** [comment]
we tried that with base64 and got burned. I don't understand why hex parsing is not in the stdlib of a systems language, but given that it's not, better to NIH it.

Sure, it could be its own crate I guess.

**Comment by elichai** [comment]
I think mostly because the current `LowerHex` / `UpperHex` etc. kinda suck (see https://github.com/rust-lang/rust/pull/67021 )

**Comment by dongcarl** [comment]
Is the consensus here just to write our own hex crate?

**Comment by stevenroose** [comment]
Or specify the issues with the `hex` crate and try fix them? What's our issue with them? I use it in almost all my projects and never had an issue. They have a good MSRV. They don't have traits FromHex and ToHex I think, but if that's the problem we can easily add them. 

And when it comes to the reverse ordering for bitcoin_hashes I think that should be something bitcoin_hashes specific. We can f.e. have a marker trait `ReversedHex` and then `impl FromHex for T where T: Hash + ReversedHex` or something.

**Comment by elichai** [comment]
I personally prefer https://github.com/debris/rustc-hex which is basically https://github.com/rust-lang/rust/blob/master/src/libserialize/hex.rs

**Comment by apoelstra** [comment]
The issue with the hex crate is simply that it's an extra dep for nearly-trivial functionality.

**Comment by apoelstra** [comment]
Closing this, out of date.
