### ISSUE TITLE
Re-design `Block` API

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3571]
The current `Block` API is lacking and we would like to move good clean API's over to `primitives` [0]. As such we would like to re-think the API.

From comment here: https://github.com/rust-bitcoin/rust-bitcoin/pull/3549#issuecomment-2450609746

> I see that you kept the check_merkle_root and check_witness_commitment methods back in the extension trait. This is 
reasonable because it's poor API design to have "sanity check" methods on a type. Instead we should enforce that the type cannot be constructed or modified in a way that violates its invariants.
>
> In this case we have two invariants:
>
> For all blocks, the merkle root of txdata should match the merkle root embedded in header
For all segwit blocks, i.e. blocks that contain witness-bearing transactions, the witness commitment embedded in the last output of the coinbase transaction must be consistent with the txdata. IOW the first item of txdata must be consistent with the remaining items.
>
> Furthermore the name txdata sucks.
>
> All this to say that I don't think we can move this type over as a POD type. I think we need to close it and rethink the API.

Raising issue for discussion.

[0] "good clean", yes yes I know that is not an unambiguous non-subjective term.

**Comment by tcharding** [comment]
A couple of questions please because I'm having trouble understanding the usecase for this API, hence having trouble thinking about the design.

- Isn't checking the merkle root an expensive operation? Aren't applications that want to parse the whole chain going to be upset if we start hashing instead of just parsing?
- What application is expecting to parse blocks that might be invalid, where would such blocks come from?
- Apart from parsing is there any other use case for the `Block` type (are people writing mining software with`rust-bitcoin`)? Does this need to be considered when designing the API?

Hope I'm not being braind-dead, you know what they say there is no such thing as stupid questions only stupid people.

**Comment by apoelstra** [comment]
These are all good questions:

> * Isn't checking the merkle root an expensive operation? Aren't applications that want to parse the whole chain going to be upset if we start hashing instead of just parsing?

Yeah. So, ideally we would make this value lazy (only computed on access and maybe even cached using mutexes or something), but unfortunately it's part of the `Header` type which we really do want to be a POD type (it has no internal invariants and is designed to be cheap).

> * What application is expecting to parse blocks that might be invalid, where would such blocks come from?

It has happened multiple times in Bitcoin's history that miners have produced invalid blocks, apparently by accident. But it would also happen as part of a miner-assisted double-spend attack. Certainly the incentives would be higher if rust-bitcoin users weren't validating blocks!

In this case, if we don't validate the transaction merkle root, performing an attack is trivial: you take any valid block header from the chain, grab any set of transactions you want, and call them a "block".

> * Apart from parsing is there any other use case for the `Block` type (are people writing mining software with`rust-bitcoin`)? Does this need to be considered when designing the API?

Yep -- I have talked to multiple people writing mining software based on rust-bitcoin. So our use cases are:

* People parsing the blockchain and willing to trust its validity (e.g. because it comes from a trusted node) and who would like to go as fast as possible
* People parsing the blockchain and *not* willing to trust its validity (e.g. full nodes or light wallets) -- these **need** to make sure the merkle root is correct because otherwise a malicious data provider can lie about the presence/absense of transactions
* People creating blocks (who need their block headers to be correct or they will wasting mining power)

**Comment by apoelstra** [comment]
I am tempted to split `Block` into two types, like `Address`. A `Checked` one that you get by validating all the hashes, and an `Unchecked` one that you can directly construct, modify the transaction set of, etc.

For `Unchecked` we can have accessors `unchecked_header`, `unchecked_header_mut`, `unchecked_transactions`, `unchecked_transactions_mut`, etc., and a method to convert the unchecked block to a checked one, which would provide shorter accessors.

The checked one could also maintain a cache of TXIDs (and maybe even Merkle proofs), since it needs to compute these as part of the Merkle root check.

**Comment by tcharding** [comment]
Interesting, let me chew on this for a bit. Thanks.

**Comment by tcharding** [comment]
A few observations:

- In general `Decodable`, as it should, only errors for decoding errors. It does not do validity checks (there may be some abuses of this).
- `Decodable` stays in `bitcoin`
- The merkle root code is likely to stay in `bitcoin` not move to `primitives` (`TxMerkleNode::calculate_root` and `Block::compute_merkle_root`)
- Deserializing a `Block` is only currently supported by way of `Decodable` (implies `encode::deserialize`) 
- We want to get `primitives` out the door with POD types.

Which leads me to claim:

- We should move `Block` as is with public fields over to `primitives`
- We should step back and take a look at our deserialization code, (examples are not meant to start discussion just to highlight that we have a whole bunch of issues that are all related to deserialization)
   -  Add associated error type to `Decodable` (we are using `String` in the `encode::Error`) 
   - Consider adding `_unchecked` versions and defaulting to do validity checks
   - Consider adding inherent functions everywhere (this ties in with all things that are typically hex should have `FromStr` parse hex, e.g. `Transaction`  is still missing `from_str`, `from_hex`, and a simple way to deserialize it.
   - WTF are we going to do about `Encodable` / `Decodable` (push decoding, separate crate, `io::Error` etc)

**Comment by apoelstra** [comment]
It sounds like we want to copy what we did with `Address`, where we have an "unchecked" version that can be decoded, and which can be converted to a checked one either by checking or by calling an `assume_` method.

**Comment by tcharding** [comment]
Ok, I finally got over my PTSD from the fallout of introducing `Address<NetworkChecked>` and added `Block<Checked>` in https://github.com/rust-bitcoin/rust-bitcoin/pull/3582. Draft but ready for concept review please.

**Comment by tcharding** [comment]
Done.
