### ISSUE TITLE
Is rust-bitcoin compatible with Bitcoin SV?

### ISSUE THREAD

**Issue by SatoKentaNayoro** [rust-bitcoin/rust-bitcoin#3624]
Hello,

I would like to know if the rust-bitcoin library is compatible with Bitcoin SV. Specifically, can it be used for building applications or wallets that interact with the Bitcoin SV network? Are there any known limitations or considerations?

Thank you!

**Comment by apoelstra** [comment]
If you just want to sign SV transactions, you can pretend they're Bitcoin transactions and then use https://docs.rs/bitcoin/latest/bitcoin/sighash/struct.SighashCache.html#method.legacy_signature_hash with a `sighash_type` value that's mangled in some way. (The API in 0.32 takes a `u32` to support doing this, but future versions of the library will not, because there is no reason in Bitcoin to exceed the range of a `u8`.)

At least, that's how bcash worked.

This should be sufficient for you to move your SV coins to an exchange so that you can sell them for Bitcoin.

If you're trying to do anything else, then yeah, you're SOL :). This library does not (and will not) support any of the new opcodes, probably does not support huge blocks, does not support any weird futzing with difficulty algorithms, etc etc.

**Comment by yancyribbens** [comment]
> with explicit backdoors added as a part of consensus to allow certain parties to steal your coins

Was that Satoshi's Vision? :thinking:
