### ISSUE TITLE
Move TX_IN_BASE_WEIGHT to TxIn BASE_WEIGHT

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#3661]
Why not move `TX_IN_BASE_WEIGHT` to TxIn `BASE_WEIGHT`?  Wouldn't that follow the pattern of `OutPoint::SIZE` and other `SIZE` consts?

**Comment by tcharding** [comment]
The current push is to get `units`, `hashes`, `io` (and `hex` and `ordered`) to 1.0 so we can 1.0 `primitives`. In order to achieve this we are trying to make the API on all these crates as small as possible so we have more confidence to do the stable releases. Things can be added back in later but we cannot change or remove things. `rust-bitcoin` is getting into a less-than-optimal state to prioritise the other crates.

**Comment by yancyribbens** [comment]
Ok, well if we can add it to 1.0 that works if you need to prioritize other things.
