### ISSUE TITLE
`Amount` serde does not roundtrip `Amount::MAX`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3688]
Deserializing `Amount::MAX` currently fails with

```bash
---- amount::serde::tests::can_serde_as_btc stdout ----
thread 'amount::serde::tests::can_serde_as_btc' panicked at units/src/amount/serde.rs:423:61:
failed to deser: Error("amount out of range: the amount is greater than 18446744073709551615", line: 1, column: 29)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I would expect this test to pass:

```rust
    #[test]
    fn can_serde_as_btc() {
        #[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
        pub struct HasAmount {
            #[serde(with = "crate::amount::serde::as_btc")]
            pub amount: Amount,
        }

        let orig = HasAmount {
            amount: Amount::MAX,
        };

        let json = serde_json::to_string(&orig).expect("failed to ser");
        let rinsed: HasAmount = serde_json::from_str(&json).expect("failed to deser");
        assert_eq!(rinsed, orig)
    }
```

**Comment by jamillambert** [comment]
The issue is converting a `u64` to an `f64`.  `u64::MAX` can't be stored as an `f64` without a loss of precision.  
If you edit the test code to use the maximum integer that can be stored as an f64:
```rust
        let orig = HasAmount {
            amount: Amount::from_sat(9_007_199_254_740_992),
        };
```
it passes, and then fails if you increase the number by 1.

We could change `Amount::MAX` from `u64::MAX` to `9_007_199_254_740_992`?

**Comment by jamillambert** [comment]
The issue is converting a `u64` to an `f64`.  `u64::MAX` cannot be stored as a `f64` without a loss of precision.  It gets rounded to `18_446_744_073_709_552_000` which is larger than `u64::MAX`.

If you change the test code to 
```rust
        let orig = HasAmount {
            amount: Amount::from_sat(9_007_199_254_740_992),
        };
```
it passes.  And then if you increase the number by 1 it fails because the f64 gets rounded to an even number due to the lack of the units bit from the loss in precision.

We could change `Amount::MAX` to be `9_007_199_254_740_992` instead of `u64::MAX` since this is the largest integer that can be used safely without any loss in precision.

**Comment by apoelstra** [comment]
If we're gonna do that then I'm tempted to just use `MAX_MONEY` as `Amount::MAX`.

Many people think that this is why `MAX_MONEY` is what it is -- to fit in the 52-bit mantissa of a f64.

**Comment by yancyribbens** [comment]
I think `Amount::MAX` should be `MAX_MONEY` instead of `u64::MAX`.

**Comment by apoelstra** [comment]
Yeah, I'm coming around to this view as well.

**Comment by tcharding** [comment]
Please see #3691

**Comment by tcharding** [comment]
Now we use `MAX_MONEY` for `MAX` this issue is resolved.
