### ISSUE TITLE
What does "part of the public API" mean in Rust anyway?

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3785]
Recent discussion in #3767 and #3784 raised the opinion that something marked by the `doc(hidden)` attribute is not part of the public API.

While trying to understand this I read rustlang docs:

> We choose to hide it with #[doc(hidden)] because users can never have a PrivateError in their code so this impl would never be relevant to them.

ref: https://rust-lang.github.io/api-guidelines/documentation.html#rustdoc-does-not-show-unhelpful-implementation-details-c-hidden

Which seems to support that opinion. Why did we go to the trouble of removing all the `From<FooError>` impls then when we could have slapped `doc(hidden)` on them? It seems to me like taking something out of the docs is a pretty soft way of saying its not in the public API given that some user can very much still depend on it and very much still get their code broken by a minor update.

Why bother having private scoped functions if we can just slap the attribute on them instead? Or am I just being autistic?

**Comment by dpc** [comment]
What is and what isn't public is a bit of a gray area.

`#[doc(hidden)]` only hides a symbol from the documentation and is a bandaid: It's still technically public, and can be used downstream if someone knows it's there. In certain cases it's just the best thing that can be done - e.g. one can have a public API macro, that under the hood needs to call a method that is not supposed to be public-stable.

`From<X>` are "visible" by doing `.into()` or `From::from(x)`, so `#[doc(hidden)]` workaround doesn't work for them really.

**Comment by junderw** [comment]
doc(hidden) is an explicit

"do not rely on this. by relying on this you agree to have minor and patch version updates break your code."

For instance, serde has the `__private` module which is pub and anyone can use it... but it's only meant for use in serde macros.

If serde changes around something in the `__private` module and your code breaks because you relied on it, that's on you.

That is my 2 cents.

**Comment by apoelstra** [comment]
> Why did we go to the trouble of removing all the `From<FooError>` impls then when we could have slapped `doc(hidden)` on them

This is a great question, and we used to have `doc(hidden)` on all these. Kix argued that this was unidiomatic and I shouldn't do it, and at the time I didn't have a principled argument for or against; I'd just cargo-culted it from some other project because it made the docs look ugly to have them in there.

**But** IMO specifically with `From<Error>` impls, I think that these are morally "part of the API" even if we hide them from the docs. The reason is that nobody uses these impls after seeing them in the docs. They use them by typing `?` and if it "works" they move on with their lives.

>Why bother having private scoped functions if we can just slap the attribute on them instead? Or am I just being autistic?

This is why in the other thread I said we shouldn't lean on this too heavily. For structs that need to be explicitly constructed or functions/macros that need to be explicitly called, I think it's fine to put `doc(hidden)` on them and call it a day. But if the user is able to obtain an instance of a type "without realizing it" because it's the return type of a function whose exact type we don't think about, or something like that, then we need to be careful.

**Comment by apoelstra** [comment]
Maybe as a matter of policy we should say that we're only allowed to put `doc(hidden)` on

* types whose entire lifecycle occurs inside of a macro
* traits which are only implemented by such types (regardless of whether they are sealed)
* standalone functions
* macros

And we can add things to this set as we encounter them.

And we should have the same rules for things that are exposed from `internals`, and things which we leave in the public docs but mark `__private` or otherwise mark as unstable.

**Comment by tcharding** [comment]
Good related post from another issue: https://github.com/rust-bitcoin/rust-bitcoin/pull/3767#issuecomment-2550300741

**Comment by tcharding** [comment]
ugh - sealing, this is totally pointless if it is accepted that `doc(hidden)` means "don't use this" - and it fits in with "one would have to discover by reading docs and/or code". Sometimes I wish I was a C programmer again.

**Comment by apoelstra** [comment]
Sealing is not "totally pointless". Sealing prevents downstream users from implementing a trait on their own types (thus allowing us to add methods). Hiding it means that they can't use it to bound things, and we can't expose anything that uses it to bound things.

**Comment by tcharding** [comment]
\me crawls back into his hole.

**Comment by Kixunil** [comment]
> Why did we go to the trouble of removing all the `From<FooError>` impls then when we could have slapped `doc(hidden)` on them?

Because it's way too easy to type `?` without thinking. Contrast that with `_some_long_name_saying_do_not_use`.

> Kix argued that this was unidiomatic and I shouldn't do it

No, I argued it doesn't work well because of the `?` operator.

> They use them by typing `?` and if it "works" they move on with their lives. And we can't delete these impls and claim that the code breakage was because users were "using `?` when they shouldn't have".

Exactly

> * standalone functions

Only if called from a public stable macro.
