### ISSUE TITLE
Solve PublicKey ambiguity

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#382]
Two distinct structs share the same name: `bitcoin_hashes::PublicKey` and `bitcoin::util::key::PublicKey`. The first one is re-exported by the bitcoin crate, creating confusion and necessity to use `as` for importing when both of them are used in the same mod. 

I propose to rename one of the structs to avoid the confusion. I have already done it in my local branch, renaming `bitcoin::util::key::PublicKey` into `BitcoinPubkey`, so I can PR this version if you will accept this idea.

**Comment by stevenroose** [comment]
I think you're talking about `secp256k1::PublicKey`, right?

We're aware of the confusion. I was personally against the new `bitcoin::PublicKey` and `bitcoin::PrivateKey` types because they don't really add any value over the original `secp256k1` types.

However, now that they exist, I think most of us are aware of both types and when to use which. Basically you shouldn't ever have to use the `secp256k1` types anymore.

**Comment by dr-orlovsky** [comment]
Yes, sure, I meant `secp256k1::PublicKey`. Yes, I'm aware about the difference, however PublicKey/EC cryprography can be used outside of the scope of Bitcoin transactions, where scep256k1 will be usable again — we have this situation in the RGB project (off-chain client-validated data), that's why I had actually made this proposal.

**Comment by apoelstra** [comment]
`secp256k1::PublicKey` does not have any notion of compressedness. `bitcoin::PublicKey` does. There is no way to equate these types.

I do not want to rename `bitcoin::PublicKey` to `BitcoinPublicKey`. You save two characters in exchange for making it less clear what crate the type came from.

**Comment by thomaseizinger** [comment]
What was the reason for adding this notation of compressedness through `bitcoin::PublicKey` instead changing `secp256k1::PublicKey`?

**Comment by dr-orlovsky** [comment]
> I do not want to rename bitcoin::PublicKey to BitcoinPublicKey. You save two characters in exchange for making it less clear what crate the type came from.

Just to notice, if you have to use both version (which is the case in some of my code, you end up not with `bitcoin:PublicKey` and  `secp256k1::PublicKey` but rather

```rust
use bitcoin::secp256k1::PublicKey;
use bitcoin::util::key::PublicKey as BitcoinPubkey;
```

or 

```rust
use bitcoin::secp256k1::PublicKey as SecpPubkey;
use bitcoin::PublicKey;
```

i.e. there is no simple way of having `bitcoin:PublicKey` and `secp256k1::PublicKey` without  importing the whole `secp256k1::*`; so one is forced to stick with  `as`-renaming for at least one of them during the import.

**Comment by thomaseizinger** [comment]
> i.e. there is no simple way of having bitcoin:PublicKey and secp256k1::PublicKey without importing the whole secp256k1::*; so one is forced to stick with as-renaming for at least one of them during the import.

The names are "standard Rust", at least according to [RFC356](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#avoid-redundant-prefixes-[rfc-356]).
Given that RFC, I've found it helpful to import the next high-level namespace to disambiguate instead of using `as`:

```rust
use bitcoin::secp256k1;
```

and then in your code do:

```rust
let bitcoin_key = bitcoin::PublicKey::new(...)
let secp_key = secp256k1::PublicKey::new(...)
```

Personally, I try to avoid renaming imports with `as`. If your IDE supports searching for types and you use `as` a lot, it forces you to always check the imports first before you can do a type-search (otherwise you get 0 results and wonder where the type is coming from).

Another approach (which we ended up going for), is to simply define your own type `PublickKey` type that wraps whichever one is more suited for your case and provide conversion methods.

Still, I'd be curious for why there was a need to actually introduce a new type @apoelstra ?
Did you just not want to make a breaking change to `secp256k1::PublicKey` or is there another reason why the feature of compressedness does not fit into `secp256k1::PublicKey`?

**Comment by stevenroose** [comment]
I do agree that the compressedness flag shouldn't be in `secp256k1::PublicKey`, though. Au contraire, I actually think it shouldn't be in `bitcoin::PublicKey` either :P 

It's not a property of the key itself. A public key is a point on the curve. So a pubkey type should have the information to represent that point on the curve. The compressedness flag only indicates *which format is used to serialize the key into bytes*. So it's a property of the serialization rather than the key itself.

However, in Bitcoin, the mode of serialization is relevant for determining which address is generated. So in Bitcoin, the compressedness flag is also a property of *how the key is (intended to be) used*. I believe that's why it's included in the `bitcoin::PublicKey` type. While still not semantically correct to have it there, it avoids some annoyances and prevents some easy mistakes.

Like a `WIF` "Bitcoin private key" also contains a flag to indicate that addresses for that private key should be generated with a compressed or uncompressed public key.

Andrew and probably others, value the ability to make the following series of conversions:
```
WIF string -> PrivateKey -> PublicKey -> Address
```

If `PrivateKey` and `PublicKey` don't keep track of this compressedness flag, it would have to be brought along when calculating an `Address`.

--------
About a year ago [I did a PR](https://github.com/rust-bitcoin/rust-bitcoin/pull/221) that removed the `bitcoin::*Key` types and just used the `secp256k1::*Key` types. I don't recall the exact implementation, but basically it'd have a `util::wif::WIF` type that is strictly used for WIF serialization and would just be a tuple of `secp256k1::SecretKey` and the compressed flag. WIF is not a very common format anymore anyway since BIP39 seeds became the standard. Also uncompressed public keys are very much discouraged and only still used in legacy systems. That aside, the PR was closed and I got over it (clearly) :sweat_smile:

**Comment by dr-orlovsky** [comment]
Also, this will all change once again with Taproot and Schnorr pubkey serialization. In general, I find concept of Bitcoin addresses highly legacy... May be it worth to take it all together and leave for upper layers on top of `rust-bitcoin` (such as wallets)? So we can not bother with anything that is related for the intentions of using public key in some way at the user level.

**Comment by elichai** [comment]
Well for users PublicKey==Bitcoin Address.
An Address is somewhat a template specifying a `scriptPubKey`.

anyhow. secp doesn't care about scriptPubKey and/or Bitcoin Address.
Bitcoin does. at least for users, I do think we should provide Bech32/Base58/WIF formats.
I wouldn't care if you rename `bitcoin::PublicKey` to `Address`. but other than naming I see no reason for anything to change

**Comment by apoelstra** [comment]
A public key is not an address. A public key is a component of a scriptpubkey associated to a CHECKSIG or CHECKMULTISIG opcode and there is no way to uniquely and computably map an address to one.

**Comment by dr-orlovsky** [comment]
So what is our final take on this issue? Close it down?

**Comment by thomaseizinger** [comment]
I am not expert on ECDSA math but the [this link](https://crypto.stackexchange.com/questions/8914/ecdsa-compressed-public-key-point-back-to-uncompressed-public-key-point) suggests that one can actually convert between the compressed and uncompressed form losslessly?

Why are we keeping that state around then if we can just convert to the other form at any point? I guess we would need the `secp256k1::Context` to do the math but we need that one anyway in many places.

For what it is worth, as a downstream user of this library, I'd be in favor of not having the `bitcoin::PublicKey` type to improve ergonomics. It seems more correct to pass the information of uncompressed/compressed format at the time it makes a difference instead of keeping it around all the time.

I am happy to submit a patch if we can get the requirements laid out precisely, i.e. what conversions should be possible etc.

**Comment by dpc** [comment]
This `pub compressed: bool,` in `bitcoin::PublicKey` is a bit odd. Shouldn't serialization information be static in the first place?

That would mean `PublicKey` is directly from `secp256k1`, and then there's `CompressedPublicKey` and `UncompressedPublicKey` wrappers, couple of `Into` and other utilities, and APIs can even take `pubkey: Into<PublicKey>` or `pubkey: Into<CompressedPublicKey` etc. if they want to accept both.

A bit of complication, not sure if worth it.

**Comment by stevenroose** [comment]
> I am not expert on ECDSA math but the [this link](https://crypto.stackexchange.com/questions/8914/ecdsa-compressed-public-key-point-back-to-uncompressed-public-key-point) suggests that one can actually convert between the compressed and uncompressed form losslessly?
> 
> Why are we keeping that state around then if we can just convert to the other form at any point? I guess we would need the `secp256k1::Context` to do the math but we need that one anyway in many places.
> 
> For what it is worth, as a downstream user of this library, I'd be in favor of not having the `bitcoin::PublicKey` type to improve ergonomics. It seems more correct to pass the information of uncompressed/compressed format at the time it makes a difference instead of keeping it around all the time.
> 
> I am happy to submit a patch if we can get the requirements laid out precisely, i.e. what conversions should be possible etc.

@thomaseizinger I did that before. I can do that again, but I've noticed we prefer to have it like this.

Yes, you can convert freely between compressed and uncompressed keys. And I don't think we ever store an uncompressed key. At the secp level, there are two methods: `serialize()` and `serialize_uncompressed()`.

The reason for the flag is that one can make 2 different addresses from every pubkey: one with the compressed serialization and one with the uncompressed serialization. While the latter is rare and discouraged, it still exists. So the flag exists to indicate how to make the `PublicKey -> Address` conversion for that key.

And the reason why it's hard to take that boolean flag out of the `PublicKey` struct and just have two methods, like in secp (which is identical to just replacing the type with the secp equivalent), is because a Bitcoin **private key** in WIF format (RAS syndrome for wallet import format format) also carries this information. So when you have a WIF private key, it carries the tuple `(network, privkey, compressed?)`. So in order to make sure that someone using a certain WIF will generate the correct address using `Address::p2pkh(wif.public_key(), wif.network)`, the information about whether the public key should be serialized compressed or uncompressed for the generation of the address needs to be somehow kept.

Without it, it would be something like:
```rust
if wif.compressed {
    Address::p2pkh(wif.public_key(), wif.network)
} else {
    Address::p2pkh_uncompressed(wif.public_key(), wif.network)
}
```

That's [what I implemented](https://github.com/rust-bitcoin/rust-bitcoin/pull/221) but arguably, it's very easy to make a mistake doing the latter. We could just have a `WIF` type with a `p2pkh_address()` getter on it. They are not very common anyhow; and uncompressed public keys are even more rare than WIFs.

If the opinion of the group changed, I'd be happy to get back to that PR. But I'm fine with the current state of affairs. Just store secp pubkeys if you care about storage size :)

**Comment by apoelstra** [comment]
Why stop at splitting the EC point from the compressedness boolean? Why not split all the bytes apart and let users decide when they should be brought together?

**Comment by dpc** [comment]
>  So in order to make sure that someone using a certain WIF will generate the correct address using Address::p2pkh(wif.public_key(), wif.network), the information about whether the public key should be serialized compressed or uncompressed for the generation of the address needs to be somehow kept.

```
enum SerializedPublicKey { // WIFPublicKey ?
   Compressed(PublicKey)
   Uncompressed(PublicKey),
}

enum SerializedPublicKeyRef<'a> { /// too bad & does not generalize better
   Compressed(&'a PublicKey)
   Uncompressed(&'a PublicKey),
}

impl WIF {
  fn public_key(&self) -> SerializedPublicKey;
}

impl Address {
    pub fn p2pkh<PK: AsRef<SerializedPublicKeyRef>>(pk: PK, network: Network) -> Address { ... }
}


impl AsRef<SerializedPublicKeyRef> for &PublicKey {
    fn as_ref(&self) -> &SerializedPublicKeyRef {
         // default to `compressed
         SerializedPublicKeyRef::Compressed(self)
    }
}

/// + bunch of other conversions.
```

Cons: 

* bunch of additional type complexity:
  * understanding this APIs requires understanding more Rust features
  * user mistakes like typos and missing `&` will not probably not get as helpful error messages

Pros:

* everything just works
* `Address::p2pkh(wif.public_key(), wif.network)` does the right thing
* `bitcoin::PublicKey` == `secp256k1::PublicKey`
* types express and enforce the actual reality better

**Comment by dr-orlovsky** [comment]
While working on non-wallet bitcoin applications, I found it highly frustrating the mess created by the introduction of "address" concept (UX topic) directly into layer Bitcoin blockchain (consensus layer) and putting it under the hood of same standard system (BIPs) and - as a consequence - libraries (like we have with `rust-bitcoin`). I would really prefer to have a library working with only `Tx`, `TxIn/Out`, `OutPoint`, `Public/SecureKey`, `Script` — and that's all! No `Address`es, no need to keep information how the public key have to be used in script (compressed or not). And a wallet library above that layer will introduce all of that. But unfortunately, due to historical reasons, there is no such clear separation and abstraction of layers...

**Comment by elichai** [comment]
> While working on non-wallet bitcoin applications, I found it highly frustrating – I mean all the mess created by the introduction of "address" concept (UX topic) directly into layer Bitcoin blockchain (consensus layer) and putting it under the hood of same standard system (BIPs) and (as a consequence) libraries (i.e. `rust-bitcoin`). I would really prefer to have a library working with only `Tx`, `TxIn/Out`, `OutPoint`, `Public/SecureKey`, `Script` – and that's all! No `Address`es, no need to keep information how the public key have to be used in script (compressed or not). And a wallet library above that layer will introduce all of that. But unfortunately, due to historical reasons, there is no such clear separation and abstraction of layers...

how is compressness not part of consensus? it's literally a different object in the script.

**Comment by dr-orlovsky** [comment]
They differ in serialization, but not validation rules. With private key I can spend pubkeyScript with both compact and non-compact pubkey by generating the right serialization

**Comment by apoelstra** [comment]
You don't even need the private key - just generate the right serialization.

Less snarkily, if you drop the compressedness flag, you are deleting a bit of the key. Just because you can grind out this bit to recover it, does not mean that the compressedness flag is somehow "not part of the key" or a historical wart or anything like that.

**Comment by stevenroose** [comment]
I don't think there's anything to say about the pubkey ambiguity anymore. Let's close this issue.
