### ISSUE TITLE
Get rid of `BitcoinHash` trait

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#383]
Once we have now type-specific hashes, we can move from using `BitcoinHash` trait to more idiomatic `From` trait; i.e. instead of `impl BitcoinHash<BlockHash> for BlockHeader` do `impl From<BlockHeader> for BlockHash`.

Also, it has come to my notice that there is no function to convert `PublicKey` into a `(W)PubkeyHash`, so this will solve this issue as well.

**Comment by stevenroose** [comment]
Yikes, I don't think that's what the from trait is intended for!

> Used to do value-to-value conversions while consuming the input value.

Personally I don't think we need a trait for this at all. It's just annoying that you need to import an extra trait to call the hash function. I think the original idea of the trait was to do things like merkle tree calculation over any set of similar hashable objects. But turns out that most merkle trees are actually built using txid's which are no longer equivalent to the `BitcoinHash` impl. So I vote to remove the trait altogether.

**Comment by dr-orlovsky** [comment]
Since I wrote my version of code yesterday before @stevenroose I will just create an alternative PR with it for comparison of the possible solutions: #386

**Comment by apoelstra** [comment]
I do think we should drop the trait because it's no longer useful (you can just serialize objects into a hash engine now, like we do in Core). But agreed that using `From` for this is creative, to say the least.

**Comment by dr-orlovsky** [comment]
Ok, let's stick to the @stevenroose PR then, I will close mine
