### ISSUE TITLE
Use Miniscript in script::Builder instead of direct script construction

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#393]
I think this can be a good starting point for use of Miniscript in the library. I will work on it in the following days, will appreciate any suggestions and recommendations!

**Comment by TheBlueMatt** [comment]
We certainly have to offer both, we can't *only* offer miniscript, though.

**Comment by apoelstra** [comment]
I don't think rust-bitcoin should depend on rust-miniscript. Miniscript is bigger and less general.

**Comment by dr-orlovsky** [comment]
So what would be a suggested plan for rust-bitcoin and miniscript "relations"? None? Since just recently there was a discussion proposing to add it, so I was basing on it: <https://github.com/rust-bitcoin/rust-bitcoin/pull/333>

**Comment by apoelstra** [comment]
rust-miniscript needs to depend on rust-bitcoin, of course. If people want to do interesting things with Script they should depend on rust-miniscript, but otherwise they shouldn't need to care that it exists.

I think rust-bitcoin should have basic support for the different address types, as well as BIP32, but in general I think that advanced script/wallet stuff should happen more in rust-miniscript than in this library.

**Comment by dr-orlovsky** [comment]
I think I can close this issue then, since nothing has to be done in `rust-bitcoin`: its status quo matches the description
