### ISSUE TITLE
Network names are not BIP70 conform

### ISSUE THREAD

**Issue by bonomat** [rust-bitcoin/rust-bitcoin#423]
According to bitcoind's api documentation in [1], valid names for the network are defined in BIP70 ([2]) and can be either `main` or `test` (`regtest` not defined in BIP70).

Is there a particular reason why `Network` uses different values? 

https://github.com/rust-bitcoin/rust-bitcoin/blob/c3a7d1b27cf46bdf8a0d3c4dc20d6f0a0a0b5206/src/network/constants.rs#L50-L56

Resources: 
* [1] bitcoind api doc: https://bitcoincore.org/en/doc/0.19.0/rpc/blockchain/getblockchaininfo/
* [2] BIP70 https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki

**Comment by TheBlueMatt** [comment]
BIP70 is long-since deprecated, so I don't think its a good benchmark for naming. There are various bits of constants that folks have suggested for including altcoins that are sufficiently bitcoin-compatible so as to not require library-level changes. Thus, "main" may be a bit confusing. I don't know that it really matters, but if we want to change the we should well-define exactly what they mean (ie add documentation noting that they are Bitcoin Core RPC compatible names).

**Comment by stevenroose** [comment]
I agree that it's not necessary to change this. Any RPC-critical naming would be done in `rust-bitcoincore-rpc` already.

**Comment by bonomat** [comment]
Makes sense. Thanks for the responses.
