### ISSUE TITLE
Ryu 1.0.5 incompatible with Rust 1.22

### ISSUE THREAD

**Issue by sgeisler** [rust-bitcoin/rust-bitcoin#430]
The transitive dependency `ryu` caused by `serde_json` is incompatible with rust 1.22 at least from `v1.0.5` on (see #429). We probably want to pin to an older version of `serde_json` to fix this or try to get patches into upstream to regain compatibility (it only seems incompatible due to the `crate` keyword used in a `use` statement).

**Comment by elichai** [comment]
Well, we pinning a specific `serde_json` version won't help because it uses `ryu ="1.0"`
We could however pin `ryu =  "< 1.0.5"` which should work transitively and force `serde_json` to use the right version. 
But I guess we should instead adapt the same policy as in https://github.com/rust-bitcoin/rust-secp256k1/pull/204 (which we'll have to do after that is released and we bump the dependency)

**Comment by sgeisler** [comment]
I jut tried to pin `ryu`, didn't seem to work. Another fix would be to not run tests but just to test if the crate compiles with old rust. `serde_json` is just a dev dependency for testing afaik. And rust shouldn't change its behavior in a backwards-incompatible way. So this might be good enough if the pinning gets too hacky.

**Comment by sgeisler** [comment]
False alarm, `ryu = "=1.0.4"` works. I got confused by the test failing to compile if I activate the serde feature. Will PR asap.
