### ISSUE TITLE
Lacking git tags

### ISSUE THREAD

**Issue by petertodd** [rust-bitcoin/rust-bitcoin#54]
I think this is needed for accountability/clarity, and they should be signed.

I'd be happy to create a set.

**Comment by dongcarl** [comment]
Should be closed? It seems that 0.13.2 isn't signed though

**Comment by apoelstra** [comment]
I don't think any of them are signed. I want to leave this open until I get my GPG signing key mess sorted out.

**Comment by dongcarl** [comment]
Why does https://github.com/rust-bitcoin/rust-bitcoin/tags show that they're signed?

**Comment by thomaseizinger** [comment]
> Why does [rust-bitcoin/rust-bitcoin/tags](https://github.com/rust-bitcoin/rust-bitcoin/tags) show that they're signed?

It says that the _commit_ is signed. I am no Git expert but I think that is different from signing a tag.

The reason the commits are signed is because they are merge commits done through GitHub's PRs. Those are signed by a key owned by GitHub.

**Comment by stevenroose** [comment]
Yeah, it says
> This commit was created on GitHub.com and signed with a verified signature using GitHub’s key.

It's different then having a `git tag -s`. I'd prefer to have them tagged by one of the maintainers, though. I do this with all libraries I maintain and also in rust-bitcoincore-rpc f.e.: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/releases/tag/v0.2.0.

**Comment by dongcarl** [comment]
:man_facepalming:

**Comment by stevenroose** [comment]
Is it possible to have multiple contributors sign tabs? Like can I pull in a tag, add my signature and push it again, f.e.? That would be ideal IMO.

**Comment by petertodd** [comment]
@stevenroose You can! Literally by just adding another signature to the end of the git commit signature, and GnuPG will even show both valid signatures. This is similar to how OpenTimestamps works actually.

That said, AFAIK there's no tooling to actually create such commits. And remember that the commit hash will change when you do this.

There's also a per-commit "note" feature that could be used for this: https://git-scm.com/docs/git-notes

The advantage would be notes can be attached to any object in git without changing the object itself. But I don't know if GitHub and other tools actually support notes - they're pretty recent.

**Comment by stevenroose** [comment]
@petertodd Hmm, I was thinking of git tags rather than commits. Tags don't have a hash, right, so nothing would change if it was possible to add a signature to the tag.

**Comment by petertodd** [comment]
@stevenroose Ah! You might cause some minor issues with git in synchronization between repos; dunno how well git handles that case. But yes, you're correct in thinking that adding an additional signature wouldn't directly affect anything.

**Comment by junderw** [comment]
[0.28.0-rc1](https://github.com/rust-bitcoin/rust-bitcoin/releases/tag/0.28.0-rc1) was signed by @apoelstra in January 2022.

Tags after that have not been signed.

**Comment by apoelstra** [comment]
Oops, I forgot. I will redo the tags since January here and in rust-secp.

**Comment by junderw** [comment]
@apoelstra What are your thoughts on Github's "Verified" feature?

All your signatures show up as "Unverified" because you haven't manually uploaded your public key to your Github Account...

While I think there is a point to be made about the problem with Github auto-signing everything with a hot always online key and marking that as "Verified", and keeping it "Unverified" might force/encourage people to verify outside of Github...

At the same time, I think it is more likely to put off devs rather than encourage them to verify OOB.

I personally think you should upload your key so it shows as "Verified" but it's not that big a deal.

**Comment by junderw** [comment]
My point being:

Github auto-signed web-UI commits (using Github's keys) and locally signed commits (using the user's keys) are shown as Verified in the same way (you need to click the "Verified" image to see the difference) and because of this many people give them both the same unconscious "security weight."

A point could be made that, by enabling vigilant mode and explicitly making all of your locally signed commits show as Unverified, you would encourage people to "investigate" the signature and actually verify it locally.

However, the counter-point (and my view) is that most people would just take "Unverified" to mean "not trustworthy" and assume there is something wrong / refuse to use the repo in fear of "tampering" etc... rather than investigate further.

**Comment by petertodd** [comment]
In both cases you're trusting GitHub, as you are relying on their UI code to tell you what you are seeing. So I see no issue in uploading your public key to make commits appear as verified.

**Comment by apoelstra** [comment]
I tried to upload my public key and repeatedly got an opaque "Error occurred".

I agree it's harmless to give them my public key (they have my email address and can find the key on multiple keyservers with that if they want). But the benefit is also too small for me to bother trying to figure this out.

**Comment by apoelstra** [comment]
Also Microsoft has spent *decades* throwing slurs at open source projects. If somebody is going to avoid something now because they called some of our commits "unverified" there's no helping them.

**Comment by tcharding** [comment]
Is there a path forward on this issue or can we close it?

**Comment by apoelstra** [comment]
The path forward is that I go through and sign all the old tags, or this my tag-signing habit gets old enough (looks like I started in Jan of this year) that we can forget about the old ones.

**Comment by tcharding** [comment]
January of this year means anyone using the edition 2018 versions gets signed tags, that's good enough IMO.

**Comment by apoelstra** [comment]
Signed all the rust-bitcoin tags back to 0.20.0 (Aug 2019) and all the rust-secp tags back to when we did the secp/secp-sys split (Dec 2019).

I also finally wrote a script to recreate old tags as signed ones, so if people want me to do this for other repos I can do it without too much trouble.

**Comment by apoelstra** [comment]
Signed them all since I realized I might as well just loop through the whole output of `git tag`.

**Comment by junderw** [comment]
Noticed [0.28.2](https://github.com/rust-bitcoin/rust-bitcoin/releases/tag/0.28.2) is still unsigned FYI.

**Comment by junderw** [comment]
It's created by @TheBlueMatt

**Comment by petertodd** [comment]
Just checked, and 0.28.2 seems to be signed now on a fresh checkout.

Thanks!

Also, going forward, I would suggest timestamping tags with OpenTimestamps too: https://petertodd.org/2016/opentimestamps-git-integration

**Comment by apoelstra** [comment]
I opened a separate issue for opentimestamps.
