### ISSUE TITLE
Add FindAndDelete for Signature hash calculation

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#570]
Add support sighash for scripts with `OP_CODESEPARATOR`.

**Comment by sanket1729** [comment]
I will do it at some point in the future but is up for grabs if anyone wants to do it, it's up for grabs

**Comment by apoelstra** [comment]
lol nobody wants to do this, I'm afraid it's gonna be on you :)

**Comment by vss96** [comment]
I would like to give this a try but I might be out of my depth here 😅

**Comment by apoelstra** [comment]
@vss96 that would be welcome! But be aware that our signature hash computation has changed a bit since this issue was opened. In particular, since #628 we have a new structure, `util::sighash::SigHashCache` which is responsible for computing sighashes.

To implement CODESEPARATOR, you need to change the legacy sighash algorithm to implement `FindAndDelete` (see the Bitcoin Core source code for what this is); for the segwit and taproot sighashes, the CODESEPARAOR behavior is much simpler and can be found in their respective BIPs (141 for segwit and 341 for taproot, I believe)

**Comment by sanket1729** [comment]
@vss96 you can reach me on IRC(libera) or on Twitter for more assistance

**Comment by tcharding** [comment]
@vss96 its been a while since you posted so I had a go at this one. Hope you don't mind.

**Comment by vss96** [comment]
@tcharding Please go ahead and work on it, I never got the time to work on this 😓 .

**Comment by tcharding** [comment]
Shall we close this one then @sanket1729?

ref: https://github.com/rust-bitcoin/rust-bitcoin/issues/777#issuecomment-1073034640

**Comment by tcharding** [comment]
No action on this for a long time and I don't think we are going to support `OP_CODESEPARATOR` any time soon.
