### ISSUE TITLE
Document constraints on nonce in bitcoin::network::message_network::VersionMessage

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#575]
The `nonce: u64` field in `bitcoin::network::message_network::VersionMessage` is not documented, so I'm not sure what are the constraints on its value.

`btc-rpc-proxy` depends on `rand` just to set its value, so I wonder if it needs to be random. Would it be perhaps sufficient to use `AtomicU64` and just increase it by one every time network message is sent?

**Comment by TheBlueMatt** [comment]
The `nonce` field is used to detect accidental connection-to-self. eg if you're running a public node, you may connect to an address, not realizing its your own and then just talk to yourself. By sending a random value, you can check if the connection you just got matches the connection you just made. Predictable values may result in nodes accidentally disconnecting each other just because they're at the same nonce count, though if you hashed something unique (even publicly tied) to the current node, that would be ok.

**Comment by Kixunil** [comment]
Hmm, so if the application opening connection doesn't actually listen it could as well set it to 0, right?

**Comment by TheBlueMatt** [comment]
That seems reasonable, yes. Better question is why an "rpc-proxy" program is connecting to P2P - it'd be somewhat malicious to query another node via P2P in response to local RPC commands.

**Comment by Kixunil** [comment]
Great, thanks!

It's a new, opt-in feature that allows pretending the node is **not** pruned by fetching the data (using clearnet or Tor) from a random node and of course validating it before returning it.

**Comment by tcharding** [comment]
This field currently has `/// A random nonce used to detect loops in the network` - is that enough to close this issue?

**Comment by Kixunil** [comment]
I think we can do better. Something like:

> A random nonce used to detect loops in the network.
>
> The nonce can be used to detect situations when a node accidentally connects to itself. Set it to a random value and, in case of incoming connections, compare the value - same values mean self-connection.
> If your application uses P2P to only fetch the data and doesn't listen you may just set it to 0.
