### ISSUE TITLE
Efficiently serialize non Encodable data

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/rust-bitcoin#595]
I've got a use case where I would like to efficiently serialize something like `Vec<Option<TxOut>>` and I can't use `bitcoin::consensus::serialize` because `Option` it's not `Encodable` and it looks neither I can use serde because it's not efficient at all (maybe because it's json specific?).

```
let genesis = genesis_block(Network::Bitcoin);
let a = serde_cbor::ser::to_vec_packed(&genesis).unwrap();
assert_eq!(461, a.len());
let b= bitcoin::consensus::serialize(&genesis);
assert_eq!(285, b.len());
let c: Vec<u8> = bincode::serialize(&genesis).unwrap();
assert_eq!(496, c.len());
```

maybe related https://github.com/rust-bitcoin/rust-secp256k1/issues/295

UPDATED: changed `serde_cbor::to_vec` to `serde_cbor::ser::to_vec_packed` because I noticed `to_vec` store also field names which is unfair compared to others

**Comment by RCasatta** [comment]
I guess I can just implement Encodable for Option<TxOut>

**Comment by TheBlueMatt** [comment]
> I can use serde because it's not efficient at all (maybe because it's json specific?).

That sounds like a bug itself - serde should be pretty efficient, and isn't json specific, or shouldn't be?

**Comment by RCasatta** [comment]
I mean rust-bitcoin serde customization is showing `Vec<u8>` in their hex representation, I think so that in json looks better. but this cause binary encoding to consume two times the space.

```
let vec = vec![0u8, 1u8];
let script = Script::from(vec.clone());
let a = serde_json::to_string(&script).unwrap();
assert_eq!(a, "\"0001\"");
let a = serde_cbor::to_vec(&script).unwrap();
assert_eq!(a, [100, 48, 48, 48, 49]);

let a = serde_json::to_string(&vec).unwrap();
assert_eq!(a, "[0,1]");
let a = serde_cbor::to_vec(&vec).unwrap();
assert_eq!(a, [130, 0, 1]);
```

If it's not possible to have some behavior specifically for json (or any human-readable format) I think we should avoid the hex representation

**Comment by thomaseizinger** [comment]
> If it's not possible to have some behavior specifically for json (or any human-readable format) I think we should avoid the hex representation

It is possible. The implementation for `Serialize` should check on `serializer.is_human_readable`. We do that in a couple of places (f.e. [here](https://github.com/rust-bitcoin/rust-bitcoin/blob/8231e25292d833a56d4678008864c52a596e6b40/src/serde_utils.rs#L231-L236)) but for `Script` in particular, [we don't](https://github.com/rust-bitcoin/rust-bitcoin/blob/8231e25292d833a56d4678008864c52a596e6b40/src/blockdata/script.rs#L853-L862).

**Comment by dpc** [comment]
> I've got a use case where I would like to efficiently serialize something like Vec<Option<TxOut>> and I can't use bitcoin::consensus::serialize because Option it's not Encodable and it looks neither I can use serde because it's not efficient at all (maybe because it's json specific?).

Can you explain what are you doing?

Would you want `rust-bitcoin` to implement `Encodable` for basic containers like `Arc`, `Box`, `Vec`, `Option` and alikes?

**Comment by RCasatta** [comment]
> Would you want rust-bitcoin to implement Encodable for basic containers like Arc, Box, Vec, Option and alikes? Seems reasonable, but does it solve your problem?

Yes, I would like it and it will help to solve my problem better than using serde serialization (because consensus encoding looks more space-efficient)

However, it looks from https://github.com/rust-bitcoin/rust-bitcoin/pull/264 and in comments like https://github.com/rust-bitcoin/rust-bitcoin/pull/264#discussion_r287142652 that the direction is to have consensus_encode specifically for consensus types...

About my use case, I made a blocks iterator https://github.com/RCasatta/blocks_iterator and computing fees is pretty memory hungry.  I thought having a map of transactions outputs instead of a map of outpoints may save some memory. (but I have to keep track of spent outpoints so that I can remove it once the transaction has no unspent outputs, that's why I would have wanted a Vec<Option<TxOut>>. Also, serialization helps to have fewer heap allocations.

**Comment by dpc** [comment]
> About my use case, I made a blocks iterator

Oh. That's cool. I guess every single bitcoin indexer kind of works in this way, so what you describe very much fits what I've been doing in https://github.com/dpc/rust-bitcoin-indexer.

First - on the point. Your use case seems so particular, that is probably not worth influencing `rust-bitcoin` needs. I'd just use own types for outpoints etc. and use some other serialization that is even more compact.

Less on the point.

>  I thought having a map of transactions outputs instead of a map of outpoints may save some memory. 

My understanding is that what you have is:

```
Map<OutPoint, TxOut>;
```

and you consider something along the:

```
Map<TxId, Vec<Option<TxOut>>
```

?

so you can use mark spent ones with `None`?

Are you sure this scheme is worthwhile? I would be guessing that a lot of txes gets spent rather quickly, so the simplest solution seems quite optimal.

Also `None` in such vector would still take as much space as `Some`, so as long as not all the outputs are spent, such an entry in a map would linger and keep using more memory than necessary.

One of the biggest optimizations there is to use just first N bytes of txid as a prefix, to save on the key storage. I was using 16B prefix, which seems pretty much guaranteed to be unique. If some way to resolve duplicates (like `txindex`) is available, I would go with `8B`.

Another optimization I would consider is using LRU if `-txindex` is available to have the memory usage bounded and get 90% of a speedup with 10% of memory used.

Another optimization I was wondering about is offloading scripts to a separate set with `(Outpoint, ref_counter)`, since address re-use is unfortunately a common thing and scripts are the biggest part of the output.

Just my 2c.

**Comment by RCasatta** [comment]
> Oh. That's cool. I guess every single bitcoin indexer kind of works in this way, so what you describe very much fits what I've been doing in https://github.com/dpc/rust-bitcoin-indexer.

I recently saw it, similar but different at the same time, mine is much simpler, without a db, without the rpc...

> My understanding is that what you have is:  `Map<OutPoint, TxOut>;`

I've got `Map<u64, TxOut>` where `u64=fxhash(OutPoint)` with fallback to `Map<OutPoint, TxOut>` if collision occurs (even if there are only 2 collisions, the bip34 txs).

> and considering having: `Map<TxId, Vec<Option<TxOut>>`

I am considering `Map<u64, Vec<u8>>` where `u64=hash(TxId)` and `Vec<u8>=serialize(Vec<Option<TxOut>>)`

> Are you sure this scheme is worthwhile?

No, especially computationally is expensive, however, I will give a try (probably with CustomOption and CustomVec) to check if there is less memory usage, if it's worthwhile I can probably add more parallelism.

> Also None in such vector would still take as much space as Some, so as long as not all the outputs are spent, such an entry in a map would linger and keep using more memory than necessary.

That is not true because of the serialization to Vec<u8>. But it's not true even without serialization because`TxOut` is not only on the stack, the Script is a Box that points to a heap location (which is not used in case of None)

> One of the biggest optimizations there is to use just first N bytes of txid as a prefix, to save on the key storage. I was using 16B prefix, which seems pretty much guaranteed to be unique. If some way to resolve duplicates (like txindex) is available, I would go with 8B.

In the case of txid, I don't think you need txindex to resolve duplicates? have a look at https://github.com/RCasatta/blocks_iterator/blob/master/src/truncmap.rs

> Another optimization I was wondering about is offloading scripts to a separate map with Map<prefixofsomekind, Vec<(rest_of_the_output, ref_counter)>> or something since address re-use is, unfortunately, a common thing and scripts are the biggest part of the output.

may be worth it, but sad at the same time :)

**Comment by dpc** [comment]
> I recently saw it, similar but different at the same time, mine is much simpler, without a db, without the rpc...

Exactly. I very much like your approach, which might be very useful for "one off" jobs that can just run quickly through whole history and compute some stuff. I actually know of at least one immediate use for it and will share it with some people.

> I've got `Map<u64, TxOut>` where `u64=fxhash(OutPoint)` with fallback to `Map<OutPoint, TxOut>` if collision occurs (even if there are only 2 collisions, the bip34 txs).

Oh. This is smart. Why haven't I thought about fallback map? :) . Oh. I know - because in case of `rust-bitcoin-indexer`, I might not have all the unspents at all times (they can be lazily loaded on first use after restart) so I might not be able to detect collisions like that, so I needed a way that always works.

Is there any reason to use `fxhash` instead of just take some bytes of txhash? txhash is already uniform and "random", no? Is this to protect from people crafting collisions on purpose? But then - they could as well craft them against `fxhash` since it doesn't seem to be randomized.

> That is not true because of the serialization to Vec. But it's not true even without serialization becauseTxOut is not only on the stack, the Script is a Box that points to a heap location (which is not used in case of None)

Oh that's what I meant - kind of. Serialization is going to be computationally expensive, and even without script a tx with many outputs can linger like that for a while with all these Nones (which are not big on their own, but they add up - especially since you seem to have rather compact format with two maps already). 

> I will give a try (probably with CustomOption and CustomVec) to check if there is less memory usage,

I'm very interested in the results. I might be able to utilize this knowledge, so I'd appreciate pinging me about the results!

>  if it's worthwhile I can probably add more parallelism.

I'm wondering if it access to this map will not have to be serialized due to potential of race conditions etc.

**Comment by RCasatta** [comment]
> Is there any reason to use fxhash instead of just take some bytes of txhash? txhash is already uniform and "random", no? Is this to protect from people crafting collisions on purpose? But then - they could as well craft them against fxhash since it doesn't seem to be randomized.

The main reason to use another hash is vout, because it's not uniformly distributed in the search space. For example if you take 6 bytes from the txhash and only 2 for vout (u16 because historical max vout is 30000) you will end up with one byte almost always 0, increasing chances of collisions.
It's fxhash just because it's faster than standard siphash, especially if you have longish keys. And yeah, if someone craft transactions to create collisions on this iterator I can switch to siphash.
Also, note that I am doing the hash externally and then using a `PasstroughHasher` which basically skip hashing inside the hashmap because you already have a uniformly distributed key

> I'm very interested in the results. I might be able to utilize this knowledge, so I'd appreciate pinging me about the results!

sure!

> I'm wondering if it access to this map will not have to be serialized due to potential of race conditions etc.

Exactly, I can't wait to try something like this https://stackoverflow.com/a/65038724/1113302 :)

**Comment by RCasatta** [comment]
@dpc FYI I did a couple of tests:

* branch testser using `Vec<u8>=serialize(Vec<Option<TxOut>>)` , on testnet it uses about half memory ~5GB down from ~10GB, however it's about 3 times slower and even more on mainnet
* branch script_reuse using your idea of keeping a reference to scripts, on mainnet saves about 10% of memory but it is slower about 10% more. Moreover, as I have implemented it, eventual script collision would result in getting wrong prevout scripts.

In the end I decided neither of the two approaches is worth pursuing
