### ISSUE TITLE
Rust Style Conventions

### ISSUE THREAD

**Issue by JeremyRubin** [rust-bitcoin/rust-bitcoin#692]
> My understanding of naming:
> 
>     * `new` - obvious constructor, may be empty (`String::new()`, `Box::new(T)`)
>     * `from_` - takes _same_ information as `new` just in different representation (e.g. `String::from_utf8(Vec<u8>)`)
>     * `with_` - takes _additional_ information along with what `new` takes `String::with_capacity(usize)`

I thought `String` was a bit of a special case but a quick look at the std lib shows its not. Perhaps conventions have changed for more recent code? I was under the impression that
- Constructors with zero args should use `Default`
- Constructors with one arg should use `From<Foo>` (unless the foo needs further restriction like the `String;:from_utf8` case)
- Constructors with multiple args should use `new`.
- Constructors using the builder pattern should use `with(self, foo: Foo)`

I've never managed to work out the pattern for times when we need multiple constructors with multiple args? 

Amusingly I was looking at all the instances of single arg constructors for `Script` yesterday wondering why they used the pattern `new_`.

I don't mean to bike shed here, I'm genuinely interested in these sorts of conventions.

_Originally posted by @tcharding in https://github.com/rust-bitcoin/rust-bitcoin/issues/677#issuecomment-965759461_

**Comment by JeremyRubin** [comment]
@tcharding  i'd advise against implementing Default unless it is truly a default. E.g., imagine some kind of client where:

Client::new() creates an uninitialized client that needs some sort of initialization before it's safe to use, but you might want to do one to allocate the storage for it?

You might also run into issues creating e.g. default for Option<T> since it's already to return None, where you might want something else.

Same with From, TryFrom, etc. You only want those if it's a true conversion, otherwise implement your own logic/names.

**Comment by TheBlueMatt** [comment]
I'm sure everyone has their own views, but I *always* prefer the explicit forms of things. `ThingImConstructing::way_im_constructing_it` over `Trait::trait_method`. That implies no `Default` or `From` in the common case - those are, in my mind, useful things for specific cases, eg if you have a bag of settings, maybe `Default` is pretty clear to the user, or `From` allowing more concise conversion for things that are really basically equivalent.

**Comment by tcharding** [comment]
Good job on opening the issue @JeremyRubin, thanks for your response.

> Same with From, TryFrom, etc. You only want those if it's a true conversion, otherwise implement your own logic/names.

Cool, this makes sense. I was writing while @TheBlueMatt commented but that comment concretes this even more, makes usage of `into` less mysterious as well. Cheers.

Re `Default`: I don't really understand. Using your example, I would expect the default client to be uninitialized? I've been following clippy for this one so I'm keen to fully understand your position on when it _is_ ok to use `Default`. For the record I just went searching for the lint name for this by writing a quick example and could not get a clippy warning for stable or nightly. One other point is deriving `Default`, I guess that is why things like `HashMap` have an empty `new` and also implement `Default`. This begs the question why can't we use `#[derive(New)] to derive an empty constructor?

**Comment by TheBlueMatt** [comment]
> 've been following clippy for this one so I'm keen to fully understand your position on when it is ok to use Default

Everything is about readability at the call-site. `ThingImConstructing::way_im_constructing_it` starts with a pretty strong advantage in most cases, so you have to (IMO) have a pretty good reason to use `Default`. One reason is that Default can allow some containing object to include the inner type via `Default` or the like. At least in rust-lightning, I think the only use of `Default` we have is some user-config structs. There its pretty clear that `default` means "the default values of the config options", though I admit a `default_settings` may have made even more sense.

**Comment by Kixunil** [comment]
> Constructors with zero args should use `Default`

And also `new()` as clippy says.

> Constructors with one arg should use `From<Foo>`

*Infallible* constructors should, fallible should use `TryFrom` but probably only if the conversion is obvious. (There's no `TryFrom<Vec<u8>> for String` but there is `TryFrom<u64> for u32`

> I'd advise against implementing Default unless it is truly a default.

Yes, `Default` only makes sense for types that have some kind of "empty" or "zero" state. (TBH I'd prefer `Default` to not exist and have two similar traits instead: `Empty` and `Zero`)
Anyway, I never saw anyone (maybe except inexperienced programmers) use the pattern from other languages where type is in invalid state first, so this is non-issue?

 > That implies no `Default` or `From` in the common case

I view it similarly. I never implement `From<Inner> for Newtype` (but do `TryFrom` if applicable), and when *calling* methods I usually choose whichever is explicit. (My favorite exception is `PhantomData` where I always use `Default::default()`)

>  when it *is* ok to use `Default`

IMO only collections. Numeric types should use `0` or `T::ZERO`. They can still *implement* `Default` but it should be only called in generic contexts.

> why can't we use `#[derive(New)] to derive an empty constructor

Because `New` is not a trait.

One more remark: when I use `from()` or `default()` I always type `T::from(val)`/`T::default()` instead of `From::from(val)`/`Default::default()` unless it's error conversion (`.map_err(Into::into)`) or I'm lazy (ridiculously long type/type I don't remember)

> including things clippy enforces

I'd be interested in specific examples.

**Comment by tcharding** [comment]
Awesome, cheers lads.
