### ISSUE TITLE
Add regression tests for all serde serializations

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-bitcoin#723]

**Comment by tcharding** [comment]
Is this what you mean: #724?

**Comment by stevenroose** [comment]
Hmm, not sure, we probably shouldn't use JSON as a reference (people use bincode as well f.e.). There is the serde_test crate that helps with doing such regression tests. Doing the simple string things like in your draft is easy with JSON, but as soon as you get more complex things like objects (maps), it becomes a lot harder.

**Comment by tcharding** [comment]
Cool, thanks @stevenroose, converting to draft and leaving this on my todo list.

**Comment by apoelstra** [comment]
My feeling is:

1. Anything is better than nothing :) although with json we do run the risk that map ordering etc could change out from under us and cause spurious breakage .... though I suspect this is true for any serialization of an unordered structure.
2. I like bincode because it's very simple, last I checked it had a very small dep tree, and it's specified in a much stronger way than JSON.
3. I don't like serde-test because in my experience it fails to differentiate between obscure owned-vs-borrowed things in the serde model, which has led to JSON breakage in the past that was passed by my own "regression tests". Which would've been fine except that the tests took me **forever** to write because serde-test was so annoying :)

**Comment by Kixunil** [comment]
1 - I think the test should be written to be order-independent. (Or maybe not if some formats rely on it?)
