### ISSUE TITLE
`ExtendedPrivKey` from WIF does not match original

### ISSUE THREAD

**Issue by mcroad** [rust-bitcoin/rust-bitcoin#745]
I am attempting to generate an xprv from a WIF. The generated xprv does not match the original xprv.
I would expect the assert in the example to work. Am I doing this right?

```rs
let xprv = ExtendedPrivKey::from_str("xprv9s21ZrQH143K3zccLFZysUT7ktWsAhhCpUwYGEKfrUuvoZx2X9mnLTf4xqJkSDLho23AgoVsJzvYiymjeCMqU999q9wzdpE4nLAWkH7wcgM")?;
let xprv_wif: String = xprv.private_key.to_wif();

// convert WIF to ExtendedPrivKey as recommended in
// https://github.com/rust-bitcoin/rust-bitcoin/blob/master/examples/bip32.rs
let wif: PrivateKey = PrivateKey::from_wif(&xprv_wif)?;
let xprv_from_wif = ExtendedPrivKey::new_master(Network::Bitcoin, &wif.to_bytes())?;

// assertion fails
assert_eq!(xprv.to_string(), xprv_from_wif.to_string());
```

**Comment by apoelstra** [comment]
The example is starting from a WIF key and generating a master xpriv, which is perfectly fine (though I guess it is a pretty weird thing to do .... the point I believe was to demo how to create a BIP32 derivation starting from a master seed, and we may have reached for WIF because it was handy, not because it was a normal/wise way to store a seed).

What it does *not* do, and can't do, is derive any non-master xpriv, and you cannot convert xpriv -> WIF -> xpriv in this way.

I think we should hex-encode the master seed in our example. Agreed that using WIF here is confusing and potentially misleading.
