### ISSUE TITLE
no-std feature more problematic than anticipated

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#758]
When attempting to support `no_std` in `ln-types` I found out that `no-std` makes it problematic:

* It essentially requires re-exporting this feature in the consuming libraries (and the consumers of consumers and so on...)
* It will not work well with the upcoming [weak dependency features](https://github.com/rust-lang/cargo/issues/8832) because the intention was for depending library to provide `std = ["bitcoin?/std"]` so that the number of features doesn't blow up.
* The feature is irrelevant for consumers that only use things without IO or allocation (e.g. `Amount`) so it's not nice to force it.

Proposed solution:

* Finer feature gating - disable `blockdata` and other things without `alloc`
* Either disable consensus encoding without either `std` or `core2` or depend on `core2` unconditionally (it reexports `std`) or use other crate or NIH `io` traits (and change encoding traits). As a byproduct of this we could get rid of `.expect("hash engines don't err")`.
* Use dependency inversion to avoid dependency on `hashbrown`

**Comment by TheBlueMatt** [comment]
> Either disable consensus encoding without either std or core2 or depend on core2 unconditionally (it reexports std) or use other crate or NIH io traits (and change encoding traits).

We'd have to stop using core2. I don't think we want to universally depend on it. It really really really sucks that Rust hasn't addressed this yet in core :(

> Use dependency inversion to avoid dependency on hashbrown

Not sure what you mean here?

**Comment by Kixunil** [comment]
> We'd have to stop using core2.

Why?

> Not sure what you mean here?

```rust
trait Map {
     type Key;
     type Value;

    fn get(&self, key: Key) -> Option<&Value>;

   // ...
}

#[cfg(feature = "std")]
impl<K, V> Map for std::collections::HashMap<K V> { ... }

fn something_that_uses_map::<M: Map>(map: M);
```

The user supplies their map, we don't care what it is.

**Comment by TheBlueMatt** [comment]
> We'd have to stop using core2.


Because I don't think the trust level we have in core2 is even remotely good enough to unconditionally depend on it.

> The user supplies their map, we don't care what it is.

Ah, hmm, that's pretty gross for no-std users without a default. I guess we could consider instead going towards supporting compiling with neither feature, with "not(std)" simply not compiling things that require IO. All that said, I do think this is maybe less bad than we think - downstream crates already have to think about whether they support no-std, and enabling flags is no different. Eg in rust-lightning, the no-std flag replaces Mutexes with RefCells, and I imagine similar things will exist in any non-library crates. Passing features down isn't that crazy.

**Comment by Kixunil** [comment]
Was thinking about reviving `genio` lately, do you think it'd be more trustworthy given I'm a collaborator here and a publicly-known Bitcoiner/Rustcean? Could also give access to people from here.

> Ah, hmm, that's pretty gross for no-std users without a default.

We could still have a feature to turn on `hashbrown` if it's popular. The upside is increased flexibility and "do not pay for what you don't need"

> "not(std)" simply not compiling things that require IO

I tried to experiment with this refactoring for a bit and apart from it being massively complicated it'd disable insanely large part of the crate. The only progress forward I can see now is either defining our own traits (and implement wrappers for std or ditch the ability to avoid `expect`) or depend on something else.

> Passing features down isn't that crazy.

I believe weak dependency features are intended to reduce that so long term it'd be good to be compatible with it.

**Comment by TheBlueMatt** [comment]
> Was thinking about reviving genio lately, do you think it'd be more trustworthy given I'm a collaborator here and a publicly-known Bitcoiner/Rustcean? Could also give access to people from here.

Is that very different from NIH-ing it? Or are you suggesting we do that? If we're gonna NIH it maybe there's a better way forward with our own IO traits that we impl for std, though there were some issues in that direction in the original no-std PR.

> I tried to experiment with this refactoring for a bit and apart from it being massively complicated it'd disable insanely large part of the crate.

Ugh, okay.

> I believe weak dependency features are intended to reduce that so long term it'd be good to be compatible with it.

I don't see why that's relevant, really, we have to turn some code on for no-std, and we have to turn other code on for std. This is a pretty common desire, was my point, and can be seen even more extreme in the `rust-lightning` repo.  At the end of the day, this really just needs to be fixed by Rust.

**Comment by Kixunil** [comment]
> Is that very different from NIH-ing it? Or are you suggesting we do that?

Not sure at this point. I started some experimenting with `genio` refactor. One thing I'd really like to address is `std`s inability to efficiently read into uninitialized buffers. This obviously requires `unsafe` so either we make exception for it, inefficiently NIH it without it or depend on `genio`. I think experimentation in `genio` could provide us some feedback on how to do it here.

> This is a pretty common desire, was my point

I wonder if this is also felt in wider Rust community or we're trying to fit a square peg into a round hole. (I'm afraid the latter.)

**Comment by Kixunil** [comment]
For those who are interested in `genio` refactor, here's the PR: https://github.com/Kixunil/genio/pull/24

It's not complete in the sense of being releasable but most important stuff is done.

**Comment by Kixunil** [comment]
Thankfully, we've already deleted `no-std` feature! :tada:
