### ISSUE TITLE
Unify `EcdsaSig` decoding

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#759]
`Deserialize` looks nearly identical to the implementation of `FromStr`. It'd be nicer to put the common part into a separate function and call it from both places. Maybe even `impl<'a> TryFrom<&[u8]> for EcdsaSig`

_Originally posted by @Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/pull/669#discussion_r780689066_

**Comment by dr-orlovsky** [comment]
Probably this can't be done properly due to the facts discussed in https://github.com/rust-bitcoin/rust-bitcoin/pull/669#discussion_r780825023

Specifically, they are not the same: one uses from_u32_consensus and the other from_u32_standard, which is an important difference. Also, errors are different, so moving this code to a shared function will result in having more code and not less.

**Comment by Kixunil** [comment]
The error would've been mapped but different encoding is really a dealbreaker.
