### ISSUE TITLE
Encoding a TX with the SIGHASH_SINGLE bug

### ISSUE THREAD

**Issue by MatanHamilis** [rust-bitcoin/rust-bitcoin#817]
In
https://github.com/rust-bitcoin/rust-bitcoin/blob/cb35766979c5541c4e158fa7c0aae4b50ab13f9e/src/blockdata/transaction.rs#L340-L346

The SIGHASH_SINGLE bug is handled where the input for which we compute the `scriptSig` signature is using SIGHASH_SINGLE without a matching output.

However, the code writes to the writer the array of "1000...0" which will be later hashed again by the writer, resulting the wrong hash being signed, i.e. the hash to be signed should simply be "1000...0" and not the hash of it.

**Comment by apoelstra** [comment]
Cool! What an ugly bug to fix :/. This was introduced when we abstracted the sighash to allow it to be written directly into a hash engine, without intermediate vectors.

**Comment by apoelstra** [comment]
Since #860 this bug now has a different form.

**Comment by tcharding** [comment]
This issue is tagged as part of the 0.28 milestone, implying that it is holding up the release of 0.29 - is that the case?

**Comment by apoelstra** [comment]
Yes, we should make a decision about whether/how to resolve it.

Our choices are basically "let the current situation be", which is to produce a wrong hash in response to the SIGHASH_SINGLE bug, or to make the `encode_signing_data_to` return an error, which is a scary breaking change because it makes a function that currently never fails (if you give it a hash engine anyway) into one that will fail given bad input.

**Comment by tcharding** [comment]
Why would anyone use the `encode_signing_data_to` function instead of the `signature_hash` function? I don't get why its a public function?

I added https://github.com/rust-bitcoin/rust-bitcoin/pull/897 that returns an error but I'm not fully understanding the implications that you describe of changing it to a function that now errors on bad input.

**Comment by tcharding** [comment]
Thanks for the explanation @apoelstra.
