### ISSUE TITLE
Use infallible conversions from hashes to `secp256k1::Message`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#824]
https://github.com/rust-bitcoin/rust-bitcoin/pull/819#discussion_r801472840

And check/fix other cases as well.

**Comment by arturomf94** [comment]
Hi @Kixunil / @bruteforcecat - is this still an open issue? 

I see #851  has been opened as a draft, but I don't know if it's up for grabs now?

**Comment by Kixunil** [comment]
I think #830 should've been resolved by #1065, so feel free to give it a try!

**Comment by arturomf94** [comment]
Thanks! I think I'll have a stab! Could you assign it to me please? 🙏

**Comment by tcharding** [comment]
Go for it man! Thanks

**Comment by arturomf94** [comment]
Hi @tcharding / @Kixunil - I'm having some trouble with this one. I've replaced all instances of `secp256k1::Message::from_slice(_).expect(_)` to `secp256k1::Message::from(_)`. There is one particular case in which I'm getting an error:

https://github.com/rust-bitcoin/rust-bitcoin/blob/cd790dc7e931ff359cdc6c487520c73a17c2f14b/src/util/misc.rs#L143

The error I'm getting is:

```rust
error[E0277]: the trait bound `hashes::sha256d::Hash: secp256k1::ThirtyTwoByteHash` is not satisfied
   --> src/util/misc.rs:143:23
    |
143 |             let msg = secp256k1::Message::from(msg_hash);
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `secp256k1::ThirtyTwoByteHash` is not implemented for `hashes::sha256d::Hash`
    |
    = note: required because of the requirements on the impl of `std::convert::From<hashes::sha256d::Hash>` for `secp256k1::Message`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `bitcoin` due to previous error
```
This is confusing me because such `impl` [does exist](https://docs.rs/secp256k1/0.23.0/secp256k1/trait.ThirtyTwoByteHash.html#impl-ThirtyTwoByteHash-for-Hash%3CT%3E).

Digging deeper, I believe this might be due to a mismatch between the versions of `bitcoin_hashes` used in `rust-bitcoin` and `rust-secp256k1`, which are `0.11.0` and `0.10.0`, respectively. 

Interestingly, I think the approach taken [here](https://github.com/rust-bitcoin/rust-bitcoin/blob/03a0b260c1d7d87a530bf882079f84d083b7e147/src/util/taproot.rs#L82) does not work due to 58f94be.

I'm unsure about which could be the appropriate direction here :thinking: My bet is on matching the `bitcoin_hashes` version, but I'd love to read your thoughts...

**Comment by apoelstra** [comment]
We should update rust-secp I guess. Annoying because this will require a major version bump there. We should've coordinated this better ... I think I literally forgot that rust-secp depended on bitcoin_hashes and that we'd have to update things in order.

**Comment by arturomf94** [comment]
Sorry to be the bearer of these bad news! :/ 

Question: is there a specific reason why `rust-secp256k1` does not have a more relaxed restriction on `bitcoin_hashes`? Something like, `">=0.10"`?

**Comment by tcharding** [comment]
> I think I literally forgot that rust-secp depended on bitcoin_hashes and that we'd have to update things in order

I'll take the rap for that one, I did the release PR without checking if this would break things.

**Comment by apoelstra** [comment]
> Sorry to be the bearer of these bad news! :/
> 
> Question: is there a specific reason why `rust-secp256k1` does not have a more relaxed restriction on `bitcoin_hashes`? Something like, `">=0.10"`?

Prior to 1.0, cargo treats the minor version number as a major version number. There is no way you can tell it "use 0.10 or 0.11 or...", nor would we want to, because there are breaking changes between those releases.

**Comment by arturomf94** [comment]
> Prior to 1.0, cargo treats the minor version number as a major version number. There is no way you can tell it "use 0.10 or 0.11 or...", nor would we want to, because there are breaking changes between those releases.

Got it. Thanks for the clarification.

**Comment by tcharding** [comment]
I've tried to clean up my mess, please see:
- https://github.com/rust-bitcoin/rust-secp256k1/pull/475
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1103
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1104
