### ISSUE TITLE
Why Psbt implements consensus encoding traits?

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#934]
PSBT module defines a dedicated serialization traits, which are used for serializing data inside PSBT key maps. This is reasonable, since BIP-174 defines a specific serialization formats not used anywhere else (and not guaranteed to strictly follow consensus rules).

Nevertheless, at the high-level structures (`PartiallySignedTransaciton`, `Output`, `Input`) serialization is done via ... bitcoin consensus encoding implementation! Which is strange, since consensus roles are unrelated to PSBT serialization and instead PSBT serialization traits must be used as well (so their scope is defined in docs is extended just from key map value serialization to serialization of all PSBT data).

**Comment by apoelstra** [comment]
I don't understand this question. The consensus encoding of Bitcoin objects is not going to change, and neither will the BIP-174 encoding. If one can be used to produce the other, why wouldn't we share the same code?

**Comment by apoelstra** [comment]
Ah, I misunderstood! Yes, agreed, there is no reason that we should implement `consensus::Encodable` and `Decodable` for the PSBT types.

It looks like this dates back to Carl's original PSBT PR and we never noticed or revisited this.

**Comment by sanket1729** [comment]
I like doing this, and maybe this can be a good first issue. This is something that we don't need urgently but will conceptually cleanup the code.

**Comment by DanGould** [comment]
Is the preferred alternative implied in this question to replace `consensus::Encodable` and `Decodable` with dedicated serialization in `serialize.rs`, or something else like serde custom serialization? I'm confused because Psbt already has `#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]` attribute and I don't know why we want bip-defined and derive-generated serialization.

**Comment by dr-orlovsky** [comment]
I think the proper way is to use existing traits for the main `Psbt` instead of consensus encode/decode, as the rest of data types in psbt mod do.

**Comment by Kixunil** [comment]
I would even consider removing serde support for PSBT or reimplement it using BIP-174. (base64 in human readable, binary otherwise)

**Comment by dr-orlovsky** [comment]
Serde is good for printing PSBT for inspection (for instance in YAML format). Debugging printing is simply unreadable for real-world PSBTs

**Comment by Kixunil** [comment]
We could just have a better debug output or a separate module for that case.

**Comment by DanGould** [comment]
To answer the question _why_: 

I think the original reason Carl used consensus encoding is because that module contains convenient, generalized, and now well reviewed serialization patterns. The PSBT-pr reviewers knew the patterns and so ignored their repurpose. We should separate these patterns from the consensus module for their utility across the library. Then the consensus mod will contain consensus layer bitcoin p2p network implementation and a clean serialize mod will contain familiar utilities available for clean application level support for psbt and beyond.

**Comment by apoelstra** [comment]
Neat idea, but I worry that separating out the shared logic would add indirection to the consensus module, which could make things harder to review/understand.

(On the other hand, the consensus encodings have mostly not changed in literally a decade, so maybe this isn't a big deal.)

**Comment by Kixunil** [comment]
Sharing code like this could lead to breakages as Uncle Bob said in one of his books (can't remember which). If the behavior of shared function is changed because one of the encodings requires it it may affect the other encoding.

I *think* this could be mitigated by good naming and careful design. E.g. `encode_le_u16` instead of `encode_u16` would guarantee that the change would immediately be seen as wrong if one were to change byte order. Also if the PSBT spec says "use consensus encoding" anywhere we could use it internally.

Exposing consensus encoding is just confusing to the consumers.

@dr-orlovsky less code is not always the best choice. :) I guess the main problem is that some bytes are written as arrays instead of hexes? Maybe we should newtype those fields?

**Comment by sanket1729** [comment]
Here is another suggestion that I like

1) Make psbt::Serialize and psbt::DeSerialize traits private
2) Add these as methods to `impl Pbst`

We really don't need to expose how the psbt field serialization is being done to downstream users.

**Comment by tcharding** [comment]
This is part of the PSBT epic which is ongoing, seems like there is no urgent need for this in 0.29.0, please correct me if I'm wrong.

**Comment by Kixunil** [comment]
If it's possible to deprecate impls (I doubt so) then it'd be nice to do that but yeah, not a huge issue.
