### ISSUE TITLE
Use crates from RustCrypto org instead of rust-crypto

### ISSUE THREAD

**Issue by newpavlov** [rust-bitcoin/rust-bitcoin#98]
The following crates should cover all required functionality: `sha2`, `ripemd160`, `hmac`.

**Comment by TheBlueMatt** [comment]
I think we may end up wanting our own rust-bitcoin/hash-utils repo or something like that, as we'll likely want to steal some fun things like the optimized double-sha256-64-bytes functions from Bitcoin Core to optimize merkle tree building and the like: https://github.com/bitcoin/bitcoin/blob/4437d6e1f3107a20a8c7b66be8b4b972a82e3b28/src/crypto/sha256.cpp#L577

We may want to use RustCrypto for ripemd160 and hmac, but unless they're more optimized or have fixed bugs from rust-crypto, why bother moving from something stable (as in unmaintained so will never change) to something being changed, at least for crypto implementations?

**Comment by newpavlov** [comment]
Reasons which I can name are:
- significantly smaller dependency size, and as a consequence compilation time will be faster as well
- no_std and wasm friendliness
- completely pure Rust (if `asm` feature is not used)
- additional optimizations (e.g. `asm` feature today, or utilization of Intel SHA intrinsics in future)

And if you are worried about changes, you always can pin crates to exact versions.

**Comment by TheBlueMatt** [comment]
Yea, if/when we actually switch to something else we probably want to wrap it so that we can drop in our own asm when we want to optimize merkle tree. Note that one drawback of RustCrypto compared to rust-crypto is the use of an external "constant_time_eq" crate dep, which I'm skeptical LLVM won't optimize down to not-so-constant-time-eq https://github.com/cesarb/constant_time_eq/blob/master/src/lib.rs#L16
That said, its probably better than the one in rust-crypto, which doesn't build on anything except ARM and x86.

**Comment by newpavlov** [comment]
You always can check [assembly](https://godbolt.org/g/GZghqy), I've also checked `MacResult` behaviour with ctgrind and it didn't reveal any problems.

**Comment by TheBlueMatt** [comment]
In C it looks like folks mostly mark things as volitile, which at least forces the read/writes-to-tmp-var to happen, which should be a pretty significant improvement, even if also not a guarantee. Mostly I can't find any documentation for LLVM IR NoInline handling if you do an LTO (or some profile-guided optimization or something) pass.

**Comment by TheBlueMatt** [comment]
While subtle is probably better-maintained it looks like it does roughly the same thing under the hood (except instead of just XORing at the byte level it shifts down to one bit) but without the inline(never) until its done, and with an inline on the actual operation function, which seems much less general-purpose than you'd probably want, depends on how conservative you want to be, I suppose.

**Comment by apoelstra** [comment]
I've created a new crate which is sufficient for our purposes https://github.com/rust-bitcoin/bitcoin_hashes and depends only on `byteorder` (which rust-bitcoin also directly depends on, and which is small/simple enough I'm happy to just review it and keep it forever as a dep).

I'm not really concerned about constant-timeness for hashes. They're inherently branch-free (well, HMAC has a branch on key length, but key length is typically not a secret), use addition and bit-ops rather than multiplication or division, and within a few rounds (i.e. a few cpu cycles) they tend to completely scramble any secret input anyway.

**Comment by newpavlov** [comment]
@apoelstra 
Well, if you prefer NIH, then it's an approach to take. Though, from the ecosystem development point of view (i.e. distributing maintenance burden, focusing development efforts, providing more eyes to inspect source code), I don't think it's the right approach. Plus if downstream crate will depend on RustCrypto crates and `bitcoin` we will get code duplication.

Feel free to close this issue if you'll decide to go with `bitcoin_hashes`.

**Comment by apoelstra** [comment]
When the Rust ecosystem stops including random extraneous dependencies, breaking things in minor releases, and being unable to compile on Debian's compiler, I will stop "NiH"ing functions that have been standardized for decades and have no need to ever change or use bleeding-edge language features or generic arrays or what have you.

BTW RustCrypto's hash library does not compile with rustc < 1.20, even with all features disabled, because it depends on multiple things that depend on `block-buffer`, which depends on `generic-array`, which depends on `typenum`, which uses associated constants.

**Comment by newpavlov** [comment]
RustCrypto crates are very strict in their versioning. Breaking changes (even if it's minimum supported Rust version bump) are done only with minor version bump, plus crates are CI tested against declared MSRV. When we'll finally get const generics new `0.x+1` crate versions will be published, thus crates with `0.x` version constraint will not be broken. There was only a single case when these promise was broken, I've intentionally removed a buggy `VariableOutput` trait implementation from a crate to communicate issue to users.

If you really want to support Rust 1.14, then it's a valid reason to use your NIH implementation. Though I personally don't see much reason in doing it, as the mentioned Debian AFAIK packages Rust 1.24.

**Comment by apoelstra** [comment]
Thanks very much for your commitment to responsible dependency usage. Sorry for implying otherwise.

Unfortunately Debian stable ships 1.14.0 on arm64 and i386. Only on x86_64 do they have 1.24.

**Comment by TheBlueMatt** [comment]
rust-bitcoin will probably also want weird bitcoin-specific things like highly-optimized-double-sha256-of-two-32-byte-buffers so I think it makes sense to forge our own way anyway.

**Comment by apoelstra** [comment]
One weird bitcoin-specific-thing we already have is a `Sha256dHash` type whose user-visible serialization is hex-encoded in reverse order. :upside_down_face:

**Comment by newpavlov** [comment]
Well, having bitcoin-specific part does not mean you need to write your own implementation of several algorithms. Plus I can expose via feature gate [compress function](https://github.com/RustCrypto/hashes/blob/master/sha2/src/sha256_utils.rs#L263) which in future will support [hardware acceleration](https://github.com/RustCrypto/hashes/issues/51). But honestly I don't think you'll get a win bigger than several comparisons.

**Comment by TheBlueMatt** [comment]
It seems to shave quite a bit off in hash-heavy stuff, see https://github.com/bitcoin/bitcoin/pull/13191 (specifically the varsize -> size64 naive/1way benchmarks there).

**Comment by newpavlov** [comment]
Of course I was talking about general non-SIMD case. :)

**Comment by TheBlueMatt** [comment]
The benchmarks I was referencing were both non-SIMD.

**Comment by newpavlov** [comment]
I don't know what you had behind "naive" code (and don't have desire to look into it), for that I know it could've been sub-optimal. In case of `sha2` if you process two 32 bytes blocks you will not get wasteful copies, so overhead will be equal to zeroing out 32 byte buffer on stack and to several `if`s. I guess the main win will be from usage of constant padding block.

**Comment by jeandudey** [comment]
> rust-bitcoin will probably also want weird bitcoin-specific things like highly-optimized-double-sha256-of-two-32-byte-buffers so I think it makes sense to forge our own way anyway.

Well that isn't a valid reason to reimplement all hash algorithm that rust-bitcoin uses, only a new hash algorithm is implemented for that use case without rewriting all of them.

> One weird bitcoin-specific-thing we already have is a Sha256dHash type whose user-visible serialization is hex-encoded in reverse order.

That's not a much of a problem, the `Sha256dHash` could still exist and SHOULD be constructed from the output of the hash functions, probably the hash functions found in RustCrypto organization. Anyway newer types for that exact purpose can be created e.g. `ReversedSha256d`, or newer methods e.g. `reversed_str`, etc.

I think this crate shouldn't suffer from the NIH syndrome, RustCrypto crates are very small and can be easily reviewed. I have been reading the `bitcoin_hashes` project source code and the first thing I noted is that it isn't compatible with the `digest` crate that is becoming the *de facto* standard for hash functions.

PD: `Sha256dHash` type name is too long, `H256` is sufficient, the same for `Uint256`, `U256` is sufficient, but this is content for another discussion in another issue, parity-bitcoin uses this approach and it seems they are doing well with that without too much hassle.

**Comment by dpc** [comment]
@apoelstra 

> Unfortunately Debian stable ships 1.14.0 on arm64 and i386. Only on x86_64 do they have 1.24.

I think I've seen you mention this many times already as a root of the problem. It seems to me that it would be easier to just accept that at least at the current state, distribution provided rust compiler binaries are going to be constantly stale, for years to come, and are therefore not very usable for project under active development. Rust is just not yet 50 years old and the roadmap is clear: new feature will be introduced every release, and people/projects will want to use them.

I am not sure what exactly are yours and other potential devs/users goals, but whatever they are, maybe it would be easier to adapt the rustup workflow and maintain and test against minimal supported version, that would (out of necessity) roll forward continously (but just not _too_ fast).

**Comment by dpc** [comment]
Whatever users does `rust-bitcoin` have and will have in the future, they have implicitly accepted that they are using a language under active development, with a relatively immature ecosystem, and they will have to pay the price, by having to deal with changes. `rustup`, `cargo` and other tooling is there to help everyone.

**Comment by apoelstra** [comment]
Of course it's not compatible with `digest`, `digest` does not compile for me and it also has a nontrivial dependency tree.

My target users are people who care about being able to build their projects deterministically, vendor their dependencies and review the code that they've vendored. Rust is perfectly capable of supporting that, and I see no reason to introduce random dependencies on projects that undermine my ability to do so.

A language that hit 1.0 three years ago now is not "under active development" to the point where all of its users must be constantly updating their toolchains by replacing unsigned binaries with other ones. It would be obnoxious to require that, and it reflects poorly on the Rust community that there are such large portions of it who seem to think otherwise.

**Comment by TheBlueMatt** [comment]
I think Andrew's point here was that there *are* projects that use rust-bitcoin *in production* and would like to use stable Debian and similar distros because they're stable and for a security-critical server and product that's pretty much ideal. Thus, accepting a newer rustc requirement would absolutely screw over some users. Other rust-bitcoin projects have later rustcs because they don't have this issue.

**Comment by dpc** [comment]
> I think Andrew's point here was that there *are* projects that use rust-bitcoin *in production* and would like to use stable Debian and similar distros because they're stable and for a security-critical server and product that's pretty much ideal. 

I understand that, and I think it would be wonderful if they could build as much code as possible using rustc that comes with it. Similarly with any other Linux/OS distribution. I am not saying that anyone should rush to force others to update compiler. I to understand the value of stability/compatibility with older versions. The oldest rustc that can be supported, the better.

But if it comes in conflict with keeping up with Rust ecosystem, I think it would be better to ask these users to update their compiler, maybe helping them to find a way that would be a compromise between their security goals / convenience, and active development needs.

Most Rust projects (and many are used in production for important projects), maintains a minimal supported version, that gets bumped from time to time. I just think, at current state of Rust, a 1 year old compiler version is more reasonable that almost 2 years.

I'm not a Debian user, but I don't think there was anything magical about 1.14, and Debian maintainers are preparing new updates:
https://packages.debian.org/search?keywords=rust&searchon=names&suite=all&section=all
If I read it correctly, there is even 1.24 for amd64:

```
Package rustc

    stretch (stable) (rust): Rust systems programming language
    1.24.1+dfsg1-1~deb9u2: amd64
    1.14.0+dfsg1-3: arm64 i386 
```

**Comment by TheBlueMatt** [comment]
Are there any miscompilation bugs in Rust 1.14? If not, why should they be required to upgrade when part of their security-critical system depends on it? What if they've already done review of parts of it (I don't know if they have, but they might have), why should they be required to spend the time and money to review it again?

Are there any bugs in rust-crypto? Aside from possible performance improvements, what are we gaining by switching hash function implementations? Personally, I'd much much rather use a completely unmaintained and unupdated hash function implementation than one that is changing, at least for security-critical software, if that means copying an existing implementation into our own repo (with appropriate attribution), even better.

**Comment by apoelstra** [comment]
You are welcome to fork the project and require your users upgrade their compilers whenever one of your dependencies requires it, and to even deliberately include dependencies maintained by people who like to do this.

This project has actual users who are funding development, including myself, who have complained about the difficulty of reliably obtaining a toolchain, dealing with neverending lists of dependencies, vendoring said dependencies, auditing updates of them, fighting with cargo whenever minor releases break compilation, etc.

We are not going to break things for these users. Nobody has given a good reason to do so. We have a long-stated policy of minimizing dependency trees and maintaining compatibility with 1.14.  Some users have complained about breakage due to unnecessary dependencies in rust-crypto (see #96). It is obviously not a solution to replace it with another project full of unnecessary dependencies which cause breakage.

Matt and I both have many years' experience writing high performance high-assurance cryptographic software. I think we can handle implementing a couple of mathematical functions that are all over a decade old.

**Comment by dpc** [comment]
I think it's a fair game. Some people need this to compile on Stable Debian, or whatever else requirements, security policies or preferences they have, pay for etc. No hard feeling. However, the other arguments don't really convince me, and @newpavlov said exactly what I think.

> Matt and I both have many years' experience writing high performance high-assurance cryptographic software. I think we can handle implementing a couple of mathematical functions that are all over a decade old.

With all due respect, I think this is an attitude from a C/C++ land, where everybody is afraid to change a single line of code anywhere because it might explode, shared code is scarce and cooperation is rare. It ignores both the state of Rust as an immature language and its cooperation-inducing features.

While I do see some merit there, I don't think it works for Rust ATM, (somewhat regrettably) and I would rather use (and potentially contribute to) a fork that integrates well with the ecosystem, instead of the one that will always be potentially a hindrance to integrate with other code.  Business-wise, I would rather pay for reviewing shared code, and use locking for ensuring security, than maintain own, potentially hard to upgrade code.

But I fully acknowledge that I'm mostly just leaching on somebody elses work (which I am thankful for) so I'll show myself the door now. :)

**Comment by dpc** [comment]
@apoelstra I don't want to get into the discussion, just making sure you're aware:
 https://medium.com/@shnatsel/how-rusts-standard-library-was-vulnerable-for-years-and-nobody-noticed-aebf0503c3d6
